### ISSUE TITLE
Buff Filters

### ISSUE THREAD

**Issue by SaganOmMIg** [ElvUI-WotLK/ElvUI#101]
I seem to have a problem with the "buff filters" in particular the Turtle Buff filter. I can't make them show properly on the praty/raid frames. Semms to blacklist the spells rather then whitelist them. 

Thanks in advance

**Comment by xeek** [comment]
I have the same Issue with Turtle and CCDebuff Filters

**Comment by crumdidlyumshis** [comment]
I haven't noticed this issue. Close or update needed?
