### ISSUE TITLE
Suggestion - Totems Bar Resize Option

### ISSUE THREAD

**Issue by Nzith** [ElvUI-WotLK/ElvUI#122]
Is it possible to add more options to the totems bar? Basically add the ability to resize the bar.
![screenshot_1](https://cloud.githubusercontent.com/assets/16617127/12708229/034539c8-c8a6-11e5-87e0-5041377f1207.jpg)
![screenshot_2](https://cloud.githubusercontent.com/assets/16617127/12708230/094058e4-c8a6-11e5-8184-6e0256e0e8ec.jpg)

**Comment by crumdidlyumshis** [comment]
This would be nice to have.

**Comment by Bunny67** [comment]
partially added

**Comment by crumdidlyumshis** [comment]
Looks almost finished ^^

Only issue is totem buttons not skinned. Good job!

**Comment by Bunny67** [comment]
finished, check
