### ISSUE TITLE
Does not work with WIM addon

### ISSUE THREAD

**Issue by Luisu11** [ElvUI-WotLK/ElvUI#125]
it does not work with wim addon for whispers the chat goes crazy

**Comment by Bunny67** [comment]
Was genau funktioniert nicht? Kann ein screenshot, wie sie sein sollte

**Comment by zypher11** [comment]
If you turn on Wow Instant Messenger addon, it essentially breaks the chat. It reverts all chat windows to the default UI chat windows entirely. I did not test to see if WIM still actually worked in that state.

**Comment by crumdidlyumshis** [comment]
I just tested and it works fine! I will see if I can add skin later for ElvUI_AddonSkins.

Close if needed.

**Comment by crumdidlyumshis** [comment]
Close, this works fine. Just needs skin in AddonSkins
