### ISSUE TITLE
Player's class backdrop isn't correct.

### ISSUE THREAD

**Issue by Tiny6** [ElvUI-WotLK/ElvUI#130]
![qq 20160226083121](https://cloud.githubusercontent.com/assets/16896017/13347183/ff5992b0-dc63-11e5-9bbf-f61fbe73a013.png)
![qq 20160226083152](https://cloud.githubusercontent.com/assets/16896017/13347185/043ffc6a-dc64-11e5-8ce9-d7bd4dfd12e1.png)

**Comment by Bunny67** [comment]
Google Translete:
All also does not work?

Ru:
Все также не работает?

**Comment by crumdidlyumshis** [comment]
Seems to work fine. Close?
