### ISSUE TITLE
Pet Resistance Icons

### ISSUE THREAD

**Issue by Alx1502** [ElvUI-WotLK/ElvUI#145]
I'm not sure but those arrows seems that are not skinned, also the same for the pet resistance icons.
Close this if i'm wrong.
![pet 2](https://cloud.githubusercontent.com/assets/16160069/14272310/ac392daa-fb0a-11e5-8384-e13066dfaf9c.png)
![pet 3](https://cloud.githubusercontent.com/assets/16160069/14272312/affae85c-fb0a-11e5-8d5b-f1c11cd691e8.png)
![pet elvu](https://cloud.githubusercontent.com/assets/16160069/14272316/b4144bea-fb0a-11e5-9693-9f3714b58504.png)

**Comment by Alx1502** [comment]
![adasd](https://cloud.githubusercontent.com/assets/16160069/14272480/035565d0-fb0c-11e5-8fa0-8582c4af6063.png)
I think it should look like these arrows from the auction house dressing room

**Comment by Alx1502** [comment]
It seems that i was wrong about the Rotate arrow buttons, they are skinned but to me somehow the original looks better, thats why i thought it was not.

![compare](https://cloud.githubusercontent.com/assets/16160069/14301348/bf97349c-fb9f-11e5-9266-977695abb6b8.png)
So its only the pet resistance icons that are not skinned.

**Comment by crumdidlyumshis** [comment]
Probably close?

**Comment by crumdidlyumshis** [comment]
Yeah these need to be skinned. However, if you use ElvUI_Bunny it eliminates these issues.

**Comment by Bunny67** [comment]
fixed
