### ISSUE TITLE
Expand Button

### ISSUE THREAD

**Issue by Alx1502** [ElvUI-WotLK/ElvUI#146]
In some Frames the Expand button is not skinned. 
Some examples:
![wowscrnshot_040616_030150](https://cloud.githubusercontent.com/assets/16160069/14302125/3bef3df4-fba6-11e5-9aab-e1762695225b.jpg)
![wowscrnshot_040616_030903](https://cloud.githubusercontent.com/assets/16160069/14302127/3f21c87a-fba6-11e5-90b3-21bf3387a082.jpg)
![wowscrnshot_040616_031245](https://cloud.githubusercontent.com/assets/16160069/14302128/420ce092-fba6-11e5-99ec-814212f346a7.jpg)
![wowscrnshot_040616_031350](https://cloud.githubusercontent.com/assets/16160069/14302133/4514793a-fba6-11e5-9b22-f83ef15f2640.jpg)
![wowscrnshot_040616_031426](https://cloud.githubusercontent.com/assets/16160069/14302134/487fcdcc-fba6-11e5-8658-d5577051f39f.jpg)

**Comment by crumdidlyumshis** [comment]
Seems like @Apollyonn will have these skinned soon judging by the speed he's been skinning the other frames. ^^

**Comment by crumdidlyumshis** [comment]
Any updates on this @Bunny67 or @Apollyonn ?

**Comment by Bunny67** [comment]
fixed
