### ISSUE TITLE
Hunter Pet Happiness Indicator/Icon

### ISSUE THREAD

**Issue by mimmordino** [ElvUI-WotLK/ElvUI#151]
Currently the pet unit frame is missing the happiness indicator so we know when our pet needs to be fed. Is it possible to add that feature to the frame?

**Comment by Lexblack** [comment]
Type "happiness" at the Edit box of Unitframes, Player Frame.

**Comment by mimmordino** [comment]
In the Text Format field? There are several edit boxes on that page including Custom Texts and Text Format, and that's just in the "Health" area of Player Frame.

**Comment by Lexblack** [comment]
Yes

**Comment by mimmordino** [comment]
Tried that but nothing display wise changes on the pet unitframe. Am I missing something obvious?

![Happiness Settings](https://cloud.githubusercontent.com/assets/5108617/14693033/94055abc-0729-11e6-92f7-4668ddf32bd4.png)

**Comment by Lexblack** [comment]
Unitframes>Player Frame>Text Format Edit Box

**Comment by mimmordino** [comment]
That only displays the text happiness next to my health value on the Player unit frame.

![4-20-2016 7-20-30 pm](https://cloud.githubusercontent.com/assets/5108617/14693452/0c60e424-072d-11e6-8da7-53424036e0c8.png)

**Comment by Lexblack** [comment]
Sorry my bad, Type it on the Pet Frame, it should show a happy face or a sad face, like this.
![wowscrnshot_042116_023021](https://cloud.githubusercontent.com/assets/16202997/14693614/2681bfb8-0769-11e6-8eca-4d28d452651c.jpg)

**Comment by mimmordino** [comment]
That's ok in the interim, thanks for the help. However, if the author is willing to add the feature I think the pet happiness icon with the changing in color would look more polished if it was added to one of the corners or sides of the pet unit frame.

**Comment by crumdidlyumshis** [comment]
Close? Or is something else in the works?

**Comment by crumdidlyumshis** [comment]
I think this could be done. But it's probably low on the priority list right now.

**Comment by Bjonnfesk** [comment]
> Sorry my bad, Type it on the Pet Frame, it should show a happy face or a sad face, like this.
> ![wowscrnshot_042116_023021](https://cloud.githubusercontent.com/assets/16202997/14693614/2681bfb8-0769-11e6-8eca-4d28d452651c.jpg)

Can't get this to work on WoW Classic with ElvUI v1.03. It just shows "[happiness]" verbatim in the health bar of my pet.

**Comment by LybrialsGit** [comment]
Yep. Does not work in classic wow.

**Comment by Bjonnfesk** [comment]
> Use this:
> 
> ```
> [happiness:icon]
> ```

Thanks, worked!

**Comment by Westfallx** [comment]
Select the Custom Texts tab and create the happiness icon on it, you can control the size of the icon.

**Comment by xxauroraxx** [comment]
There is a new "Happiness" tab within the pet frame, however the [Happiness] tag no longer seems to function whatsoever. Is there something I'm missing?

[Happiness:icon]
[Happiness:discord]

Neither work in the health or name tabs.

**Comment by omgpaladin** [comment]
@xxauroraxx and anyone else reading this, it must be lower case, for ex:
```
[happiness] # text smileys, such as :)
[happiness:icon] # WoW happiness icon
[happiness:discord] # emoji 😍🙁
```
