### ISSUE TITLE
Suggestion - GCD Bar Possibly using Swing Timer

### ISSUE THREAD

**Issue by felenaa** [ElvUI-WotLK/ElvUI#153]
Maybe an option to have an option for the swing timer to show for the GCD? I'm thinking more so for healers or casters. If not, possibly ideas for self modifications? Thanks.

**Comment by Bunny67** [comment]
http://mods.curse.com/addons/wow/global-cooldown-bar ?

**Comment by felenaa** [comment]
Yes! Thank you. I can try that when I get home not sure if it will work on 3.3.5, but I will give it a go and see what happens.

**Comment by felenaa** [comment]
I did some changes to my copy of oUF_Swing.lua; https://github.com/felenaa/ElvUI_SwingBar/blob/master/ElvUI_SwingBar/oUF_Swing.lua it works for what I'm doing but I could not get it fully working along with the Auto-Shoot and Shoot. Melee worked fine. I'll leave it in case anyone else wants to take a stab at it.

**Comment by crumdidlyumshis** [comment]
Good suggestion! Any thoughts on this? @Bunny67

**Comment by Bunny67** [comment]
author seem to decide issue

**Comment by crumdidlyumshis** [comment]
Close?

**Comment by Bunny67** [comment]
Yes :)
