### ISSUE TITLE
"Unknown" level on nameplates is displayed as my current level instead of "??"

### ISSUE THREAD

**Issue by datbunneh** [ElvUI-WotLK/ElvUI#162]
Player's level is shown as "??" on tooltip but on nameplate it shows my current level.

**Comment by crumdidlyumshis** [comment]
I honestly have never seen this issue. Can anyone reproduce this? @datbunneh if you could provide a screenshot and anything else you may have done to see this, that would help :+1:

**Comment by datbunneh** [comment]
I guess I won't be able to reproduce it right now. If I ever encounter it again, I will reopen this issue and'll try my best to provide a screenshot.
