### ISSUE TITLE
Deathknight Runebar

### ISSUE THREAD

**Issue by Soshiy** [ElvUI-WotLK/ElvUI#165]
The Runebar is kind of bugged.
It is greyed out on default, and resets to full when a rune is used ... so it works the opposit way then it should..?

Kind of hard to describe..
Tried to reinstall elvui, no other addons aktive - everything fresh

Without addons enabled the runebar works fine, any help? :(

**Comment by Bunny67** [comment]
Screenshot can be?

**Comment by Soshiy** [comment]
![wowscrnshot_051616_205507](https://cloud.githubusercontent.com/assets/19389587/15300404/ca2b037e-1ba8-11e6-970c-7d927c36b627.jpg)
![wowscrnshot_051616_205527](https://cloud.githubusercontent.com/assets/19389587/15300405/ca510cc2-1ba8-11e6-9066-810e41391684.jpg)

**Comment by Soshiy** [comment]
first one is outfight, every rune is greyed out

second one, i've used one blood rune

so it shows how long it needs to recharge, not like the standard runes work :<

**Comment by Bunny67** [comment]
Strange, since I have all okay
![wowscrnshot_051616_222359](https://cloud.githubusercontent.com/assets/5816685/15301220/4c3b9048-1bb5-11e6-80d8-178bb1a6d0fa.jpg)

**Comment by Soshiy** [comment]
really strange... well don't know what it could be, maybe reinstalling wow, im sad ;o

**Comment by Bunny67** [comment]
It used to be okay?

**Comment by Soshiy** [comment]
Yes, but i havent played in a long time..

Started wow and the runes were bugged at this time, updating made no different

**Comment by Bunny67** [comment]
While I do not know how to help :(

**Comment by Soshiy** [comment]
I'm reloading wow, in about 2 hours i'll write u again ;)

thanks anyways :+1:

**Comment by Soshiy** [comment]
well, like expected no change.. damn D:

**Comment by Bunny67** [comment]
What is your client? language

**Comment by Soshiy** [comment]
German

**Comment by crumdidlyumshis** [comment]
I don't see any issues going on with this still. Maybe close?
