### ISSUE TITLE
Suggestion: When importing profile, also include the action bar paging

### ISSUE THREAD

**Issue by shinpou** [ElvUI-WotLK/ElvUI#171]
When importing another characters elvui profile, also include any action bar paging settings in the profile.

**Comment by crumdidlyumshis** [comment]
I will test this later. It may be fixed already.

**Comment by Bunny67** [comment]
The problem disappeared?

**Comment by crumdidlyumshis** [comment]
I havent seen any issue with this. Maybe close?
