### ISSUE TITLE
how can i change the color for disable buttons /not active, [grayed out] ?

### ISSUE THREAD

**Issue by raykai** [ElvUI-WotLK/ElvUI#204]
i have a bf that has a vision problems and has a hard time with seeing if the buttons are Active or Disable [grayed out] in the action bar.

i was wandering if there is a way to Chang the grayed out color to say blue if its Disable [grayed out] i searched for an addon but i dont think there is one for this.

i know we can change the color for out of range and out of power but not for not active buttons or should i say Disable [grayed out]

**Comment by Kkthnx** [comment]
Hmm. I'll look into adding this for him.

**Comment by crumdidlyumshis** [comment]
This actually would be a nice feature for some. People with colorblindness need a few options within the config. This could very well be possible.

**Comment by Bunny67** [comment]
I don't understand the question :( text is google translated incorrectly :(

**Comment by crumdidlyumshis** [comment]
https://en.wikipedia.org/wiki/Color_blindness

I think she is talking about Active buttons versus Disabled buttons.

https://youtu.be/s5QBMeeTrZc

**Comment by Bunny67** [comment]
color support has been added in version 4+(cata)
I'm not know how to on to 3.3.5a this implement it

**Comment by crumdidlyumshis** [comment]
Suggestion:

Add checkbox "Color Blindness" under General settings.

If yes:  show two or more Color Pickers:

Active Button
Disabled Button
Enabled Button

![untitled](https://cloud.githubusercontent.com/assets/7307335/18178075/82733de6-7042-11e6-817a-9e07e70f22db.png)

else:

![untitled2](https://cloud.githubusercontent.com/assets/7307335/18178103/9971bee6-7042-11e6-8ad4-f216c1f3482c.png)

**Comment by Bunny67** [comment]
It will be difficult to implement :(

**Comment by raykai** [comment]
yes im talking about the color for the Disabled buttons [grayed out] as when you run out of mana and some spells button grayed out i need a option to chang the color of when there grayed out

**Comment by raykai** [comment]
let me see if i can find this Color Blindness option.

**Comment by raykai** [comment]
cant seam to find it on V10.16

**Comment by Bunny67** [comment]
on which version of the game you play ?

**Comment by raykai** [comment]
hmmm i see this github is not the main elvui dev would be good to say so :P 

im on the live game wow leagon. i just say this is for old wotlk

**Comment by crumdidlyumshis** [comment]
Yeah maybe close then. The question you are asking is possible to add to this version. I just don't know if Bunny67 wants to invest the time to make it happen. Maybe a separate addon might work.
