### ISSUE TITLE
ElvUI_ContainerFrame - CoinPickupFrame

### ISSUE THREAD

**Issue by crumdidlyumshis** [ElvUI-WotLK/ElvUI#210]
Am I incorrect or when I left click on the coins, I should be given a CoinPickupFrame?

![wowscrnshot_090116_144205](https://cloud.githubusercontent.com/assets/7307335/18181776/834796bc-7052-11e6-98aa-005bc56938c2.jpg)

**Comment by Bunny67** [comment]
Why you need it?)

**Comment by crumdidlyumshis** [comment]
I don't need it :)

It would appear logical to click the currency and a CoinPickupFrame would appear above ElvUI_ContainerFrame.

If unnecessary, please close.

**Comment by Bunny67** [comment]
Implement this function is unfortunately not work :(

**Comment by crumdidlyumshis** [comment]
No problem!

**Comment by Bunny67** [comment]
It is necessary to change the text of gold, resulting in a non-working style of the text Gold

**Comment by crumdidlyumshis** [comment]
No worries! But at least skin: https://github.com/ElvUI-WotLK/ElvUI/issues/209

:)
