### ISSUE TITLE
Chat Bubble - Strata

### ISSUE THREAD

**Issue by crumdidlyumshis** [ElvUI-WotLK/ElvUI#211]
I think the strata of the chat bubble is too much.

Retail

![wowscrnshot_090116_163002](https://cloud.githubusercontent.com/assets/7307335/18185098/98741b64-7061-11e6-8da5-7c7efaf2a745.jpg)

WotLK

![wowscrnshot_090116_161322](https://cloud.githubusercontent.com/assets/7307335/18185117/bae8e7f6-7061-11e6-9178-85bc4a86a6c6.jpg)

**Comment by Bunny67** [comment]
It seems to me, and it was intended

**Comment by crumdidlyumshis** [comment]
Looks it it was!

**Comment by henryman93** [comment]
Is it possible to edit the strata? It makes the skin unusable if it covers relevant UI frames like raidframes

**Comment by henryman93** [comment]
Quoting @snwflake for the solution:

https://github.com/ElvUI-WotLK/ElvUI/blob/master/ElvUI/modules/misc/chatBubbles.lua#L201

possible value (most-back to most-front):
BACKGROUND
LOW
MEDIUM
HIGH
DIALOG
FULLSCREEN
FULLSCREEN_DIALOG
TOOLTIP
