### ISSUE TITLE
Suggestion - Tweak Tabs

### ISSUE THREAD

**Issue by crumdidlyumshis** [ElvUI-WotLK/ElvUI#212]
Suggestion:

Retail

![wowscrnshot_090116_163727](https://cloud.githubusercontent.com/assets/7307335/18185322/b9aa0482-7062-11e6-9637-351014e1a87a.jpg)

WotLK

![wowscrnshot_090116_163717](https://cloud.githubusercontent.com/assets/7307335/18185337/cd1b3fae-7062-11e6-9f25-0967a3d42a3f.jpg)

**Comment by Bunny67** [comment]
Unfortunately on 3.3.5a this cannot be done

**Comment by crumdidlyumshis** [comment]
No problem. Just thought I would suggest!
