### ISSUE TITLE
Action-bar Stance Switching 

### ISSUE THREAD

**Issue by crumdidlyumshis** [ElvUI-WotLK/ElvUI#214]
https://youtu.be/noCmSUp2fjQ

**Comment by Bunny67** [comment]
https://youtu.be/XdrV-dIFl4U

**Comment by crumdidlyumshis** [comment]
Hmm maybe dominos conflicts

**Comment by Bunny67** [comment]
dominos not support

**Comment by crumdidlyumshis** [comment]
So if dominos or bartender installed, they do not work with ElvUI?

**Comment by Bunny67** [comment]
Disable actionbars module

**Comment by crumdidlyumshis** [comment]
Dang. I deleted dominos. Wish there was a working action-bar addon.

**Comment by crumdidlyumshis** [comment]
I am going to try to make a ElvUI_ActionBars replica for 3.3.5 using Extra Bar addon.

I tried out this addon last night and it worked nicely with ElvUI. Only issue I saw was the button options wouldn't allow me to do button spacing and button columns.

https://wow.curseforge.com/addons/extra-bar/
