### ISSUE TITLE
Achievements

### ISSUE THREAD

**Issue by Tristan000** [ElvUI-WotLK/ElvUI#216]
![1](https://cloud.githubusercontent.com/assets/20983405/18226650/470a6af0-7217-11e6-842b-77922dfc5885.jpg)

![2](https://cloud.githubusercontent.com/assets/20983405/18226652/550a1146-7217-11e6-8151-eccab7abc995.jpg)

Now i'm rich :D

**Comment by Bunny67** [comment]
:D
Later fix

**Comment by Bunny67** [comment]
animation text disabled for this statusbar
