### ISSUE TITLE
Проблема с ползунками в журнале заданий.

### ISSUE THREAD

**Issue by SlavaTenhi** [ElvUI-WotLK/ElvUI#218]
При 20+ квестах ползунки ElvUI, листая вниз, остаются на месте, но и появляются стандартные.
Если не листать вниз
![wowscrnshot_090616_205725](https://cloud.githubusercontent.com/assets/22032649/18285126/90231e48-7475-11e6-8729-53f67dc80b12.jpg)
Если листать вниз
![wowscrnshot_090616_205731](https://cloud.githubusercontent.com/assets/22032649/18285167/baed975c-7475-11e6-975a-9699c5358984.jpg)

**Comment by Bunny67** [comment]
Исправил
