### ISSUE TITLE
Minimap icon position fix?

### ISSUE THREAD

**Issue by GitNadleeh** [ElvUI-WotLK/ElvUI#220]
Is there any chance of a change being made to the way ElvUI handles the minimap icons?
There is a thread by someone suggesting that it is possible, but the modification they made is no longer available to [download](http://www.dalaran-wow.com/forums/community/ui-customization/topic/5885/square-minimap-bar-buttons-for-elvui-backport), and no one seems to have it .

Unfortunately by default I am stuck with this [mess](https://i.imgsafe.org/00fefb6085.png) :(
I would really appreciate a "fix" for this!

**Comment by Bunny67** [comment]
https://github.com/ElvUI-WotLK/SquareMinimapButtons not working?

**Comment by GitNadleeh** [comment]
Hrm! That is a wonderful addon, though it is not catching a few of them(Outfitter, Atlas, Fishing Buddy, Enchantrix).
Is there a way to get that to dock to the ElvUI minimap?
I cannot see a way to move the frame manually.
Thanks!

**Comment by Bunny67** [comment]
Do not understand: "Is there a way to get that to dock to the ElvUI minimap?
I cannot see a way to move the frame manually."

Google translete unclear :(

**Comment by GitNadleeh** [comment]
Hrm, in the first screenshot embedded in the page i linked("download"), the icons were docked on the left side of the ElvUI Minimap, how can I do that too?

**Comment by Bunny67** [comment]
![wowscrnshot_090716_184148](https://cloud.githubusercontent.com/assets/5816685/18318552/c5d5abc2-752a-11e6-90c5-58d7e97aea36.jpg)

**Comment by GitNadleeh** [comment]
Your square mini map icons are not attached to the action bar at the side, like [mine](https://i.imgsafe.org/05c35620a1.png).

**Comment by crumdidlyumshis** [comment]
You can move the actionbar around with the movers. I don't see any issues at the moment.

**Comment by crumdidlyumshis** [comment]
When the bar is enabled, the UI needs reload.

**Comment by Bunny67** [comment]
Download https://github.com/ElvUI-WotLK/ElvUI_MinimapButtons
If you have a problem, report it
