### ISSUE TITLE
+/ - Toggle Skin

### ISSUE THREAD

**Issue by crumdidlyumshis** [ElvUI-WotLK/ElvUI#224]
![world of warcraft 9_9_2016 11_55_13 am](https://cloud.githubusercontent.com/assets/7307335/18395602/b4b0404a-7684-11e6-8b1b-9a6c75bd54c3.png)
![world of warcraft 9_9_2016 11_55_31 am](https://cloud.githubusercontent.com/assets/7307335/18395604/b5f7833c-7684-11e6-942b-94bfd3dd1ab3.png)

**Comment by crumdidlyumshis** [comment]
Disabled +/- needs skin.

Trainer

![world of warcraft 9_9_2016 2_58_48 pm](https://cloud.githubusercontent.com/assets/7307335/18401032/14f53e1a-769e-11e6-9cf6-fcef2202231e.png)

**Comment by crumdidlyumshis** [comment]
Raid Browser

![world of warcraft 9_9_2016 3_17_05 pm](https://cloud.githubusercontent.com/assets/7307335/18401551/a54100b0-76a0-11e6-878d-626ed8298786.png)

**Comment by Bunny67** [comment]
it does not work :)

**Comment by crumdidlyumshis** [comment]
Boo :(

Oh well.
