### ISSUE TITLE
Выпадающее меню выбора локации в Даларане на карте.

### ISSUE THREAD

**Issue by freesay** [ElvUI-WotLK/ElvUI#227]
Давненько уже эта штука глаз мозолит. Можно ли подправить недочет этот?
![wowscrnshot_091016_103429](https://cloud.githubusercontent.com/assets/19500175/18408804/d5018b7e-7742-11e6-859d-18e07e4f9cb5.jpg)

**Comment by Bunny67** [comment]
Должно быть исправлено
