### ISSUE TITLE
Выделение фрейма выбранной цели.

### ISSUE THREAD

**Issue by freesay** [ElvUI-WotLK/ElvUI#228]
Слушай, была раньше такая штука классная, как выделение фрейма выбранной цели, в группе или в рейде. Ну, вот, например, в группе, выбираю я лока в таргет, чтоб подхиллить, скажем, и его фрейм выделяется фиолетовой подсветкой, под стать отображению агро, только в цвет класса. Сейчас такой штуки нет. Весьма досадненько =( 
![wowscrnshot_091016_130235](https://cloud.githubusercontent.com/assets/19500175/18409731/d63ba2d0-7757-11e6-8f19-61b544e6eb77.jpg)

**Comment by Bunny67** [comment]
В настройках группы есть эта настройка, по умолчанию выключена

**Comment by freesay** [comment]
Упс, не увидел, вероятно. Спасибо.
