### ISSUE TITLE
AddOnSkins does not work with TellMeWhen v2.4.1

### ISSUE THREAD

**Issue by datbunneh** [ElvUI-WotLK/ElvUI#230]
Icons are not skinned and error on startup:

`Message: ...erface\AddOns\ElvUI_AddOnSkins\addons\tellMeWhen.lua:10: attempt to call global 'TellmeWhen_GetActiveTalentGroup' (a nil value)
Time: 09/10/16 15:57:43
Count: 10
Stack: [C]: in function ``TellmeWhen_GetActiveTalentGroup'
...erface\AddOns\ElvUI_AddOnSkins\addons\tellMeWhen.lua:10: in function <...erface\AddOns\ElvUI_AddOnSkins\addons\tellMeWhen.lua:9>
[C]: in function ``TellMeWhen_Group_Update'
Interface\AddOns\TellMeWhen\TellMeWhen.lua:701: in function ``TellMeWhen_Update'
Interface\AddOns\TellMeWhen\TellMeWhen.lua:728: in function <Interface\AddOns\TellMeWhen\TellMeWhen.lua:719>`

**Comment by Bunny67** [comment]
WotLK version 1.2.5b1
https://wow.curseforge.com/addons/tellmewhen/files/8-tell-me-when1-2-5b1/

**Comment by datbunneh** [comment]
Yes, but it's terrible, there is no reason to use it for anyone when there is version 2.4.1 available. It's not 100% competible with 3.3.5 but as it's suppotring roughly 80-90% of it, it's already more than 1.2.5 can offer. Please consider to switch to this one.

**Comment by Bunny67** [comment]
update addonSkins, check

**Comment by datbunneh** [comment]
@Bunny67 Awesome, so far looks good. Now I can drop OmniCC and ButtonFacade out. Thanks!
