### ISSUE TITLE
Multiple leaders on Raid Frames

### ISSUE THREAD

**Issue by datbunneh** [ElvUI-WotLK/ElvUI#232]
Don't know if the problem is there, but I've disabled my Party Frames and use my general Raid Frames for groups from 2 up to 25 people. And when I join RDF sometimes I see "leader" icons over 2-3 people frames.
![multiple_leaders](https://cloud.githubusercontent.com/assets/9550798/18412157/c78812d0-7790-11e6-8794-73d89346309c.png)

**Comment by Bunny67** [comment]
https://github.com/ElvUI-WotLK/ElvUI/issues/88

**Comment by Bunny67** [comment]
I don't know how to fix it :(

**Comment by datbunneh** [comment]
@Bunny67 Will try to look into this myself. But I'm neither very good at Lua nor at wow api though.

**Comment by datbunneh** [comment]
Seems like {{UnitIsPartyLeader(unit)}} simply returns a wrong value.

**Comment by Mangos02** [comment]
i though the crown also showed the guide and the leader. maybe put a different guide icon of possible?

**Comment by crumdidlyumshis** [comment]
@Mangos02 Good suggestion, very well could be a server side issue.
