### ISSUE TITLE
Timestamp and Chat Style settings are missing with ElvUI enabled

### ISSUE THREAD

**Issue by datbunneh** [ElvUI-WotLK/ElvUI#233]
I turned on ElvUI timestamps and was very confused trying to find how to turn off the default ones (as there is no reason to have both). Spent like 10 minutes trying to find them anywhere until I tried to turn off the ElvUI and that did the trick.

![social_settings](https://cloud.githubusercontent.com/assets/9550798/18412494/a6cea902-7798-11e6-97a1-601f257a00b9.png)

![social_settings2](https://cloud.githubusercontent.com/assets/9550798/18412520/30f75bb0-7799-11e6-93fc-03003096b7b4.png)

**Comment by Bunny67** [comment]
ChatStyle not support
Timestamps disable in elvui config

**Comment by datbunneh** [comment]
@Bunny67 Those timestamps in ElvUI config are different. You can have both at the same time.

**Comment by Bunny67** [comment]
Now you can disable

**Comment by datbunneh** [comment]
@Bunny67 Thanks!
