### ISSUE TITLE
как мне отключить проверку версии, это вызывает лаги

### ISSUE THREAD

**Issue by silentwinter** [ElvUI-WotLK/ElvUI#235]
как мне отключить проверку версии, это вызывает лаги

**Comment by Bunny67** [comment]
Не совсем понял, появляется предупреждение об обновлении и начинает лагать?

**Comment by silentwinter** [comment]
В рейде с другими игроками ФПС падает до 30 или ниже, хотя я имею очень хороший ПК. Я думаю, это происходит потому, что надо проверить версии между ElvUI клиентами, но я не уверен.

http://imgur.com/a/HYg66
красный = Плохо

P.S. Я не умею говорить по-русски...

**Comment by Bunny67** [comment]
The screenshot shows that it has posted 4 messages, I do not think that because of this lag

**Comment by silentwinter** [comment]
What could possibly cause the FPS to drop? 

I asked my friends who also have ElvUI and they also have problem with FPS drops on 25 men raid with very good PCs.

**Comment by silentwinter** [comment]
My addons for raiding
-BigWigs
-DBM 
-Grid2
-Doom Cooldown Pulse
-Gearscore
-MSBT
-Skada
-Weakauras 2
-WIM
-ElvUI

**Comment by Bunny67** [comment]
try to comment on this line https://github.com/ElvUI-WotLK/ElvUI/blob/master/ElvUI/core/core.lua#L627 and check

**Comment by Bunny67** [comment]
i in battleground 40 players 60fps

**Comment by silentwinter** [comment]
FPS on BGs are fine. But in 25 men raid environment, it drops to 30.

**Comment by silentwinter** [comment]
Never tried disabling ElvUI because.. I can't play without it anymore.....

**Comment by Bunny67** [comment]
May I suggest disabling it, and check

**Comment by crumdidlyumshis** [comment]
@silentwinter same here with having to have ElvUI. :)

**Comment by Bunny67** [comment]
check

**Comment by crumdidlyumshis** [comment]
Fixed?

**Comment by silentwinter** [comment]
Haven't tried yet.
