### ISSUE TITLE
Nameplate castbar is not shown if unit is targeted after it started casting

### ISSUE THREAD

**Issue by datbunneh** [ElvUI-WotLK/ElvUI#236]
![nameplate_castbar](https://cloud.githubusercontent.com/assets/9550798/18418846/89af47a0-7856-11e6-878d-c906556659fa.jpg)

**Comment by Bunny67** [comment]
This is not correct

**Comment by Alx1502** [comment]
Its because castbar doesn't have start. This will fix it and it will show tradeskill casts too, i don't know if you can put this in this version tho.
Here is the link https://github.com/doadin/Elvui/commit/6462452bc46599f1efb43bff894968cf598b2e6b

**Comment by Bunny67** [comment]
nameplates is not units

**Comment by Alx1502** [comment]
yes i know, wotlk doesn't have nameplate castbars, but i don't know if its possible to take as reference the unitframe castbar. i might be very wrong, its just a thought :D

**Comment by datbunneh** [comment]
@Bunny67 I did not get your point. Just tested it out and it's still bugged.

**Comment by Bunny67** [comment]
I don't know how to fix it

**Comment by datbunneh** [comment]
@Bunny67 Even `UnitCastingInfo("target") cannot help here?

**Comment by Bunny67** [comment]
no
will have to write a new castbar that affect the operation of nameplates

**Comment by magicbunneh** [comment]
@Bunny67 So you figured out how to make it work?

**Comment by Bunny67** [comment]
No
The same error is in the Tidy Plates
