### ISSUE TITLE
Nameplate castbar overlaps nameplate

### ISSUE THREAD

**Issue by datbunneh** [ElvUI-WotLK/ElvUI#237]
It used to be positioned properly but after some update my setting messed up a little bit and it changed.
Maybe it's because of spell name and cast timer is displayed and they are located in a single container with castbar, and this container is attached to nameplate by its middle point vertically (instead of top).
![nameplate_castbar2](https://cloud.githubusercontent.com/assets/9550798/18418886/62612ef6-7857-11e6-8426-6a75576c2993.jpg)

**Comment by crumdidlyumshis** [comment]
Ok I thought I was going crazy but your right it is overlapping.

**Comment by datbunneh** [comment]
Checked without spell name and timer - did not fix anything.

**Comment by Bunny67** [comment]
check

**Comment by datbunneh** [comment]
Not quite there yet:
![nameplate_castbar3](https://cloud.githubusercontent.com/assets/9550798/18419789/ca595628-786b-11e6-820e-acc404051319.jpg)
There used to be space between nameplate, castbar and icon so neither border nor glow overlap. Something like this (here come my lacking editing skills):
![nameplate_castbar4](https://cloud.githubusercontent.com/assets/9550798/18419808/1b1d3cd2-786c-11e6-98c4-9fa2880bcfda.jpg)

**Comment by Bunny67** [comment]
check

**Comment by magicbunneh** [comment]
@Bunny67 Will do after work.

**Comment by datbunneh** [comment]
@Bunny67 Yes, a slider in options appeared, I've set it to 2 and everything is great. Thanks.
