### ISSUE TITLE
Micro Bar Scale

### ISSUE THREAD

**Issue by xdrt** [ElvUI-WotLK/ElvUI#239]
If you set scale in the Micro Bar, after reload/restart it will keep the scale you set but will change position to the left-top corner as if it was 100% scale.
To fix it you need to go the MicroBar Options and click any option in there and it will fix the position until you restart/reload again.

Top - Before reload/restart
Bottom - After reload/restart
![4444](https://cloud.githubusercontent.com/assets/1572696/18438432/40b03e1c-78f9-11e6-9183-6da5a92cf7bd.jpg)

Thanks for all your amazing work!

**Comment by Bunny67** [comment]
update https://github.com/ElvUI-WotLK/ElvUI_Microbar and check

**Comment by xdrt** [comment]
Fixed! Amazing and fast work! Thank you!
