### ISSUE TITLE
Health Animation Speed - Suggestion

### ISSUE THREAD

**Issue by crumdidlyumshis** [ElvUI-WotLK/ElvUI#240]
Could you add the health animation speed slider to the unitframes?

![world of warcraft 9_12_2016 11_03_06 am](https://cloud.githubusercontent.com/assets/7307335/18443243/a1fb7eb8-78d9-11e6-93f8-cf3e8d0a474a.png)

![world of warcraft 9_12_2016 11_03_15 am](https://cloud.githubusercontent.com/assets/7307335/18443242/a1f8db18-78d9-11e6-9152-961504eb9dfd.png)

**Comment by Bunny67** [comment]
It may be added

**Comment by Bunny67** [comment]
check

**Comment by crumdidlyumshis** [comment]
Works! But maybe in decimal form? example: 0.2 (instead of 6 or whatever it is)

**Comment by Bunny67** [comment]
Above this option still think

**Comment by crumdidlyumshis** [comment]
Works! Thank you @Bunny67 and @Loaal ! :)
