### ISSUE TITLE
Bag Tracked Currency not displaying

### ISSUE THREAD

**Issue by Mangos02** [ElvUI-WotLK/ElvUI#244]
when you track a Currency the number of them do not appear in the bag,

![](https://puu.sh/rajVx.png)

**Comment by Loaal** [comment]
Can't reproduce
![123](https://cloud.githubusercontent.com/assets/590348/18494205/7fb61904-7a1d-11e6-80a8-a0aa6eea74fe.PNG)

**Comment by Mangos02** [comment]
Strangely it works on my other char but not on the other.

**Comment by Mangos02** [comment]
Nevermind i fixed it by switching Currency format back and forth.
