### ISSUE TITLE
Time DataText - Options

### ISSUE THREAD

**Issue by crumdidlyumshis** [ElvUI-WotLK/ElvUI#248]
Could there be an option to set format of time like a dropdown?

![wowscrnshot_091416_203900](https://cloud.githubusercontent.com/assets/7307335/18535821/1fde10ea-7abd-11e6-9a01-b30290b3a444.jpg)

![wowscrnshot_091416_205005](https://cloud.githubusercontent.com/assets/7307335/18535805/f4ebcb98-7abc-11e6-9c7a-68613a71b54b.jpg)

Example:

![wowscrnshot_091416_204945](https://cloud.githubusercontent.com/assets/7307335/18535801/f0bb8f22-7abc-11e6-84fe-18ccf8ee9888.jpg)

**Comment by Bunny67** [comment]
While I do not know how to add

**Comment by crumdidlyumshis** [comment]
If you don't know how, that's okay :)

If possible, could the Date be changed to: M / D / Y _not_ D.M.Y ?

**Comment by Bunny67** [comment]
https://github.com/ElvUI-WotLK/ElvUI/commits/test You can check out here, but it can be not added

**Comment by crumdidlyumshis** [comment]
Oh wow! Maybe more work can be done and later added. Not needed right now, but very good work so far!

**Comment by datbunneh** [comment]
@crumdidlyumshis M / D / Y pattern looks totally weird to me...

**Comment by crumdidlyumshis** [comment]
@datbunneh This is what I am talking about: 

![image](https://cloud.githubusercontent.com/assets/7307335/18565301/e7b2452c-7b54-11e6-8c5e-599536396f9a.png)

This is the time format I am most used to. I am from Texas.

Luckily, Bunny67 added 95% of the code needed to show the time and date in the optional format that we can choose. :) https://github.com/ElvUI-WotLK/ElvUI/tree/test

**Comment by Bunny67** [comment]
And where 5%? :(

**Comment by crumdidlyumshis** [comment]
Haha I just assumed you were 95% done! Now it looks like your 100% done :D :+1:  You make magic
