### ISSUE TITLE
Macros and ElvUI stacked

### ISSUE THREAD

**Issue by silentwinter** [ElvUI-WotLK/ElvUI#251]
http://imgur.com/a/9k4hD

On the menu, macros and ElvUI buttons are stacked.

**Comment by Bunny67** [comment]
What addons you have installed

**Comment by silentwinter** [comment]
there is no addon that modifies that menu. Only ElvUI

**Comment by silentwinter** [comment]
Oh, I figured it out. It is because of Addon Control Panel (ACP). 

Fix would be appreciated!

**Comment by Bunny67** [comment]
check

**Comment by crumdidlyumshis** [comment]
Tested and fixed. Close.
