### ISSUE TITLE
Пара небольших нюансов.

### ISSUE THREAD

**Issue by freesay** [ElvUI-WotLK/ElvUI#257]
Не уверен, сюда стоит писать об этом, или в ElvUI_Bunny.
Такой вот вопрос: пропали настройки ремайндера (или я не нашел их). Был чекбокс на включение/отключение напоминалки, а теперь нет его. 
И сразу предложение небольшое: может добавить еще пару настроек к этой штуке, ну, вот например, сместить вниз миникарты с отключением кнопки активации конфига. Примерно вот так:
![wowscrnshot_092116_195814](https://cloud.githubusercontent.com/assets/19500175/18750704/f56e8f5a-80e4-11e6-9f9f-6be4a7601305.jpg)
И еще стоило бы добавить настройку шрифтов. Потому как если в настройках выбрать шрифт и нажать "применить ко всему интерфейсу", то шрифт меняется и на иконках ремайндера, но настроить обводку нельзя. Получаются корявые цифры, как здесь: 
![wowscrnshot_092116_195811](https://cloud.githubusercontent.com/assets/19500175/18750821/6abb9ae6-80e5-11e6-93ba-a4c328e6a340.jpg)

И еще одно предложение: сделай пожалуйста якорь на кнопке сворачивания/разворачивания списка заданий. Чтоб заголовок не смещался в сторону, а привязывался к одному месту:
![wowscrnshot_092116_195811](https://cloud.githubusercontent.com/assets/19500175/18751000/0b7cdce2-80e6-11e6-9bd7-36c810a4d865.jpg)

**Comment by Bunny67** [comment]
1 - 2, думаю вообще вырезать
3 врятли получится изменить позицию, в бою будет таинт, но посмотрю

**Comment by freesay** [comment]
"3 врятли получится изменить позицию, в бою будет таинт, но посмотрю"

Возможно я не верно выразился... Не смещать позицию заголовка, а сделать так, чтоб кнопка сворачивания/разворачивания, не меняла своей позиции. 
Вот скрин, как это работает в данный момент:
![wowscrnshot_092116_195811](https://cloud.githubusercontent.com/assets/19500175/18752379/e38cb306-80ea-11e6-8988-f5f7d17ee0f1.jpg)
А хотелось бы, чтоб кнопка +/- не уезжала со своей позиции. А оставалась там же, где и была при развернутом списке.

**Comment by Bunny67** [comment]
Я так и понял, но обычно фреймы близзард нельзя переместить в бою, да и еще код не смотрел, кажется там просто размер фрейма уменьшается

**Comment by Bunny67** [comment]
Настройки вернул в ауры, с настройками пока беда.

**Comment by Bunny67** [comment]
У заданий не изменить размер, с позицией ремайндера беда, надо писать очень много кода. Обводка ремайндера изменяется в его настройках
