### ISSUE TITLE
Buff / Debuff on Nameplate

### ISSUE THREAD

**Issue by silentwinter** [ElvUI-WotLK/ElvUI#258]
http://imgur.com/a/gV0CZ

Image explains it all. The buff/debuff image extends or squish to absolute nothingness if I modify # of displayed auras.

**Comment by silentwinter** [comment]
http://imgur.com/a/IsXc9

Problem persists. Debuffs squished or stretched..

**Comment by Bunny67** [comment]
Change "Icon Base Height" in config

**Comment by silentwinter** [comment]
Doesn't help. Give me specific value, I will try. But doesn't help as far as I see. Tried every single number.

**Comment by silentwinter** [comment]
nevermind. I figured it out by tweaking some code.

**Comment by crumdidlyumshis** [comment]
@silentwinter Care to share the code/fix?

**Comment by silentwinter** [comment]
Easier way of reproducing:
#of displayed auras : 5
Icon Base Height : 18

This is the only feasible looking debuff-displaying way. Other numbers just won't work at all. It will look like garbage. Something apparently went wrong from the update and addon does not automatically calculate and make debuffs look square.

**Comment by Bunny67** [comment]
The number and size of auras correctly changed
