### ISSUE TITLE
Resistance stats

### ISSUE THREAD

**Issue by mokkoo** [ElvUI-WotLK/ElvUI#259]
Hi

when i'm login everything is fine, but when i check my stats ( press C ) mine resistance stats comes to life and i cant hide this, how can i solve the problem?

Images:
![wowscrnshot_092416_080446](https://cloud.githubusercontent.com/assets/22409186/18806511/61f7b444-822f-11e6-89c7-56c94b17684c.jpg)
![wowscrnshot_092416_080449](https://cloud.githubusercontent.com/assets/22409186/18806509/53e6ae78-822f-11e6-93f5-f2b5ad27c536.jpg)
![wowscrnshot_092416_080452](https://cloud.githubusercontent.com/assets/22409186/18806508/4643346c-822f-11e6-9108-ed32a2af15f8.jpg)

**Comment by Bunny67** [comment]
What you change in characterFrame.lua?

**Comment by Bunny67** [comment]
What GearScore do you use?

**Comment by crumdidlyumshis** [comment]
I have seen this issue posted before: http://forum.warmane.com/showthread.php?p=2730717#post2730717

It definitely has to do with gearscore. It adds "Raw GearCcore" at top.

**Comment by mokkoo** [comment]
i didnt change lua. how to add raw gear score?

**Comment by Loaal** [comment]
Backported version of CharacterFrame have few differences from original Cataclysm version. To fix this problem requires direct changes to GearScore addon.
