### ISSUE TITLE
Level Color

### ISSUE THREAD

**Issue by crumdidlyumshis** [ElvUI-WotLK/ElvUI#262]
Would it be possible to add the same color like minimap?

![wowscrnshot_092516_215445](https://cloud.githubusercontent.com/assets/7307335/18857880/1fa2f8f6-842d-11e6-8556-91d778a9ce6e.jpg)
![wowscrnshot_092516_215454](https://cloud.githubusercontent.com/assets/7307335/18857879/1fa22908-842d-11e6-9f23-e5cfaf6aeef2.jpg)
![wowscrnshot_092516_215459](https://cloud.githubusercontent.com/assets/7307335/18857881/1fa397d4-842d-11e6-8d7a-8f1b260f03f1.jpg)

**Comment by crumdidlyumshis** [comment]
Maybe add same color to name as class?

**Comment by Bunny67** [comment]
Check

**Comment by crumdidlyumshis** [comment]
Awesome! Thank you!
