### ISSUE TITLE
Индикаторы здоровья: Фильтры

### ISSUE THREAD

**Issue by Sdw8** [ElvUI-WotLK/ElvUI#263]
Играю на русскоязычном клиенте, возможно дело в этом. Вот и не работает ни 1 фильтр, ни Army of the death Ghoul ДК, ни змейки ханта, что очень сильно мешает в пвп и особенно на БГ. Можно как-то это пофиксить?

**Comment by Bunny67** [comment]
Можно добавить их вручную, на счет лакализации стандартных подумаю

**Comment by Sdw8** [comment]
А можно поподробнее насчет синтаксиса как их правильно добавить?

**Comment by Bunny67** [comment]
Просто добавляешь имя моба/тотема, с локализацией мобов может быть проблема. С аурами все нормально.

**Comment by Sdw8** [comment]
Хорошо, спасибо. Подумайте насчет локализации)
