### ISSUE TITLE
ChatBar

### ISSUE THREAD

**Issue by Sdw8** [ElvUI-WotLK/ElvUI#265]
![wowscrnshot_092916_002733](https://cloud.githubusercontent.com/assets/14907962/18933157/1334e24a-85dc-11e6-80a5-fe6cb2c10348.jpg)
ChatBar некорректно работает вместе с ElvUI при нажатии на кнопку появляется нужное окно чата но необходимо выделить его мышкой, либо нажать Enter чтобы туда написать.

**Comment by Bunny67** [comment]
Либо я что то не понимаю, но без ElvUI он вообще не пишет, то есть надо сначала нажать Enter а потом кнопку чатбара

**Comment by Bunny67** [comment]
Это проблема аддона, она была исправлена в версии под кату

**Comment by Bunny67** [comment]
Решение этой проблемы только в самом аддоне, если заменить функцию ChatBar_UseChatType (строка133) на https://gist.github.com/Bunny67/c74ce6dcab43259143559eab2cf6b17b

**Comment by Sdw8** [comment]
Спасибо огромное)
