### ISSUE TITLE
Nameplate autorefresh?

### ISSUE THREAD

**Issue by silentwinter** [ElvUI-WotLK/ElvUI#268]
I have noticed this problem since the first time I used this, but why does nameplate doesn't autorefresh?

Once I am not targetting that target, the buffs/debuffs/casting bar doesn't show or gets refreshed.

Is there a way to autorefresh to real time?

**Comment by Apollyonn** [comment]
Mouseover

**Comment by Loaal** [comment]
In WotLK i guess no way to detect new auras only targeting/mousovering . Already detected auras can be updated timers with OnUpdate but will have huge performance impact.

**Comment by silentwinter** [comment]
Is there any way of achieveing this as there are some other nameplate addons that have realtime updates?

**Comment by Bunny67** [comment]
Aura is automatically updated only on hostile players, other methods will not be added in order to avoid bugs
