### ISSUE TITLE
Уровень предметов

### ISSUE THREAD

**Issue by Sdw8** [ElvUI-WotLK/ElvUI#270]
![wowscrnshot_100416_181346](https://cloud.githubusercontent.com/assets/14907962/19080027/6899212a-8a5e-11e6-94e9-43378054c509.jpg)
Из-за того что нельзя настроить местоположение отображения уровня предметов оно перекрывает количество предметов на патронах и стрелах.

**Comment by Bunny67** [comment]
Мне кажется уровень предметов на них не должен быть(снарядах)

**Comment by Sdw8** [comment]
Прошу прощения. Не заметил обновления.

**Comment by Bunny67** [comment]
Я обновил после твоего сообщения
