### ISSUE TITLE
Скины аддонов

### ISSUE THREAD

**Issue by Sdw8** [ElvUI-WotLK/ElvUI#271]
![wowscrnshot_100516_183023](https://cloud.githubusercontent.com/assets/14907962/19119914/f0e11cec-8b29-11e6-8450-c3a1db2b84aa.jpg)
После последних обновлений перестала работать функция Embed settings у аддона ElvUI_AddOnSkins. Пробовал открывать/закрывать аручную Omen и Recount, не помогло.

**Comment by Bunny67** [comment]
Правый клик по > правого чата

**Comment by Sdw8** [comment]
Господи, чем дальше тем больше узнаю нового) Еще раз спасибо)
А если не тяжело может подскажете возможность сместить в чат баре подписи кнопок на правую часть. В следующих версиях это ввели в настройки, а тут нету.

**Comment by Bunny67** [comment]
Хм, не нашел этого в последней версии

**Comment by Bunny67** [comment]
Добавил возможность перемещать текст в настройки ElvUI_AddOnSkins

**Comment by Sdw8** [comment]
Спасибо

**Comment by Sdw8** [comment]
Правда когда в городе количество каналов увеличивается каждый раз нужно менять ее позицию. Вот что бы можно было зафиксировать нижнюю часть и оно увеличивалось вверх а не вниз. Ну это уже наверное я много хочу)

**Comment by Bunny67** [comment]
Не понял, у меня когда каналы добавляются/удаляются текст не меняет позицию

**Comment by Sdw8** [comment]
Ну если увеличивается количество каналов, то панель увеличивается. И так получается что вниз.

**Comment by Sdw8** [comment]
Если чатбар горизонтальный то он растет правую сторону, если вертикальный то вниз.

**Comment by Bunny67** [comment]
Эт я не так прочитал :( Обратный рост не помагает?

С голдой, попробуй поменять стиль в настройках

**Comment by Sdw8** [comment]
Обратный рост помогает но как-то непривычно снизу вверх считать)
А насчет голды вроде бы настраивается формат отображения в сумке только.

**Comment by Sdw8** [comment]
Я понял проблему, когда активна функция показывать монеты оно поверх отображает.
