### ISSUE TITLE
Shapeshift for druids

### ISSUE THREAD

**Issue by Mimzery** [ElvUI-WotLK/ElvUI#273]
Recent issue with the last two versions where you cannot use abilities in shape shift bars for druids, causing you to go into the UIs config menu and rebind the keys manually using Elv UI rather than using default key binds.

Message: ..\AddOns\ElvUI\core\core.lua line 952:
   attempt to call method 'HelloKittyFixCheck' (a nil value)
Debug:
   [C]: HelloKittyFixCheck()
   ElvUI\core\core.lua:952: Initialize()
   ElvUI\init.lua:125:
      ElvUI\init.lua:124

An error that popped up afterward.

**Comment by Bunny67** [comment]
you changed / removed files in the addon?

**Comment by Mimzery** [comment]
Absolutely none at all, it's been happening the last couple of days for me when in bear form, Unsure if i have the older version that it didn't happen on anymore to check whats changed, it'll cast the spells not on the shape shift bar unless i rebind the keys using the Elv UI key bind option.

**Comment by Bunny67** [comment]
The error is also present? After reinstalling

**Comment by Mimzery** [comment]
No, the LUA error that popped up is gone now but the issue is still there with the shape shift bar.

**Comment by Bunny67** [comment]
Check

**Comment by Mimzery** [comment]
Sadly the update did nothing to fix it, I'll upload a video so you can see for yourself what's happening with it, I've not other action bar add ons or any add ons that could be conflicting with it.

**Comment by Bunny67** [comment]
Вы имеете в виду это? [bonusbar:1,nostealth] 8; [bonusbar:1,stealth] 8; [bonusbar:2] 8; [bonusbar:3] 9; [bonusbar:4] 10;

**Comment by Bunny67** [comment]
Check

**Comment by Mimzery** [comment]
This seems to have fixed the issue, I've triple checked it along with every other add on i use to see if it was conflicting at all and found snowfall key press was causing some problems with it for whatever reason but outputted no errors or issues.

Thank you for the help and for the UI/All the work you do.

**Comment by Bunny67** [comment]
Please check last update
