### ISSUE TITLE
Sound Drop-down - Sounds Disappeared 

### ISSUE THREAD

**Issue by crumdidlyumshis** [ElvUI-WotLK/ElvUI#274]
I remember there being many more sounds to choose from.

![wowscrnshot_100616_004625](https://cloud.githubusercontent.com/assets/7307335/19141858/8debabe0-8b5e-11e6-92be-9ee149aab6b0.jpg)
![wowscrnshot_100616_004601](https://cloud.githubusercontent.com/assets/7307335/19141857/8deb8c96-8b5e-11e6-870f-3d12c1ca17fc.jpg)

**Comment by Bunny67** [comment]
No

**Comment by crumdidlyumshis** [comment]
No? Maybe I have an addon conflicting? Or am I crazy? Haha

**Comment by crumdidlyumshis** [comment]
Oh maybe my skada is bugged :/

	media:Register("sound", "Rubber Ducky", [[Sound\Doodad\Goblin_Lottery_Open01.wav]])
	media:Register("sound", "Cartoon FX", [[Sound\Doodad\Goblin_Lottery_Open03.wav]])
	media:Register("sound", "Explosion", [[Sound\Doodad\Hellfire_Raid_FX_Explosion05.wav]])
	media:Register("sound", "Shing!", [[Sound\Doodad\PortcullisActive_Closed.wav]])
	media:Register("sound", "Wham!", [[Sound\Doodad\PVP_Lordaeron_Door_Open.wav]])
	media:Register("sound", "Simon Chime", [[Sound\Doodad\SimonGame_LargeBlueTree.wav]])
	media:Register("sound", "War Drums", [[Sound\Event Sounds\Event_wardrum_ogre.wav]])
	media:Register("sound", "Cheer", [[Sound\Event Sounds\OgreEventCheerUnique.wav]])
	media:Register("sound", "Humm", [[Sound\Spells\SimonGame_Visual_GameStart.wav]])
	media:Register("sound", "Short Circuit", [[Sound\Spells\SimonGame_Visual_BadPress.wav]])
	media:Register("sound", "Fel Portal", [[Sound\Spells\Sunwell_Fel_PortalStand.wav]])
	media:Register("sound", "Fel Nova", [[Sound\Spells\SeepingGaseous_Fel_Nova.wav]])
	media:Register("sound", "You Will Die!", [[Sound\Creature\CThun\CThunYouWillDIe.wav]])

**Comment by crumdidlyumshis** [comment]
Thank you so much @Bunny67 !

Only one little skin bug:  Dropdown Scrollbar

![wowscrnshot_100616_235706](https://cloud.githubusercontent.com/assets/7307335/19179224/c70613d0-8c20-11e6-9748-be2b524ee063.jpg)
