### ISSUE TITLE
Рамки юнитов

### ISSUE THREAD

**Issue by Sdw8** [ElvUI-WotLK/ElvUI#277]
После последнего обновления при уменьшении хп вместе с полосой затирается и все что отображается на плейте. Я не нашел способа вернуть как было. Или это было включено специально?)

**Comment by Bunny67** [comment]
Можно скрин?)

**Comment by Sdw8** [comment]
![wowscrnshot_101116_195655](https://cloud.githubusercontent.com/assets/14907962/19280100/f4c09f5a-8fec-11e6-9716-16d360b56dd6.jpg)
![wowscrnshot_101116_195721](https://cloud.githubusercontent.com/assets/14907962/19280101/f4c59dfc-8fec-11e6-9163-b14fa5cc27a4.jpg)

**Comment by Sdw8** [comment]
Еще бы хотелось бы узнать где можно с вами связаться, чтобы не плодить тут запросы)

**Comment by Bunny67** [comment]
Та лучше тут, тут чекаю считай каждый день. Косяк понял в чем, поправить не смогу(временно нет доступа к компу, до пятницы) Возможно другой человек зальет фикс.

**Comment by Sdw8** [comment]
![wowscrnshot_101116_202432](https://cloud.githubusercontent.com/assets/14907962/19281002/c2ff0b24-8ff0-11e6-885f-5c40b61c046e.jpg)
Вот еще баг. Иногда вместо фрейма пета пишет мой ник) Внизу по центру фрейм.

**Comment by Bunny67** [comment]
После того как слез с пушки?

**Comment by Sdw8** [comment]
Ага)

**Comment by Sdw8** [comment]
Осталось только пофиксить фрейм пета после выхода из пушки.

**Comment by Bunny67** [comment]
Так вроде исправлено, проверь еще раз

**Comment by Sdw8** [comment]
Да, вроде все хорошо. Спасибо.
