### ISSUE TITLE
Error on load

### ISSUE THREAD

**Issue by crumdidlyumshis** [ElvUI-WotLK/ElvUI#278]
Message: Interface\AddOns\ElvUI\libs\oUF\ouf.lua:164: Invalid argument "event" in UpdateAllElements.
Time: 10/12/16 00:05:01
Count: 1
Stack: [C]: ?
[C]: in function `assert'
Interface\AddOns\ElvUI\libs\oUF\ouf.lua:164: in function `UpdateAllElements'
Interface\AddOns\ElvUI_AuraBarsMovers\core.lua:108: in function <Interface\AddOns\ElvUI_AuraBarsMovers\core.lua:57>
[C]: in function `?'
...rface\AddOns\ElvUI\modules\unitframes\unitframes.lua:866: in function `Update'
...rface\AddOns\ElvUI\modules\unitframes\unitframes.lua:403: in function `Update_AllFrames'
...rface\AddOns\ElvUI\modules\unitframes\unitframes.lua:1042: in function `?'
...vUI\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:145: in function <...vUI\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:145>
[string "safecall Dispatcher[1]"]:4: in function <[string "safecall Dispatcher[1]"]:4>
[C]: ?
[string "safecall Dispatcher[1]"]:13: in function `?'
...vUI\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90: in function `Fire'
...face\AddOns\ElvUI\libs\AceEvent-3.0\AceEvent-3.0.lua:120: in function <...face\AddOns\ElvUI\libs\AceEvent-3.0\AceEvent-3.0.lua:119>

Locals:

**Comment by crumdidlyumshis** [comment]
Message: Interface\AddOns\ElvUI\libs\oUF\ouf.lua:164: Invalid argument "event" in UpdateAllElements.
Time: 10/12/16 00:07:17
Count: 1
Stack: [C]: ?
[C]: in function `assert'
Interface\AddOns\ElvUI\libs\oUF\ouf.lua:164: in function `UpdateAllElements'
Interface\AddOns\ElvUI_AuraBarsMovers\core.lua:162: in function <Interface\AddOns\ElvUI_AuraBarsMovers\core.lua:111>
[C]: in function `?'
...rface\AddOns\ElvUI\modules\unitframes\unitframes.lua:866: in function `Update'
...rface\AddOns\ElvUI\modules\unitframes\unitframes.lua:871: in function `CreateAndUpdateUF'
Interface\AddOns\ElvUI_AuraBarsMovers\core.lua:220: in function `?'
...vUI\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:145: in function <...vUI\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:145>
[string "safecall Dispatcher[1]"]:4: in function <[string "safecall Dispatcher[1]"]:4>
[C]: ?
[string "safecall Dispatcher[1]"]:13: in function `?'
...vUI\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90: in function `Fire'
...face\AddOns\ElvUI\libs\AceEvent-3.0\AceEvent-3.0.lua:120: in function <...face\AddOns\ElvUI\libs\AceEvent-3.0\AceEvent-3.0.lua:119>
[C]: in function `CameraOrSelectOrMoveStop'
[string "CAMERAORSELECTORMOVE"]:4: in function <[string "CAMERAORSELECTORMOVE"]:1>

Locals:

**Comment by Bunny67** [comment]
Conflict \ElvUI_AuraBarsMovers

**Comment by Bunny67** [comment]
Close?
