### ISSUE TITLE
Adjusting the Portrait

### ISSUE THREAD

**Issue by silentwinter** [ElvUI-WotLK/ElvUI#280]
http://imgur.com/a/cmNRs

So I got the newly updated Legion character model and the portrait only for human females are not working correctly. Rest of them are working fine.

Is there a way to adjust the portrait.

**Comment by Loaal** [comment]
Have no idea how to fix it properly.
As temporary solution you can replace content of `ElvUI\libs\oUF\elements\portraits.lua`

https://gist.github.com/Loaal/7667134427064561dab56eb8691ed469

**Comment by silentwinter** [comment]
Found a fix for human females. However, problem persists with Undead & Dwarves. Will find a way and post the code.

**Comment by Loaal** [comment]
Your solution have same problem, with a standard set of models this bug appears.

**Comment by silentwinter** [comment]
http://imgur.com/a/kIVE3

Works well for me. Just have problem listed above. (2nd screenshot L Undead head penetrating through the camera and etc)

**Comment by silentwinter** [comment]
As I've said, I am using a different character patch than from Warmane one so, it will not work unless you are using the exact same model patch as I am using...

**Comment by Loaal** [comment]
I did not notice the difference in the names of models.

**Comment by silentwinter** [comment]
It's not the names of the models or paths. It is how function is written. Rather than exactly defining the name of the model (if model ==), I used what was given on elvui (find("string") in name, model) which is well, works for me. 

I didn't see any faults in your codes, but it didn't work, so I did something else and it worked for me. Just throwing it out here.

**Comment by Bunny67** [comment]
Close? Problem solved?

**Comment by silentwinter** [comment]
Yes, free to close.
