### ISSUE TITLE
Aura filters

### ISSUE THREAD

**Issue by Tristan000** [ElvUI-WotLK/ElvUI#284]
There is something wrong with the aurabar filters, the allow whitelisted auras doesn't seem to work.

**Comment by Bunny67** [comment]
Change "Maximum Duration" to 0, so that the filter worked

Google translete :(

**Comment by Tristan000** [comment]
It works now.
One more thing i just noticed, the nameplates filters seems to have problem too, it used to show enemy buffs but now it doesn't.

**Comment by Bunny67** [comment]
Hmm, I have works fine

**Comment by Tristan000** [comment]
Am i doing something wrong? i tried everything and can't get it to work. :(
![534543543](https://cloud.githubusercontent.com/assets/20983405/19447075/8316f9e6-94a4-11e6-9536-95ee5eed7e42.jpg)

**Comment by Tristan000** [comment]
Ok after the update this now works too, thank you!
I'm closing this now.

**Comment by Bunny67** [comment]
Check now
