### ISSUE TITLE
Неймплейты

### ISSUE THREAD

**Issue by Suonu** [ElvUI-WotLK/ElvUI#285]
Можно ли сделать, чтобы имена над неймплейтами были по середине, а не слева как сейчас?

**Comment by Bunny67** [comment]
Можно, но только где будет находится уровень ? :) В елв добавлять не буду, но можно добавить в https://github.com/ElvUI-WotLK/ElvUI_CustomTweaks

**Comment by Bunny67** [comment]
Добавлен твик https://github.com/ElvUI-WotLK/ElvUI_CustomTweaks/commit/d8960a748a19c3433a175d7043ac38da2ab906b9
