### ISSUE TITLE
Панель тотемов

### ISSUE THREAD

**Issue by Sdw8** [ElvUI-WotLK/ElvUI#287]
При выключении панели тотемов (totems) панель остается. Панель тотемов невозможно привести к виду как сделаны остальные панели(черная окантовка и так далее). Возможность менять ориентацию (вертикально-горизонтально). И при маленьком разрешении экрана при разворачивании тотемов оно западает под фрейм. Хотелось бы хотя бы добавить возможност ьменять ориентацию уже не было проблемы с приоритетом фреймов.

**Comment by Bunny67** [comment]
Все что щас есть в настройках тотемов, это максимальное что с ними можно сделать. Для других настроек из надо писать с 0.
Не понял как западает за под фрейм, можно скрин?

**Comment by Sdw8** [comment]
А почему не выключается панель? Галочку снял, но все равно панель остается.

**Comment by Sdw8** [comment]
А насчет приоритета когда нажимаешь на панель тотемов появляется выпадающий список тотемов, и когда оно идет поверх моего фрейма игрока то нельзя нажать на тотем потому что выделяется мой фрейм.

**Comment by Sdw8** [comment]
Еще предлагаю стилизировать замечательный аддон TotemTimers. Добавить его в AddonSkins.

**Comment by Bunny67** [comment]
Исправил возможность отключить их

**Comment by Sdw8** [comment]
Еще у друга наблюдается в последней версии нексовпадени с гкд и вообще кд способностей. Якобы спелл откатилсяно на самом деле еще кд.

**Comment by Bunny67** [comment]
Такого не замечал, нужно воспроизведения бага

**Comment by Sdw8** [comment]
Насчет стилизации аддона TotemTimers в AddonSkins создать отдельную тему?

**Comment by Bunny67** [comment]
Нет, скин уже почти готов, если сегодня успею, залью

**Comment by Sdw8** [comment]
Хорошо спасибо)
