### ISSUE TITLE
нужно портирование

### ISSUE THREAD

**Issue by maryday001** [ElvUI-WotLK/ElvUI#288]
Привет,не могли бы вы портировать 
http://www.tukui.org/addons/index.php?act=view&id=285
для 3.3.5а?

**Comment by Bunny67** [comment]
В смысле поддержку скинов кнопок? Так как этот элв не поддерживает Masque он же ButtonFace на личе вроде. Возможно когда нибудь будет поддержка ButtonFace скинов.

**Comment by maryday001** [comment]
Понятно!спасибо)а можно ли как-нибудь изменить кнопки,раз так нельзя?

**Comment by Bunny67** [comment]
Добавлена поддержка ButtonFacade, по умолчанию отключена.
