### ISSUE TITLE
пара вопросов

### ISSUE THREAD

**Issue by maryday001** [ElvUI-WotLK/ElvUI#289]
[deficit:name]
собственно должно показывать либо имя,если фул хп,либо дефицит хп,соответственно,но у меня чт-то не выходит добиться этого эффекта.

прозрачность рамки юнитов определяется радиусом действия скилла?можно сделать,чтобы для ппалов это была "Длань возмездия",а для хпалов заклинания категории "Правосудие"?

**Comment by Bunny67** [comment]
1 таг по моему не так пишется, смогу глянуть только вечером.
2 да, радиусом. Проверки на спек к сожалению нет, можно сделать только приоритет, тоже глянуть вечером

**Comment by maryday001** [comment]
http://www.tukui.org/forums/topic.php?id=31399
вот тут написано,там еще в комментах вопрос есть такой,ток я не пойму,вроде все так же делаю,но там,судя по комментам опять -таки,версия 7+,если это имеет значение,в любом случае спасибо,буду ждать)

**Comment by Bunny67** [comment]
По идеи должен быть такой таг, но тут его нет :(

**Comment by Bunny67** [comment]
Хм, таг [defict:name] у меня работает.

Добавил Длань возмездия в проверку, проверь. Мне лень делать спек танка :(

**Comment by maryday001** [comment]
проверю-отпишу,спасибо))
а кинешь всю строчку или куда ты таг вообще писал?

**Comment by Bunny67** [comment]
Для проверки закинул в текст здоровья [healthcolor][defict:name]

**Comment by maryday001** [comment]
хм,понятия не имею как и почему,но вся проблема была в букве I,ибо без нее работает,а с ней нет,хотя на форуме,на который я ссылку давал выше,эта буква присутствует в списке)(deficIt)

**Comment by maryday001** [comment]
щас проверю длань)

**Comment by maryday001** [comment]
в общем длань работает,таг тоже,но Правосудие в хпале нет,там талант есть,из-за которого радиус становится больше у Правосудия,может из-за этого?

**Comment by Bunny67** [comment]
Не понял :(

**Comment by Bunny67** [comment]
В хиле надо 40м?

**Comment by maryday001** [comment]
http://db.uawow.com/?spell=53557
вот этот талант,из-за него,может быть,проблема?

**Comment by maryday001** [comment]
40,судя по всему)

**Comment by Bunny67** [comment]
Проблема чуть в другом, Правосудие света не добавляется в проверку, если нет баффа(делая спелл активным), а проверки на наличие баффа не хочется делать.

**Comment by Bunny67** [comment]
Чуть поправил, теперь должен в хиле считать 40м, в дд/танке 30м

**Comment by maryday001** [comment]
все работает,Спасибо)
