### ISSUE TITLE
Skada/Recount

### ISSUE THREAD

**Issue by freesay** [ElvUI-WotLK/ElvUI#290]
Здравствуй. Погляди пожалуйста, в чем проблема скрывается. Настраиваю интерфейс, выставляю в правое окно чата скаду (или рекаунт, не важно), все готово. Но! Если загрузить игру отключив все аддоны, а затем снова перезайти в игру, но с уже включенными аддонами, то окно скады/реканту исчезает. Я так понимаю, что оно укатывается за пределы экрана. Можно сбросить настройки скады, но, если в конфиге элва снова выставить скаду в правое окно чата, скада снова потеряется. Не уверен, понятно ли расписал проблему, но вот никак не вернуть потом на место писькомер.

![wowscrnshot_110216_145912](https://cloud.githubusercontent.com/assets/19500175/19927888/f77e61a6-a10c-11e6-88bf-13db742cb218.jpg)

**Comment by Bunny67** [comment]
Заметил баг только со скадой, если ее поменять на рекаунт то она остается на месте, то есть она остается прикрепленной. Решается перезагрузкой, и она будет по центру экрана. Фикса этой проблемы пока хз.

**Comment by freesay** [comment]
Не совсем понял как решается эта проблема, но у меня даже чиста файлов настроек скады/рекаунта из папки wtf не решало эту проблему. Соответственно с перезапуском игры. Скада наотрез отказалась вернуться в пределы обозримого экрана. Рекаунт вернулся после сброса настроек, пока прилепил его в чат руками, без указания настройки в элве.

**Comment by silentwinter** [comment]
Confirmed. Embed setting does not work anymore.

**Comment by silentwinter** [comment]
Resetted WTF folder, resetted Cache, still doesn't work. Recount/Skada/Omen/whatever you name it, will get stuck somewhere outside of the screen.

**Comment by silentwinter** [comment]
Any fixes on the way? bump

**Comment by Loaal** [comment]
Немогу воспроизвести. Recount/Skada/Omen работают без проблем.
Некоторые аддоны хранят позицию своих фреймов в отдельном файле.
Для сброса позиции достаточно удалить относящиеся к фрейму строки.

[EN]
Can't reproduce. Recount/Skada/Omen all of them works fine for me.
Some of addons store their frame properties in separate file.
For resetting of position you need just remove few lines.

`WTF\Account\AccName\Realm\CharName\layout-local.txt`
![capture](https://cloud.githubusercontent.com/assets/590348/20983269/da21eee4-bccc-11e6-95c3-62a54f228d83.PNG)

**Comment by Bunny67** [comment]
Сбросить позицию рекаунта можно через его настройки, скада за приделы экрана не может уйти
