### ISSUE TITLE
Карта и имена игроков в группе/рейде.

### ISSUE THREAD

**Issue by freesay** [ElvUI-WotLK/ElvUI#291]
Еще одна проблемка - имена игроков в группе/рейде находятся на слое выше карты мира. 
![wowscrnshot_110216_150543](https://cloud.githubusercontent.com/assets/19500175/19928086/fe208eca-a10d-11e6-92e9-2e818c323a7d.jpg)

**Comment by Bunny67** [comment]
Сделай слой для карты TOOLTIP, возможно другие баги вылезут :(

**Comment by freesay** [comment]
Теперь с именами сопартийцев полный порядок. Спасибо.
Вылез, правда иного рода баг, правда уже гораздо менее критичный, с которым я бы и не столкнулся вообще, если бы не решил проверить столь очевидную вещь, как описание квестов в развернутом виде карты мира. Но раз уж баг имеет место быть, то зарепорчу и его, просто для галочки =)
![wowscrnshot_110616_121440](https://cloud.githubusercontent.com/assets/19500175/20036529/8810df12-a41b-11e6-85c0-e47e66ba5fce.jpg)
