### ISSUE TITLE
ElvUI with Platebuffs?

### ISSUE THREAD

**Issue by silentwinter** [ElvUI-WotLK/ElvUI#300]
It seems that ElvUI nameplate doesn't work with PlateBuffs. Could it be possible?

**Comment by silentwinter** [comment]
nvm it works, but not with some specific addon it seemed

**Comment by silentwinter** [comment]
came back from thanksgiving break. It doesn't work anymore. I dont know why

**Comment by Bunny67** [comment]
What is your version of Platebuffs?

**Comment by Bunny67** [comment]
Check in last update
