### ISSUE TITLE
CastBarOverlay

### ISSUE THREAD

**Issue by freesay** [ElvUI-WotLK/ElvUI#302]
Решил глянуть, что это такое. Не пригодилось - выключил. Теперь полосы каста пропали вовсе. Очень жаль, заново отстраивать интерфейс =(

**Comment by Bunny67** [comment]
На сколько помню каст бар можно восстановить поумолчанию

**Comment by freesay** [comment]
Да ничего, я уже отстроился заново =) 
Это уже особый ритуал после экспериметнов.

**Comment by Bunny67** [comment]
Сохраняй профиль в текстовом виде, перед экспериментами :)

**Comment by freesay** [comment]
Спасибо, как-то раньше не обращал внимание на настройки экспорта/импорта. Но штука в том, что настройки кастом твиков, медиа и еще каких-то других мелочей (не помню что именно) не экспортирует.
