### ISSUE TITLE
GearScore

### ISSUE THREAD

**Issue by freesay** [ElvUI-WotLK/ElvUI#303]
Малююююсенький нюанс =) 
![1](https://cloud.githubusercontent.com/assets/19500175/20495871/f44ebcf2-b033-11e6-9a7d-37dfb6a5a8ff.jpg)
![2](https://cloud.githubusercontent.com/assets/19500175/20495873/f4c7bd82-b033-11e6-8692-3422da0c39b6.jpg)

**Comment by Bunny67** [comment]
https://github.com/ElvUI-WotLK/ElvUI_Bunny/commit/01ddad7d5caafad3be1285fa6dd9f9659461f403 Должно было быть исправлено в ElvUI_Bunny, или проблема осталась?

**Comment by freesay** [comment]
Да, оказывается все в норме, просто я давно не обновлялся =)

**Comment by Bunny67** [comment]
В
