### ISSUE TITLE
[Предложение] Безопасный обмен

### ISSUE THREAD

**Issue by freesay** [ElvUI-WotLK/ElvUI#305]
Есть у меня аддон один, называется SS - SafeTrade. Нашел я его, кажется, в репах Kkthnx, но точно не помню, сейчас уже едва ли найду первоисточник. Создан для безопасного обмена вещами/деньгами между игроками. 

Скажу честно - я не особо понимаю как он работает, потому как на кидал не напарывался, все чаще ауком и почтой работаю, но раз в жизни и палка стреляет. Однако, функционалом кой-каким он однозначно обладает. Вывод сей мною сделан исходя из опытного расследования запечатленного на нижепредставленном куске скриншота =) 
![123456](https://cloud.githubusercontent.com/assets/19500175/20700543/f6253786-b61e-11e6-9c24-426d8410edb6.jpg)

Сложно не согласиться с утверждением, мол лохам урок в прок, но все же, мне кажется, подобная функция была бы отличным дополнением к такому крутому аддону как элв. 
Если заинтересует, скажи куда лучше залить архив с этим аддоном?

**Comment by Bunny67** [comment]
Ну в элв добавлять точно не стоит, если только плагин, да аддон же есть, кому надо мб найдет.

**Comment by Sdw8** [comment]
Что-то я не могу найти рабочей версии для 3.3.5а, Можно ссылку?

**Comment by freesay** [comment]
https://cloud.mail.ru/public/8LV1/PgpTwrB7M

**Comment by Sdw8** [comment]
Спасибо

**Comment by Bunny67** [comment]
Добавляться в ElvUI не будет. Если нужен скин аддона, создайте запрос тут https://github.com/ElvUI-WotLK/ElvUI_AddOnSkins
