### ISSUE TITLE
[Предложение] Цвет ключевых слов в чате

### ISSUE THREAD

**Issue by freesay** [ElvUI-WotLK/ElvUI#310]
Здравствуй. Стал пользоваться ключевыми словами, полезная штука, оказывается. Но столкнулся с неприятной особенностью - цвет ключевых слов плохо читается на фоне элвовского чата. Особенно короткие аббревиатуры, типа, дс, рс, ик, мк и т.д. 
Можно ли прикрутить настройку цвета для ключевых слов? 
Или еще лучше, добавить дополнительную строку, для которой можно было бы назначить свой цвет. Чтоб в чате выделялись разными цветами разные типы ключевых слов. Вот как я это вижу:
![aa24bde2-ba75-11e6-852f-e6f9f43ae505](https://cloud.githubusercontent.com/assets/19500175/20870823/79943caa-ba9f-11e6-8947-c3569caa7eae.jpg)
Будет очень круто, если таких полос будет несколько.

**Comment by Bunny67** [comment]
Сложно в реализации, лучше использовать аддон предназначенный для поиска слов.
Вроде для что то наподобие https://mods.curse.com/addons/wow/broker-chatalerts/442849
