### ISSUE TITLE
[Баг] Информационные панели

### ISSUE THREAD

**Issue by freesay** [ElvUI-WotLK/ElvUI#311]
Привет. В поисках свободного пространства, стал избавляться от лишних элементов интерфейса. Скрыв две боковые инфо панели, активировал одну центральную, под экшнбаром1, но выглядит она, мягко говоря, странновато. Никакие настройки бара не оказывают влияния на "выравнивание" панели в лучшую сторону. Пробовал настраивать отступ кнопок, их размер, фон, отступ фона - ничего не помогает. Есть ли возможность подправить этот нюанс? Превосходно было бы иметь возможность настраивать отступ этой панели от экшнбара. Или возможность перемещать её, как отдельный элемент, независимо от бара. 
Сейчас это выглядит вот так: 
![1](https://cloud.githubusercontent.com/assets/19500175/20872048/8ce0f55c-baac-11e6-83a3-18af74f463e4.jpg)
![2](https://cloud.githubusercontent.com/assets/19500175/20872049/8ce6a204-baac-11e6-932c-dfbc93ac5a5b.jpg)
Хотелось бы, что-нибудь близкое к такому:
![3](https://cloud.githubusercontent.com/assets/19500175/20872063/a149bf42-baac-11e6-9086-7179b12dbdb9.jpg)

**Comment by Bunny67** [comment]
Был удален из ElvUI_Enhanced, используй https://github.com/ElvUI-WotLK/ElvUI_DTBars
