### ISSUE TITLE
Concider backporting TellMeWhen

### ISSUE THREAD

**Issue by datbunneh** [ElvUI-WotLK/ElvUI#312]
I know it's a bit insane to propose it here, but TellMeWhen is extremely useful and powerful addon nowadays and it used to be almost total crap back in WoTLK. Please have a look at it.

**Comment by silentwinter** [comment]
https://wow.curseforge.com/projects/tellmewhen/files/422006

There ya go buddy.

**Comment by datbunneh** [comment]
@silentwinter, have you read the description?

**Comment by silentwinter** [comment]
Ah you meant backport.

AFAIK, TMW didn't really go through much changed from 3.3.5 version to the current Legion version. The only difference might be the GUI itself and added convenience. 

A great alternative option is WeakAura backported by someone else that you can find it on Warmane Forum. It is Cataclysm version, very clean looking and nice. Not really easy to configure like TMW, however. 

Again, TMW didn't really go through a lot of changes; just how GUI looks and that's really about it. Definitely not the easiest thing to backport also, I think.. /shrug/

**Comment by datbunneh** [comment]
@silentwinter, I've actually been using TellMeWhen throughout late Cataclysm and whole Pandaria and I must say that it has grown dramatically since WoTLK. It has much more options, conditions, notifications, sorting and other look&feel staff, not just options. It's like 10 times bigger than it was.

**Comment by zelda1220** [comment]
On my mobile, excuse typos. 

I used in on WoD and I couldnt really see any difference with wotlk version. It just looks a little bit more fancy, but wotlk does the exact same job altho some of the functions like "on cd" doesnt work perfectly with some classes. 

If you want that new tmw feels, go ahead and give weakaura a try. Thats what u r looking for. Abit more complicated and requires more time tho.

**Comment by zelda1220** [comment]
Oh this is silentwinter. Didnt know i had two accounts opps.

**Comment by datbunneh** [comment]
@silentwinter, I guess you've used a couple of icons and only basic features, that's why you don't see any difference.

**Comment by silentwinter** [comment]
Kk, you are so good. 

Good luck finding somebody else to backport that walls of china.

**Comment by Bunny67** [comment]
https://github.com/ElvUI-WotLK/ElvUI#can-you-backport-addonname-to-wotlk
