### ISSUE TITLE
Масштабирование карты

### ISSUE THREAD

**Issue by Sdw8** [ElvUI-WotLK/ElvUI#313]
После вступления в бой при открытии карты она неправильно масштабируется. Приходится ее уменьшать, потом увеличивать, либо переоткрывать после завершения боя. Когда выключены цели заданий на карте масштабируется хорошо.
![wowscrnshot_121616_131048](https://cloud.githubusercontent.com/assets/14907962/21260807/c5a5722e-c398-11e6-8234-9c63648211ac.jpg)
![wowscrnshot_121616_131103](https://cloud.githubusercontent.com/assets/14907962/21260808/c5a64fa0-c398-11e6-967a-823b71e3945a.jpg)
![wowscrnshot_121616_131106](https://cloud.githubusercontent.com/assets/14907962/21260806/c5a56f54-c398-11e6-9d8e-e438e48e4498.jpg)

**Comment by Bunny67** [comment]
У меня воспроизвести не получилось. Открывал как в бою так не в боя

**Comment by Sdw8** [comment]
А может быть из-за конфликта аддонов? Возможно дело в картографе?

**Comment by Bunny67** [comment]
Попробуй только с ElvUI

**Comment by Sdw8** [comment]
Да. Дело в картографе. Но я не знаю что мне выбрать вместо него. Так как бегать вслепую не очень приятно.

**Comment by Bunny67** [comment]
Можно отключить масштабирование карты в ElvUI

**Comment by Sdw8** [comment]
Спасибо
