### ISSUE TITLE
Безмолвие

### ISSUE THREAD

**Issue by Sdw8** [ElvUI-WotLK/ElvUI#314]
Когда на меня использую безмолвие, то раньше на панелях команд все затемнялось и было видно сколько осталось времени то возможности кастовать. Теперь же ничего не происходит. Просто при нажатии на спелл, он не кастуется и все. Возможно дело в том что я давно не обновлял и теперь нужно чистить настройки и заново настраивать аддон?

**Comment by Bunny67** [comment]
Видно стоял другой аддон, у этого такого функционала нет.

**Comment by Bunny67** [comment]
Такого функционала в аддоне не было, возможно у тебя стоял другой аддон

**Comment by freesay** [comment]
Вероятно, дело в том, что ты что ты путаешь типы прерывания каста. При получении удушения, не было таймеров на панелях. Не было раньше, нет и сейчас. При установке модуля с плагинами для элва можно только сделать отображение иконки удушения. А вот при перекрытии школы магии показывается таймер на всех скиллах той школы, каст заклинания которой был прерван. 
Вот скрин удушения полученного в каст:
![wowscrnshot_121616_180730](https://cloud.githubusercontent.com/assets/19500175/21267497/a9930eb6-c3bb-11e6-9a94-b9188d729b77.jpg)
А вот заморозка разума (читай - перекрытие школы магии при попадании в каст):
![wowscrnshot_121616_180741](https://cloud.githubusercontent.com/assets/19500175/21267514/bd57619a-c3bb-11e6-9e6d-61932542df74.jpg)
Но я допускаю, что эти таймеры на скиллах показываются из-за модуля Bunny для элва. Признаться, я понятия не имею есть ли такие же таймеры в дефолтном интерфейсе, я на нем не играл никогда.

**Comment by freesay** [comment]
Ааа, я не внимательно прочитал твое сообщение. Ты говоришь про безмолвие, а я думаю про удушение. Вот олух. 
Быть может таймер не показывается, потому что не был сбит каст. Если просто попасть под "безмолвие", то никаких таймеров не будет. А если безмолвием был сбит каст - то будут таймеры на скилай школы, каст которой был сбит.

**Comment by Sdw8** [comment]
Тогда такой вопрос у друга есть иконка потери контроля, а у меня нету. Хотя я ему скидывал аддон и у него копия моего. В чем может быть дело?
![rrfqzqpic5y](https://cloud.githubusercontent.com/assets/14907962/21268577/776ced76-c3c0-11e6-8162-c9a1ae112219.jpg)
![ekj5gqm_xaa](https://cloud.githubusercontent.com/assets/14907962/21268578/7770b014-c3c0-11e6-8260-e59f989c1a8a.jpg)

**Comment by Bunny67** [comment]
Иконка потери контроля в https://github.com/ElvUI-WotLK/ElvUI_Bunny

**Comment by Sdw8** [comment]
А Bunny обновляется так же как и основной?

**Comment by freesay** [comment]
Будут идеи - будут и обновления, если они нужны. Все работает и так, что в нем обновлять?

**Comment by Sdw8** [comment]
Я сейчас проверил и у друга нету Bunny, но иконка потери контроля же есть.

**Comment by freesay** [comment]
Внимательней смотри. Если у него есть иконка потери контроля, значит есть Bunny. Смею предположить, что у него может быть какой-нибудь другой аддон со схожим функционалом, который анонсит потерю контроля, и элв его подхватил. Я честное слово, не знаю возможно ли такое вообще. Посмотри как у него выглядит окно персонажа, если так как на скриншоте, то Bunny есть однозначно. 
![1](https://cloud.githubusercontent.com/assets/19500175/21287558/4f2ebca8-c47f-11e6-8e95-4b673f2d6bb0.jpg)

**Comment by Sdw8** [comment]
У меня с Bunny выглядит так:
![wowscrnshot_121716_235512](https://cloud.githubusercontent.com/assets/14907962/21289682/4548c00a-c4b4-11e6-99c7-20d1cee0eea0.jpg)
Хотя у друга реально как у тебя на скрине. А как это включить или отключить?

**Comment by freesay** [comment]
Гляди здесь:
![wowscrnshot_121816_085119](https://cloud.githubusercontent.com/assets/19500175/21291840/64255c68-c4ff-11e6-8039-fa3cdf0c7479.jpg)

Если иконка так и не появилась, то, мне кажется, куда проще вычистить кеш, втф и заново отстроить интерфейс.

**Comment by Sdw8** [comment]
Нашел галку. Но....
![wowscrnshot_121816_121254](https://cloud.githubusercontent.com/assets/14907962/21292563/6bf88200-c51b-11e6-9a59-3b3e3c4b8bdd.jpg)
![wowscrnshot_121816_121257](https://cloud.githubusercontent.com/assets/14907962/21292562/6bf6244c-c51b-11e6-8103-76352ca383c2.jpg)
Как будто нету модельки текстуры.

**Comment by Bunny67** [comment]
Уже поправил, обнови ElvUI_Bunny

**Comment by Sdw8** [comment]
Спасибо. Помогло. 
Еще вот сделал скрин с безмолвием. Но есть проблема. Только на скрине отображается иконка потери контроля. А когда я делал скрин этого не было. И просто заклинания не кастовались. Что за бред?)
![wowscrnshot_121816_125800](https://cloud.githubusercontent.com/assets/14907962/21292807/c753d676-c521-11e6-8638-5a1e5ccef9e9.jpg)

**Comment by Bunny67** [comment]
test

**Comment by Bunny67** [comment]
test

**Comment by Bunny67** [comment]
С иконкой такого не возможно, с картой похоже баг близзарда, если ест возможность проверь без аддонов

**Comment by Sdw8** [comment]
Баг с картой может быть раз в день, а то и реже. Очень сложно его проверить.
После перезахода с иконкой все норм. Только не понятно можно ли размер иконки уменьшить?
А еще интересно что такое Interrupttracker и почему он отключен по умолчанию. Отслеживает прерывания для пвп?
