### ISSUE TITLE
Миникарта

### ISSUE THREAD

**Issue by Sdw8** [ElvUI-WotLK/ElvUI#316]
Хороший аддон для мага MageNuggets не помещается в панельке на миникарте, как мне быть?
![wowscrnshot_121916_200743](https://cloud.githubusercontent.com/assets/14907962/21321724/20915a96-c627-11e6-8697-1985844ea8ca.jpg)
Или может скин для аддона сделать? В основном использую его ради удобного использования порталов.

**Comment by Bunny67** [comment]
![wowscrnshot_122016_170619](https://cloud.githubusercontent.com/assets/5816685/21353375/bee7c478-c6d6-11e6-80b7-2dba79275a8d.jpg)
У меня добавляется, возможно из за другого аддона косяк. По поводу скина создай тут https://github.com/ElvUI-WotLK/ElvUI_AddOnSkins запрос, что бы не забыть, к выходным мб сделаю

**Comment by Sdw8** [comment]
Оно добавляется. Я про то что значок ящика аддона Atlasloot ушел в сторону между иконками. Я так понимаю не расчитано на количество иконок больше 7.

**Comment by Bunny67** [comment]
Рассчитано, последняя иконка с буквой "Ф" что за аддон?

**Comment by Sdw8** [comment]
https://wow.curseforge.com/projects/phoenixstyle
