### ISSUE TITLE
Sometimes when I click the actionbar abilities doesn't work

### ISSUE THREAD

**Issue by nadszeg** [ElvUI-WotLK/ElvUI#317]
Hi! 
Sometimes after I played some, i cannot click any of the skills I placed on the action bar, or any part of the UI so I have to /reload. Why is this happening? Also when I go to stealth, sometimes the UI thinks the actionbar is the non-stealth actionbar and uses the spells from there, so I can't use spells like Ambush...

**Comment by Unknownd0000** [comment]
I have similar problem, just the clicking part works but not the keybind, it usually happens on classes that change stance/forms.Your binds are actually the spells on default actionbar while u see the form/stance u are currently in, when u press a keybind it turns u back to normal form and actionbar, temporary fix is to keybind again w/e button on new form/stance keybind but sometimes on crash/opening the game again u need to rebind it again.

**Comment by Unknownd0000** [comment]
This seems to happen when u have SnowfallKeyPress enabled, resetting the addon SnowfallKeyPress helps, but same on game restart u need to do it again, also now elvui have the function of SnowfallKeyPress integrated with its action bars by key down option in action bars so u don't need SnowfallKeyPress addon anymore right?

**Comment by Bunny67** [comment]
yes
