### ISSUE TITLE
MageNuggets

### ISSUE THREAD

**Issue by Sdw8** [ElvUI-WotLK/ElvUI#319]
Понимаю что вопрос не в тему, но больше не у кого спросить.
Почему может случаться: когда пропадает бафф Brain freeze (Заморозка мозгов) остается отслеживание кулдауна аддоном?
![wowscrnshot_122216_131315](https://cloud.githubusercontent.com/assets/14907962/21423583/daef0f72-c84e-11e6-80d6-426fb49e55ed.jpg)
![wowscrnshot_122216_131318](https://cloud.githubusercontent.com/assets/14907962/21423584/daf05d32-c84e-11e6-85c4-bc669a9d2d93.jpg)
Остальное отслеживается вроде бы нормально. Да и полоска почему-то красная. Пробовал добиться через настройки и сброс кэша но не помогло.

**Comment by Bunny67** [comment]
По коду она не должна исчезать, видимо так и задумано
