### ISSUE TITLE
WIM Skin

### ISSUE THREAD

**Issue by Delmalea** [ElvUI-WotLK/ElvUI#320]
Планируется ли создание скина для данного аддона?
Скачала на просторах интернета левый скин под ElvUI, но он не совсем устраивает в эстетическом плане; иконки в окне чата очень маленькие и в ужасном качестве, про окно с настройками, которое портит всеобщую картину я вообще молчу. :)

![wowscrnshot_122416_052452](https://cloud.githubusercontent.com/assets/24690509/21464776/5554d0a0-c956-11e6-870e-8f1dd11b7f42.jpg)

**Comment by Bunny67** [comment]
Лучше чем есть врядтли что то получится
