### ISSUE TITLE
Просмотр банка из меню сумки

### ISSUE THREAD

**Issue by Sdw8** [ElvUI-WotLK/ElvUI#323]
В последних ElvUI был реализован просмотр банка из меню сумки как в аддоне Bagnon. Здесь запоминание количества предметов из банка есть, а можно ли сделать просмотр всего банка когда нет к нему доступа?

**Comment by Bunny67** [comment]
WoW API не позволяет просматривать банк, не открывая его. В багноне возможно кеширование предметов банка, для просмотра их, но не взаимодействие с ними. Как по мне не нужная функция. В елв добавляться не будет, возможно в плагин какой нибудь.

**Comment by Sdw8** [comment]
Ведь в елве в сумке при наведении возможно отобразить количество предметов в банке если они есть. Я думал они кешируются.
