### ISSUE TITLE
OuF Target Name Placement

### ISSUE THREAD

**Issue by Zanhast** [ElvUI-WotLK/ElvUI#324]
When I want to target someone the name appears to the left of the bar while I configured it to appear in the center.This appear when i target a friendly or harmful NPC,but when i target a player there is no bug.

![harmful](https://cloud.githubusercontent.com/assets/18658154/21767264/5e52b1d4-d673-11e6-8ebb-ece9dc9375b7.jpg)
![friendly](https://cloud.githubusercontent.com/assets/18658154/21767266/607397f8-d673-11e6-87c5-1f32e4373165.jpg)
![options](https://cloud.githubusercontent.com/assets/18658154/21767268/61b10240-d673-11e6-80ca-6c19722334be.jpg)

**Comment by Apollyonn** [comment]
Go at Unitframes > Target and untick "Text Toggle On NPC"
