### ISSUE TITLE
Окно заданий

### ISSUE THREAD

**Issue by Sdw8** [ElvUI-WotLK/ElvUI#326]
Периодически багается и затемняется окно,
![wowscrnshot_011517_170439](https://cloud.githubusercontent.com/assets/14907962/21963086/ea0308de-db44-11e6-83c2-174e9dd5b510.jpg)

**Comment by Loaal** [comment]
1. Пропиши /fstack
2. Наведи на затемнение
3. Сделай скрин
![capture](https://cloud.githubusercontent.com/assets/590348/22017108/f1c563a2-dcb9-11e6-8b27-a10347af1d32.PNG)

**Comment by Sdw8** [comment]
Возможно ли что этот баг был пофикшен [тут](https://github.com/ElvUI-WotLK/ElvUI/issues/306)?

**Comment by Loaal** [comment]
Маловероятно, там только фикс уровня кнопок.

**Comment by Sdw8** [comment]
Ну он очень редкий. Он очень часто появляется в рейдах, а во время прокачки его вообще нету. Думаю что дело в рейд фрейме. Пока что проверить не могу.

**Comment by Sdw8** [comment]
![wowscrnshot_020517_142457](https://cloud.githubusercontent.com/assets/14907962/22625752/eb76e5d0-ebae-11e6-9810-9560713144cd.jpg)
