### ISSUE TITLE
Отображение заданий на карте

### ISSUE THREAD

**Issue by Sdw8** [ElvUI-WotLK/ElvUI#327]
Проверил что все-таки при отключении елва задания не багаются, а при включении пока не возьмешь или сдашь любой квест не отображаются задания.
![wowscrnshot_012017_230019](https://cloud.githubusercontent.com/assets/14907962/22163863/ab026f9c-df65-11e6-99e7-8d0b283d873c.jpg)

**Comment by Loaal** [comment]
Используя набор аддонов предоставленный тобой (ElvUI-WotLK/ElvUI_MinimapButtons#3) не смог поймать данный баг.
Скорее всего проблема в Cartographer. Согласно страницам проекта на WowAce и WowInterface последние обновление было для 3.2. В патче 3.3 были изменения карты, в следствии чего можно предположить, что это недоработка модифицированной версии.
Для решения нужен способ воспроизведения этого бага.

**Comment by Sdw8** [comment]
Думаю не столь важно это фиксить. Проблемы бы не было если бы был аналог Cartographer под 3.3.
