### ISSUE TITLE
Перезарядка предмета

### ISSUE THREAD

**Issue by Sdw8** [ElvUI-WotLK/ElvUI#328]
Возможно произошел какой-то сбой и теперь пишет кулдаун 50 дней. Перезаход не помогает.
![wowscrnshot_012117_161524](https://cloud.githubusercontent.com/assets/14907962/22174691/7c5170d6-dff5-11e6-9584-2f50a68b2c14.jpg)

**Comment by Loaal** [comment]
http://imgur.com/ogGgx
https://eu.battle.net/forums/en/wow/topic/7390679012
Близовский баг, до патча 6.0.3 присутствовал.
