### ISSUE TITLE
Reminder Buttons?

### ISSUE THREAD

**Issue by Kralomax** [ElvUI-WotLK/ElvUI#329]
When un-ticking the "enable" minimap button to remove it, the "reminder icons" remain in the background. Assuming these are "reminder buttons/icons", can an option be made to disable this feature?
[<a href="http://s1271.photobucket.com/user/Kralomax/media/elvui_zpsgscgnmf0.jpg.html" target="_blank"><img src="http://i1271.photobucket.com/albums/jj622/Kralomax/elvui_zpsgscgnmf0.jpg" border="0" alt=" photo elvui_zpsgscgnmf0.jpg"/></a>](url)

**Comment by Bunny67** [comment]
![wowscrnshot_012317_223543](https://cloud.githubusercontent.com/assets/5816685/22219606/7ba849b6-e1bc-11e6-8495-cdb2ff395f8c.jpg)

**Comment by Kralomax** [comment]
Thank you! I looked for hours trying to figure that out. :)
