### ISSUE TITLE
Auctioneer

### ISSUE THREAD

**Issue by Kralomax** [ElvUI-WotLK/ElvUI#331]
I have tried different versions of auctioneer and still get this error dealing with the skin.
Date: 2017-01-25 04:45:48
ID: 1
Error occured in: Global
Count: 1
Message: ...AddOns\ElvUI\modules\skins\blizzard\auctionhouse.lua line 195:
   attempt to index field '?' (a nil value)
Debug:
   (tail call): ?
   (tail call): ?
   ...AddOns\ElvUI\modules\skins\blizzard\auctionhouse.lua:195:
      ...AddOns\ElvUI\modules\skins\blizzard\auctionhouse.lua:4
   [string "safecall Dispatcher[1]"]:4:
      [string "safecall Dispatcher[1]"]:4
   [C]: ?
   [string "safecall Dispatcher[1]"]:13: ?()
   ...lock\Lib\CallbackHandler-1.0\CallbackHandler-1.0.lua:92: Fire()
   ElvUI\modules\skins\skins.lua:492: ?()
   ...er4\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:147:
      ...er4\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:147
   [string "safecall Dispatcher[2]"]:4:
      [string "safecall Dispatcher[2]"]:4
   [C]: ?
   [string "safecall Dispatcher[2]"]:13: ?()
   ...er4\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:92: Fire()
   ...AddOns\Bartender4\libs\AceEvent-3.0\AceEvent-3.0.lua:120:
      ...AddOns\Bartender4\libs\AceEvent-3.0\AceEvent-3.0.lua:119
   [C]: ?
   [C]: LoadAddOn()
   ..\FrameXML\UIParent.lua:235: UIParentLoadAddOn()
   ..\FrameXML\UIParent.lua:246: AuctionFrame_LoadUI()
   ..\FrameXML\UIParent.lua:943:
      ..\FrameXML\UIParent.lua:454
AddOns:
  Swatter, v5.8.4723 (CreepyKangaroo)
  Atlas, v1.17.0
  AtlasBattlegrounds, v1.17.0
  AtlasDungeonLocs, v1.17.0
  AtlasOutdoorRaids, v1.17.0
  AtlasTransportation, v1.17.0
  AtlasLoot, vv5.11.04
  AtlasLootFu, vv5.11.04
  AucAdvanced, v5.8.4723 (CreepyKangaroo)
  AucFilterBasic, v5.8.4723 (CreepyKangaroo)
  AucFilterOutlier, v5.8.4723.2531
  AucMatchUndercut, v5.8.4723.2531
  AucStatHistogram, v5.8.4723 (CreepyKangaroo)
  AucStatiLevel, v5.8.4723 (CreepyKangaroo)
  AucStatPurchased, v5.8.4723 (CreepyKangaroo)
  AucStatSales, v5.8.4723.2842
  AucStatSimple, v5.8.4723 (CreepyKangaroo)
  AucStatStdDev, v5.8.4723 (CreepyKangaroo)
  AucStatWOWEcon, v5.8.4723.2530
  AucUtilAHWindowControl, v5.8.4723.3311
  AucUtilAppraiser, v5.8.4723.2530
  AucUtilAskPrice, v5.8.4723.3175
  AucUtilAutoMagic, v5.8.4723.3142
  AucUtilCompactUI, v5.8.4723.2530
  AucUtilEasyBuyout, v5.8.4723.3583
  AucUtilFixAH, v5.8.4723 (CreepyKangaroo)
  AucUtilGlypher, v5.8.4723.2545
  AucUtilItemSuggest, v5.8.4723.3108
  AucUtilPriceLevel, v5.8.4723.2545
  AucUtilScanButton, v5.8.4723.2530
  AucUtilScanFinish, v5.8.4723.3576
  AucUtilScanProgress, v5.8.4723.2530
  AucUtilScanStart, v5.8.4723.2530
  AucUtilSearchUI, v5.8.4723.3655
  AucUtilSimpleAuction, v5.8.4723.4546
  AucUtilVendMarkup, v5.8.4723.2530
  AutoBar, vv3.2.0.798
  AutoRepair, v
  Bartender4, v4.4.2-12-g94f3b58
  BeanCounter, v5.8.4723 (CreepyKangaroo)
  BrokerCurrency, v3.2.0.92
  BrokerDurabilityInfo, v1.1
  BrokerLocation, v
  BrokeruClock, v3.3.6
  Carbonite, v3.34
  CarboniteTransfer, v1.01
  ChocolateBar, vv2.0.2
  Critline, v3.0.2
  Decursive, v2.5.1-4-g77a9e9a
  ElvUI, v5.28
  ElvUIAddOnSkins, v1.01
  ExplorerCoords, v1.21
  FishingBuddy, v0.9.8p1
  GatherMate, vv.1.25
  HandyNotes, v1.1.5
  Informant, v5.8.4723 (CreepyKangaroo)
  LevelRange, v3.3
  LightHeaded, v310
  Mapster, v1.3.9
  MikScrollingBattleText, v5.4.78
  Omen, v3.0.9
  ParanoiaEPA, v	1.12.1
  PawnRU, v1.3.12
  picoDPS, v3.1.0.7
  picoFriends, v3.3.0.5
  picoGuild, v3.1.0.6
  Postal, v3.4.0
  PowerAuras, v3.0.0S
  SDDuelDecline, vv3.3.7
  SellOMatic, vv1.2.8a
  Skada, vr301
  SkadaAbsorbs, v1.0
  SkadaCC, v1.0
  SkadaDamage, v1.0
  SkadaDamageTaken, v1.0
  SkadaDeaths, v1.0
  SkadaDebuffs, v1.0
  SkadaDispels, v1.0
  SkadaEnemies, v1.0
  SkadaFailbot, v1.0
  SkadaHealing, v1.0
  SkadaPower, v1.0
  SkadaThreat, v1.0
  SmartBuff, v3.3e
  Stubby, v5.8.4723 (CreepyKangaroo)
  TipTac, v10.05.01
  TipTacItemRef, v10.02.27
  TipTacTalents, v10.02.27
  TomTom, vwowi:revision
  ZoneLevelInfo, v1.1
  BlizRuntimeLib_enUS v3.3.5.30300 <wotlk.wow-mania.com>
  (ck=a1d)

**Comment by Loaal** [comment]
Seems there's no more errors.

**Comment by Kralomax** [comment]
You my friend are a genius! Thank you for all your hard work. /Salute!!
