### ISSUE TITLE
Buff reminder bug

### ISSUE THREAD

**Issue by Tristan000** [ElvUI-WotLK/ElvUI#335]
There is a problem with buffs with no duration such as Mana Spring Totem. As you can see in the screenshot the buff stays dark.
![wowscrnshot_013117_044017](https://cloud.githubusercontent.com/assets/20983405/22459568/d57a9a6e-e7a9-11e6-922b-911dd5b3907f.jpg)

**Comment by Loaal** [comment]
_It's not a bug, it's a feature._
It works only with Mana Spring **rank 8**.
https://github.com/ElvUI-WotLK/ElvUI/blob/master/ElvUI/modules/misc/raidBuffReminder.lua#L80
http://wotlk.openwow.com/spell=58777

Each rank has it's own spell id.
http://wotlk.openwow.com/?search=Mana+Spring+Totem#spells

Other buffs have same problem.

Summoning @Bunny67
