### ISSUE TITLE
Add support for Cheese (Cataclysm Proc Visuals)

### ISSUE THREAD

**Issue by tripleslash** [ElvUI-WotLK/ElvUI#336]
Right now ElvUI's action bar is incompatible with Cheese, an addon which adds proc visuals from cataclysm to WotLK. It would be nice if support for this was added.

**Comment by Bunny67** [comment]
Added, please test

**Comment by tripleslash** [comment]
Amazing, that was fast. It seems to work perfectly so far, only if the ability is bound to a macro with `#showtooltip` then it doesn't seem to work, other than that everything is fine!

Thank you!

**Comment by Bunny67** [comment]
Can you take a screenshot?

**Comment by tripleslash** [comment]
http://imgur.com/xaEUsLo

I have a Howling Blast proc here, but the HB ability on my action bar is not highlighted when I put it into a macro like that

**Comment by Bunny67** [comment]
It's problem addon, I can't solve it.

**Comment by Bunny67** [comment]
Update, check

**Comment by tripleslash** [comment]
Macro abilities are not showing up in new commit either, its still working though for normal abilities.

**Comment by Bunny67** [comment]
![wowscrnshot_013117_200554](https://cloud.githubusercontent.com/assets/5816685/22475707/dc3fe646-e7f0-11e6-9a9c-8595a1ca3e96.jpg)
sorry my paint :D

**Comment by tripleslash** [comment]
Not working for me, try with this macro

    #showtooltip Howling Blast
    /startattack
    /cast Howling Blast

**Comment by Bunny67** [comment]
![wowscrnshot_013117_201817](https://cloud.githubusercontent.com/assets/5816685/22476187/7de2f2d0-e7f2-11e6-9f78-b2cf4f543e9b.jpg)

It's weird because I'm working on the English client, too. Google translete :(

**Comment by Bunny67** [comment]
Strange, I don't have to work anymore :(

**Comment by Bunny67** [comment]
You need to change the macros in the addon the following: https://gist.github.com/Bunny67/274c9f3a7507960d0d76169cd55ff232/revisions

**Comment by tripleslash** [comment]
Ah, awesome thank you!

**Comment by Bunny67** [comment]
https://gist.github.com/Bunny67/274c9f3a7507960d0d76169cd55ff232/revisions

**Comment by silentwinter** [comment]
http://i.imgur.com/YOMqXXL.jpg

Problem persists.

**Comment by Bunny67** [comment]
Use https://github.com/ElvUI-WotLK/ElvUI_Cheese
