### ISSUE TITLE
3 questions, 1 issue

### ISSUE THREAD

**Issue by nadszeg** [ElvUI-WotLK/ElvUI#338]
Hi! :) The addon is awesome so far, guys! I have 3 questions. Here's my UI: http://imgur.com/a/ica2M
1. The GearScoreLite addon is not working properly with ElvUI, or maybe it's because of ElvUI Bunny... it doesn't show my total score on the character page. Can you guys fix it?
2. The zone text is in the middle of the screen, and I have no idea how to move it upwards :( Can someone tell me how to do it?
3. Is there a way to change the font for the cooldown tracker on the actionbar?

Keep up the good work! :)

**Comment by Apollyonn** [comment]
What version of Gearscore do you use?

**Comment by nadszeg** [comment]
I'm using GearScore Lite 3x04 from here: https://wow.curseforge.com/projects/gearscorelite/files

**Comment by Apollyonn** [comment]
![wowscrnshot_020417_135451](https://cloud.githubusercontent.com/assets/19589902/22618303/bff4d23c-eae1-11e6-949b-af61a40a59a0.jpg)
Seems fine to me.
Make sure that you have the latest version of ElvUI_Bunny.

**Comment by nadszeg** [comment]
I finally found out how to add the outline to the text, works perfectly, thanks :)
