### ISSUE TITLE
Панель ядов

### ISSUE THREAD

**Issue by Sdw8** [ElvUI-WotLK/ElvUI#340]
Можно ли добавить панель с ядами для разбойника вроде этих: [https://wow.curseforge.com/projects/poisoner](url)?

**Comment by Bunny67** [comment]
Как вариант поставь https://github.com/ElvUI-WotLK/ElvUI_ExtraActionBars и перенеси на доп панели яды. Писать аддон или его переносить думаю никто не будет, как вариант можно запилить скин под аддон.
