### ISSUE TITLE
Лаги + Lua

### ISSUE THREAD

**Issue by Sdw8** [ElvUI-WotLK/ElvUI#341]
Когда открываю окно друзей (только его) через "O" проседает фпс и окно открывается с задержкой пропорционально количеству ников в черном списке. Когда отключаю елв или черный список пуст то лаги пропадают.
Также появляются ошибки Lua связанные только с гладиусом. Это не конфликт аддонов? Заранее извиняюсь, не нашел способа поставить спойлер.
Date: 2017-02-12 20:16:42
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\Gladius\options.lua line 7:
   attempt to index global 'AceGUIWidgetLSMlists' (a nil value)
Debug:
   [C]: ?
   Gladius\options.lua:7: in main chunk
AddOns:
  Swatter, v3.1.16 (<%codename%>)
  AckisRecipeList, vv2.01-14-gfc58e9f
  Atlas, v1.17.0
  AtlasBattlegrounds, v1.17.0
  AtlasDungeonLocs, v1.17.0
  AtlasOutdoorRaids, v1.17.0
  AtlasTransportation, v1.17.0
  AtlasLoot, vv5.11.04
  AtlasLootFu, vv5.11.04
  AucAdvanced, v5.8.4723 (CreepyKangaroo)
  AucFilterBasic, v5.8.4723 (CreepyKangaroo)
  AucFilterOutlier, v5.8.4723.2531
  AucMatchUndercut, v5.8.4723.2531
  AucStatHistogram, v5.8.4723 (CreepyKangaroo)
  AucStatiLevel, v5.8.4723 (CreepyKangaroo)
  AucStatPurchased, v5.8.4723 (CreepyKangaroo)
  AucStatSales, v5.8.4723.2842
  AucStatSimple, v5.8.4723 (CreepyKangaroo)
  AucStatStdDev, v5.8.4723 (CreepyKangaroo)
  AucStatWOWEcon, v5.8.4723.2530
  AucUtilAHWindowControl, v5.8.4723.3311
  AucUtilAppraiser, v5.8.4723.2530
  AucUtilAskPrice, v5.8.4723.3175
  AucUtilAutoMagic, v5.8.4723.3142
  AucUtilCompactUI, v5.8.4723.2530
  AucUtilEasyBuyout, v5.8.4723.3583
  AucUtilGlypher, v5.8.4723.2545
  AucUtilItemSuggest, v5.8.4723.3108
  AucUtilPriceLevel, v5.8.4723.2545
  AucUtilScanButton, v5.8.4723.2530
  AucUtilScanFinish, v5.8.4723.3576
  AucUtilScanProgress, v5.8.4723.2530
  AucUtilScanStart, v5.8.4723.2530
  AucUtilSearchUI, v5.8.4723.3655
  AucUtilSimpleAuction, v5.8.4723.4546
  AucUtilVendMarkup, v5.8.4723.2530
  BankStack, vr183
  BeanCounter, v5.8.4723 (CreepyKangaroo)
  BonusScanner, v5.3
  ChatBar, v3.0
  ClassLoot, vr126
  Configator, v5.1.DEV.278
  Cromulent, vv1.5.2
  DBMCore, v
  ElvUI, v5.29
  ElvUIAddOnSkins, v1.01
  ElvUIBunny, v1.00
  ElvUIMinimapButtons, v1.01
  ElvUISwingBar, v1.0
  ElvUIVisualProcs, v1.01
  Enchantrix, v5.8.4723 (CreepyKangaroo)
  EnchantrixBarker, v5.8.4723 (CreepyKangaroo)
  EventAlert, v4.3.6
  ExplorerCoords, v1.21
  Factionizer, v30300.4
  Gatherer, v3.1.16
  GearScore, v3.1.17 - Release
  Gladius, vv1.2.0
  Recount, v
  SlideBar, v3.1.16 (<%codename%>)
  Stubby, v5.8.4723 (CreepyKangaroo)
  TomTom, vwowi:revision
  BlizRuntimeLib_ruRU v3.3.5.30300 <logon.wowcircle.com>
  (ck=7c3)

Date: 2017-02-12 20:16:42
ID: 2
Error occured in: Global
Count: 1
Message: ..\AddOns\Gladius\Gladius.lua line 15:
   attempt to call method 'getDefaults' (a nil value)
Debug:
   (tail call): ?
   Gladius\Gladius.lua:15:
      Gladius\Gladius.lua:14
   (tail call): ?
   [C]: ?
   [string "safecall Dispatcher[1]"]:9:
      [string "safecall Dispatcher[1]"]:5
   (tail call): ?
   ...AddOns\ElvUI\Libraries\AceAddon-3.0\AceAddon-3.0.lua:529: InitializeAddon()
   ...AddOns\ElvUI\Libraries\AceAddon-3.0\AceAddon-3.0.lua:644:
      ...AddOns\ElvUI\Libraries\AceAddon-3.0\AceAddon-3.0.lua:636
AddOns:
  Swatter, v3.1.16 (<%codename%>)
  AckisRecipeList, vv2.01-14-gfc58e9f
  Atlas, v1.17.0
  AtlasBattlegrounds, v1.17.0
  AtlasDungeonLocs, v1.17.0
  AtlasOutdoorRaids, v1.17.0
  AtlasTransportation, v1.17.0
  AtlasLoot, vv5.11.04
  AtlasLootFu, vv5.11.04
  AucAdvanced, v5.8.4723 (CreepyKangaroo)
  AucFilterBasic, v5.8.4723 (CreepyKangaroo)
  AucFilterOutlier, v5.8.4723.2531
  AucMatchUndercut, v5.8.4723.2531
  AucStatHistogram, v5.8.4723 (CreepyKangaroo)
  AucStatiLevel, v5.8.4723 (CreepyKangaroo)
  AucStatPurchased, v5.8.4723 (CreepyKangaroo)
  AucStatSales, v5.8.4723.2842
  AucStatSimple, v5.8.4723 (CreepyKangaroo)
  AucStatStdDev, v5.8.4723 (CreepyKangaroo)
  AucStatWOWEcon, v5.8.4723.2530
  AucUtilAHWindowControl, v5.8.4723.3311
  AucUtilAppraiser, v5.8.4723.2530
  AucUtilAskPrice, v5.8.4723.3175
  AucUtilAutoMagic, v5.8.4723.3142
  AucUtilCompactUI, v5.8.4723.2530
  AucUtilEasyBuyout, v5.8.4723.3583
  AucUtilGlypher, v5.8.4723.2545
  AucUtilItemSuggest, v5.8.4723.3108
  AucUtilPriceLevel, v5.8.4723.2545
  AucUtilScanButton, v5.8.4723.2530
  AucUtilScanFinish, v5.8.4723.3576
  AucUtilScanProgress, v5.8.4723.2530
  AucUtilScanStart, v5.8.4723.2530
  AucUtilSearchUI, v5.8.4723.3655
  AucUtilSimpleAuction, v5.8.4723.4546
  AucUtilVendMarkup, v5.8.4723.2530
  BankStack, vr183
  BeanCounter, v5.8.4723 (CreepyKangaroo)
  BonusScanner, v5.3
  ChatBar, v3.0
  ClassLoot, vr126
  Configator, v5.1.DEV.278
  Cromulent, vv1.5.2
  DBMCore, v
  ElvUI, v5.29
  ElvUIAddOnSkins, v1.01
  ElvUIBunny, v1.00
  ElvUIMinimapButtons, v1.01
  ElvUISwingBar, v1.0
  ElvUIVisualProcs, v1.01
  Enchantrix, v5.8.4723 (CreepyKangaroo)
  EnchantrixBarker, v5.8.4723 (CreepyKangaroo)
  EventAlert, v4.3.6
  ExplorerCoords, v1.21
  Factionizer, v30300.4
  Gatherer, v3.1.16
  GearScore, v3.1.17 - Release
  Gladius, vv1.2.0
  Recount, v
  SlideBar, v3.1.16 (<%codename%>)
  Stubby, v5.8.4723 (CreepyKangaroo)
  TomTom, vwowi:revision
  BlizRuntimeLib_ruRU v3.3.5.30300 <logon.wowcircle.com>
  (ck=7c3)

Date: 2017-02-12 20:16:46
ID: 3
Error occured in: Global
Count: 1
Message: ..\AddOns\Gladius\Gladius.lua line 95:
   attempt to index upvalue 'db' (a nil value)
Debug:
   (tail call): ?
   Gladius\Gladius.lua:95:
      Gladius\Gladius.lua:89
   (tail call): ?
   [C]: ?
   [string "safecall Dispatcher[1]"]:9:
      [string "safecall Dispatcher[1]"]:5
   (tail call): ?
   ...AddOns\ElvUI\Libraries\AceAddon-3.0\AceAddon-3.0.lua:558: EnableAddon()
   ...AddOns\ElvUI\Libraries\AceAddon-3.0\AceAddon-3.0.lua:651:
      ...AddOns\ElvUI\Libraries\AceAddon-3.0\AceAddon-3.0.lua:636
   [C]: LoadAddOn()
   ..\FrameXML\UIParent.lua:235: UIParentLoadAddOn()
   ..\FrameXML\UIParent.lua:258: CombatLog_LoadUI()
   ..\FrameXML\UIParent.lua:482:
      ..\FrameXML\UIParent.lua:454
AddOns:
  Swatter, v3.1.16 (<%codename%>)
  NPCScan, v3.3.5.5
  AckisRecipeList, vv2.01-14-gfc58e9f
  Atlas, v1.17.0
  AtlasBattlegrounds, v1.17.0
  AtlasDungeonLocs, v1.17.0
  AtlasOutdoorRaids, v1.17.0
  AtlasTransportation, v1.17.0
  AtlasLoot, vv5.11.04
  AtlasLootFu, vv5.11.04
  AucAdvanced, v5.8.4723 (CreepyKangaroo)
  AucFilterBasic, v5.8.4723 (CreepyKangaroo)
  AucFilterOutlier, v5.8.4723.2531
  AucMatchUndercut, v5.8.4723.2531
  AucStatHistogram, v5.8.4723 (CreepyKangaroo)
  AucStatiLevel, v5.8.4723 (CreepyKangaroo)
  AucStatPurchased, v5.8.4723 (CreepyKangaroo)
  AucStatSales, v5.8.4723.2842
  AucStatSimple, v5.8.4723 (CreepyKangaroo)
  AucStatStdDev, v5.8.4723 (CreepyKangaroo)
  AucStatWOWEcon, v5.8.4723.2530
  AucUtilAHWindowControl, v5.8.4723.3311
  AucUtilAppraiser, v5.8.4723.2530
  AucUtilAskPrice, v5.8.4723.3175
  AucUtilAutoMagic, v5.8.4723.3142
  AucUtilCompactUI, v5.8.4723.2530
  AucUtilEasyBuyout, v5.8.4723.3583
  AucUtilGlypher, v5.8.4723.2545
  AucUtilItemSuggest, v5.8.4723.3108
  AucUtilPriceLevel, v5.8.4723.2545
  AucUtilScanButton, v5.8.4723.2530
  AucUtilScanFinish, v5.8.4723.3576
  AucUtilScanProgress, v5.8.4723.2530
  AucUtilScanStart, v5.8.4723.2530
  AucUtilSearchUI, v5.8.4723.3655
  AucUtilSimpleAuction, v5.8.4723.4546
  AucUtilVendMarkup, v5.8.4723.2530
  BankStack, vr183
  BeanCounter, v5.8.4723 (CreepyKangaroo)
  BonusScanner, v5.3
  ChatBar, v3.0
  ClassLoot, vr126
  Configator, v5.1.DEV.278
  Cromulent, vv1.5.2
  DBMCore, v
  ElvUI, v5.29
  ElvUIAddOnSkins, v1.01
  ElvUIBunny, v1.00
  ElvUIMinimapButtons, v1.01
  ElvUISwingBar, v1.0
  ElvUIVisualProcs, v1.01
  Enchantrix, v5.8.4723 (CreepyKangaroo)
  EnchantrixBarker, v5.8.4723 (CreepyKangaroo)
  EventAlert, v4.3.6
  ExplorerCoords, v1.21
  Factionizer, v30300.4
  Gatherer, v3.1.16
  GearScore, v3.1.17 - Release
  Gladius, vv1.2.0
  GroupCalendar5, v5.2.3
  InspectEquip, v1.7.7
  Mapster, v1.3.9
  Omen, v3.0.9
  Overachiever, v0.56
  PhoenixStyle, v1.4961
  Poisoner, v3.3 beta2
  Postal, v3.4.0
  RaidRoll, v
  RaidRollLootTracker, v
  RaidSlackCheck, v1.112
  Recount, v
  SlideBar, v3.1.16 (<%codename%>)
  Spy, v
  SSSafeTrade, v1.1
  Stubby, v5.8.4723 (CreepyKangaroo)
  TomTom, vwowi:revision
  WarmaneAHfix, v1.5
  BlizRuntimeLib_ruRU v3.3.5.30300 <logon.wowcircle.com>
  (ck=8f0)

**Comment by Loaal** [comment]
У тебя гладиус без библиотек.
Ссылка на полную версию
https://wow.curseforge.com/projects/gladius/files/439276

**Comment by Sdw8** [comment]
Спасибо. А что за баг с черным списком?

**Comment by Loaal** [comment]
Отключи все аддоны, кроме ElvUI и ElvUI_Config, если баг останется, то будем думать.
Если же баг не в нем, то последний вариант, по очереди включать все аддоны, чтобы понять, какой из них вызывает данную проблему.

**Comment by Sdw8** [comment]
Также интересно Заменил картограф на Mapster, но наверное лучше отключить либо твики карты там либо тут. Но в елве сделать это невозможно же. Как поступить?
Нашел аддон из-за которого были проблемы с черным списком: Group Calendar5. Странно как он влияет.

**Comment by Loaal** [comment]
Зайди в дискорд, там получишь ответ, тут подобное в рамках тикета рассматривать не вижу смысла.
https://discord.gg/NCQxpm5
