### ISSUE TITLE
Option to show Debuff highlights for non dispellable debuffs

### ISSUE THREAD

**Issue by silentwinter** [ElvUI-WotLK/ElvUI#345]
I use ElvUI for raid leading and absolutely love it.

Just one problem I have is that the nameplates color doesn't change if it is undispellable by my class. 

For instance, if I am a paladin, in raid frame, the frame won't turn into Purple if the player is afflicted by Curse. Is there an option somewhere to change this setting? I've been using ElvUI for a long time and I still can't find this option anymore.

Much appreciated. Keep up the good work! I am said u guys disabled achievement animation though. I was honestly a fan of it.

**Comment by crumdidlyumshis** [comment]
Agreed completely. This is a good feature, including the animation on achievement frames.

**Comment by Apollyonn** [comment]
I assume that you mean the party/raid unitframes instead of nameplates?
If thats the case, then there is no such option, for now at least. The debuff highlight feature detects only the dispellable debuffs and then highlights the unitframes.

**Comment by silentwinter** [comment]
Yes, I meant the unitframes. And yea, I do know that there is no such option. I am asking if it is possible.

**Comment by silentwinter** [comment]
I found the workaround, although you will have to do the same thing over and over again everytime you update.

ElvUI - Libraries - oUF_Plugins - oUF_DebuffHighlight - Open it with Notepad++.

From the 5th row, it will start defining which "class-string" can dispel which debuff strings. 

Erase everything there, add this.

	PRIEST = { Magic = true, Poison = true, Disease = true, Curse = true, },
	SHAMAN = { Magic = true, Poison = true, Disease = true, Curse = true, },
	PALADIN = { Magic = true, Poison = true, Disease = true, Curse = true, },
	MAGE = { Magic = true, Poison = true, Disease = true, Curse = true, },
	DRUID = { Magic = true, Poison = true, Disease = true, Curse = true, },
	HUNTER = { Magic = true, Poison = true, Disease = true, Curse = true, },
	WARRIOR = { Magic = true, Poison = true, Disease = true, Curse = true, },
	ROGUE = { Magic = true, Poison = true, Disease = true, Curse = true, },
	DEATHKNIGHT = { Magic = true, Poison = true, Disease = true, Curse = true, },
	WARLOCK = { Magic = true, Poison = true, Disease = true, Curse = true, },

Should work like a charm
