### ISSUE TITLE
Enhancement: WorldStateAlwaysUpFrame

### ISSUE THREAD

**Issue by crumdidlyumshis** [ElvUI-WotLK/ElvUI#346]
Can you include this into the Movers config?

I don't like having to use MoveAnything.

![screenshot9676](https://cloud.githubusercontent.com/assets/7307335/23090048/d73f9814-f559-11e6-8757-fce802dc46aa.png)

**Comment by silentwinter** [comment]
Seems working now.

**Comment by crumdidlyumshis** [comment]
Thank you very much! It works great!
