### ISSUE TITLE
Support for DXE

### ISSUE THREAD

**Issue by tripleslash** [ElvUI-WotLK/ElvUI#348]
The addon Deus Vox Encounters doesn't seem compatible with ElvUI, I get lua errors when I try to load both ElvUI and DXE. It seems related to the addon dependency ACE3-locale.

**Comment by Bunny67** [comment]
What is your client language?

**Comment by tripleslash** [comment]
enGB

**Comment by Bunny67** [comment]
https://www.wowace.com/projects/deus-vox-encounters/files/458498

**Comment by silentwinter** [comment]
bump. any updates regarding this?

**Comment by silentwinter** [comment]
Message: Usage: NewLocale(application, locale[, isDefault[, silent]]): 'silent' must be specified for the first locale registered
Time: 03/22/17 12:54:14
Count: 1
Stack: ...dOns\ElvUI\Libraries\AceLocale-3.0\AceLocale-3.0.lua:101: in function `NewLocale'
Interface\AddOns\DXE_Options\Locales.lua:11: in main chunk
[C]: ?
[C]: in function `LoadAddOn'
Interface\AddOns\DXE_Loader\Loader.lua:20: in function `Load'
Interface\AddOns\DXE\Core.lua:1288: in function `ToggleConfig'
Interface\AddOns\DXE\Core.lua:2292: in function `DXE_SLASH_HANDLER'
Interface\AddOns\DXE_Loader\Loader.lua:145: in function `?'
Interface\FrameXML\ChatFrame.lua:4049: in function `ChatEdit_ParseText'
Interface\FrameXML\ChatFrame.lua:3660: in function `ChatEdit_SendText'
Interface\FrameXML\ChatFrame.lua:3698: in function <Interface\FrameXML\ChatFrame.lua:3694>
[C]: in function `ChatEdit_OnEnterPressed'
[string "*:OnEnterPressed"]:1: in function <[string "*:OnEnterPressed"]:1>

Locals: No locals to dump
