### ISSUE TITLE
not an issue just a question :)

### ISSUE THREAD

**Issue by 3majed** [ElvUI-WotLK/ElvUI#349]
can i ask what is the addon that looks like recount in this pic please :)

![5d95a2b0-f301-11e6-81e3-52d1d619c850](https://cloud.githubusercontent.com/assets/22427035/23121067/0be21a52-f770-11e6-9d4c-1c254b913c1e.jpg)

**Comment by Suonu** [comment]
This is Skada for sure

**Comment by Bunny67** [comment]
Skada + Bui One Pixel texture
