### ISSUE TITLE
Doesn't work with koKR client.

### ISSUE THREAD

**Issue by silentwinter** [ElvUI-WotLK/ElvUI#351]
Hello,

I am a Korean player usually playing on English client.

I wanted to promote this to my Korean friends in Warmane too, but it seems like it is just not working at all for Korean client. 

This is an error you get: 
Message: Interface\AddOns\ElvUI\core\fonts.lua:7: attempt to index local 'obj' (a nil value)
Time: 02/23/17 23:32:09
Count: 1
Stack: Interface\AddOns\ElvUI\core\fonts.lua:7: in function <Interface\AddOns\ElvUI\core\fonts.lua:6>
Interface\AddOns\ElvUI\core\fonts.lua:72: in function `UpdateBlizzardFonts'
Interface\AddOns\ElvUI\core\core.lua:228: in function `UpdateMedia'
Interface\AddOns\ElvUI\init.lua:83: in function <Interface\AddOns\ElvUI\init.lua:38>
(tail call): ?
[C]: ?
[string "safecall Dispatcher[1]"]:9: in function <[string "safecall Dispatcher[1]"]:5>
(tail call): ?
...AddOns\ElvUI\Libraries\AceAddon-3.0\AceAddon-3.0.lua:529: in function `InitializeAddon'
...AddOns\ElvUI\Libraries\AceAddon-3.0\AceAddon-3.0.lua:644: in function <...AddOns\ElvUI\Libraries\AceAddon-3.0\AceAddon-3.0.lua:636>

Locals: obj = nil
font = "Fonts\2002.TTF"
size = 12
style = nil
r = nil
g = nil
b = nil
sr = nil
sg = nil
sb = nil
sox = nil
soy = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'obj' (a nil value)"

Would love to make it work in a basic level at least. I can do translations and whatnot.

**Comment by Bunny67** [comment]
Check

**Comment by silentwinter** [comment]
Sorry for late feedback.

Works flawlessly; just few problems.

1.) http://imgur.com/a/IYC3w
There is a "game rating" button in the game menu on koKR client and it is stacked with some other button.

2.) Sharedmedia doesn't seem to work? For bar textures, it does work, but for Fonts, sharedmedia doesn't seem to work. Maybe because these fonts don't support Korean, I don't know.

**Comment by Loaal** [comment]
Sharedmedia shows only declared fonts, i'm not sure what [list of Korean fonts](https://github.com/ElvUI-WotLK/ElvUI/blob/master/ElvUI/Libraries/LibSharedMedia-3.0/LibSharedMedia-3.0.lua#L94) is valid.
Without koKR client i can't verify anything.
Share the link to it or if you can upload archive of WOW/Data/**koKR** folder.

**Comment by silentwinter** [comment]
https://drive.google.com/file/d/0BwTLY1oInenEM1ZEeUNrbWZwMjA/view?usp=sharing

Here is the koKR Data file.. Hopefully it helps!

**Comment by Bunny67** [comment]
Is it good working now?

**Comment by silentwinter** [comment]
Hi, just checked. The buttons are still stacked however. The buttons stacked are "Ratings" and "AddOns".

**Comment by silentwinter** [comment]
SharedMedia still doesn't seem to work. I guess it's because those fonts don't support Koreans.

**Comment by Bunny67** [comment]
https://github.com/ElvUI-WotLK/ElvUI_Bunny updated

**Comment by Bunny67** [comment]
Yes. fonts don't support Koreans

**Comment by silentwinter** [comment]
Yea, I have the updated version. The button ("rating") is skinned, but it is still stacked. 

Also, where should I put the fonts to make it work with SharedMedia?

**Comment by Bunny67** [comment]
The button ("rating") is skinned in ElvUI, bug stacked from ElvUI_Bunny

**Comment by Bunny67** [comment]
Change ElvUI\media\sharedmedia.lua on https://gist.github.com/Bunny67/dc6dd8b4c5017ab53469587afa653ff1

**Comment by Bunny67** [comment]
If OK, then add

**Comment by Bunny67** [comment]
![wowscrnshot_030317_003840](https://cloud.githubusercontent.com/assets/5816685/23528143/cf6863e6-ffa9-11e6-8ac5-b0d5b73556ba.jpg)

**Comment by Bunny67** [comment]
Fonts not support

**Comment by Bunny67** [comment]
![wowscrnshot_030317_004050](https://cloud.githubusercontent.com/assets/5816685/23528209/11dc9594-ffaa-11e6-8e65-63bce23dcc0f.jpg)

**Comment by silentwinter** [comment]
Oh it's the Elvui bunny. Alright I will try it after this round! thanks.

**Comment by Bunny67** [comment]
Close?

**Comment by silentwinter** [comment]
Close, it has been resolved.
