### ISSUE TITLE
ZOMGBuffs icon doesn't show on Minimap

### ISSUE THREAD

**Issue by silentwinter** [ElvUI-WotLK/ElvUI#352]
http://imgur.com/a/HeGC1

Minimap icon is missing :/

It seems it has frame level 4 which is the minimap level at.

Is there a way to fix this? I tried looking into Addon's Fubar plugin, but couldn't really achieve anything.

**Comment by Loaal** [comment]
`ZOMGBuffs.minimapFrame:SetFrameLevel(Minimap:GetFrameLevel() + 1)`

[ElvUI_MinimapButtons](https://github.com/ElvUI-WotLK/ElvUI_MinimapButtons) works fine
![capture](https://cloud.githubusercontent.com/assets/590348/23393269/c049b630-fd92-11e6-9c66-16b5f4506d6c.PNG)

**Comment by silentwinter** [comment]
Thanks .Didn't know there was such a plugin. 

Seems like I am getting following LUA error.

Message: ...e\AddOns\ZOMGBuffs_SelfBuffs\ZOMGBuffs_SelfBuffs.lua:566: attempt to call global 'tinsret' (a nil value)
Time: 02/28/17 02:13:42
Count: 1
Stack: ...\AddOns\ZOMGBuffs\libs\AceAddon-2.0\AceAddon-2.0.lua:25: in function <...\AddOns\ZOMGBuffs\libs\AceAddon-2.0\AceAddon-2.0.lua:23>
...\AddOns\ZOMGBuffs\libs\AceAddon-2.0\AceAddon-2.0.lua:1055: in function `ManualEnable'
...\AddOns\ZOMGBuffs\libs\AceAddon-2.0\AceAddon-2.0.lua:552: in function <...\AddOns\ZOMGBuffs\libs\AceAddon-2.0\AceAddon-2.0.lua:545>
...\AddOns\ZOMGBuffs\libs\AceAddon-2.0\AceAddon-2.0.lua:674: in function `InitializeAddon'
...\AddOns\ZOMGBuffs\libs\AceAddon-2.0\AceAddon-2.0.lua:541: in function <...\AddOns\ZOMGBuffs\libs\AceAddon-2.0\AceAddon-2.0.lua:518>
[C]: ?
...\AddOns\ZOMGBuffs\libs\AceEvent-2.0\AceEvent-2.0.lua:298: in function `TriggerEvent'
...\AddOns\ZOMGBuffs\libs\AceEvent-2.0\AceEvent-2.0.lua:910: in function <...\AddOns\ZOMGBuffs\libs\AceEvent-2.0\AceEvent-2.0.lua:903>
[C]: ?
[C]: in function `LoadAddOn'
Interface\AddOns\ZOMGBuffs\ZOMGBuffs.lua:5537: in function `OnEnableOnce'
Interface\AddOns\ZOMGBuffs\ZOMGBuffs.lua:5701: in function <Interface\AddOns\ZOMGBuffs\ZOMGBuffs.lua:5688>
[C]: in function `pcall'
...\AddOns\ZOMGBuffs\libs\AceAddon-2.0\AceAddon-2.0.lua:24: in function <...\AddOns\ZOMGBuffs\libs\AceAddon-2.0\AceAddon-2.0.lua:23>
...\AddOns\ZOMGBuffs\libs\AceAddon-2.0\AceAddon-2.0.lua:1055: in function `ManualEnable'
...\AddOns\ZOMGBuffs\libs\AceAddon-2.0\AceAddon-2.0.lua:983: in function <...\AddOns\ZOMGBuffs\libs\AceAddon-2.0\AceAddon-2.0.lua:976>
[C]: ?
...\AddOns\ZOMGBuffs\libs\AceEvent-2.0\AceEvent-2.0.lua:260: in function `TriggerEvent'
...\AddOns\ZOMGBuffs\libs\AceEvent-2.0\AceEvent-2.0.lua:910: in function <...\AddOns\ZOMGBuffs\libs\AceEvent-2.0\AceEvent-2.0.lua:903>

Locals: No locals to dump

**Comment by silentwinter** [comment]
Also could it be possible to get like a list of elvui plugins that you guys made? There are so many helpful additions that can't be just missed.

**Comment by Loaal** [comment]
[List of plugins](https://github.com/ElvUI-WotLK) :)
Which version of ZOMGBuffs do you use?

**Comment by silentwinter** [comment]
Jesus christ there are SO MANY OF THEM that I've been missing out on!! 

Thank you so much, you guys are the best honestly.

I am using version 141 ; https://www.wowace.com/projects/zomgbuffs/files/399951

**Comment by Loaal** [comment]
r160: https://www.wowace.com/projects/zomgbuffs/files/461266

**Comment by Loaal** [comment]
About error, try to add at the top of the file `ZOMGBuffs_SelfBuffs\ZOMGBuffs_SelfBuffs.lua`
`local tinsret = table.insert`

**Comment by silentwinter** [comment]
Swapping it to the version you linked resolve the issue. Thank you again! 

I am trying all the plugins, and I already can feel I will love them.

Just on thing, I think ElvUI_Enhanced's minimap coordination system is quite redundant with ElvUI_Loc!

**Comment by silentwinter** [comment]
You can close this thread btw- Thanks again!
