### ISSUE TITLE
RaidDebuff icon doesn't show? 

### ISSUE THREAD

**Issue by silentwinter** [ElvUI-WotLK/ElvUI#353]
Hello, it seems like RaidDebuff Indicator doesn't seem to work correctly. Could someone confirm?

I have auras set up, but they don't show if the icon doesn't show in the frame.

I.E. If someone is affected by Infest on Lich King, it doesn't show Infest icon on the raidframe.

If there is any special setup I need to do, please let me know! I have it enabled, of course.

**Comment by silentwinter** [comment]
bump. Is this a known issue or am I the only one cuz I am messing up something.

**Comment by Loaal** [comment]
Can't verify the problem because no longer play Wow.
Summoning @Bunny67

**Comment by Bunny67** [comment]
The reason was found, @Loaal is doing it :P

**Comment by Bunny67** [comment]
Check

**Comment by silentwinter** [comment]
Will check later

**Comment by Bunny67** [comment]
Хорошо :)
