### ISSUE TITLE
[Suggestion] GroupCalendar

### ISSUE THREAD

**Issue by lierox90** [ElvUI-WotLK/ElvUI#356]
Hi, Ive recently encountered this issue that with GroupCalendar installed DataPanel option of date/time doesnt open GroupCalendard but regular wow calendar instead, could this be included as a tweak maybe ?

**Comment by Loaal** [comment]
Can't reproduce with latest version of GroupCalendar for WotLK ([5.2.3](https://wow.curseforge.com/projects/group-calendar/files/424841))

**Comment by lierox90** [comment]
Proper group calendar version for 3.3.5a patch ofc is 4.6.1.

01.03.2017 20:32 "Loaal" <notifications@github.com> napisał(a):

**Comment by Loaal** [comment]
I've added the fix to [ElvUI_Enchanced](https://github.com/ElvUI-WotLK/ElvUI_Enhanced)
