### ISSUE TITLE
Datatext - Time/Date - Text Color

### ISSUE THREAD

**Issue by crumdidlyumshis** [ElvUI-WotLK/ElvUI#357]
Could you change the date color text to be like this:

**White** (blue)/(blue) **White** (blue)/(blue) **White**

**03** (blue)/(blue) **02** (blue)/(blue) **17**

![wowscrnshot_030217_204304](https://cloud.githubusercontent.com/assets/7307335/23536206/043ae0c4-ff89-11e6-9a43-e172d297e08b.jpg)

**Comment by Loaal** [comment]
Looks ugly
![untitled](https://cloud.githubusercontent.com/assets/590348/23579437/6da3d716-00fe-11e7-80ba-7716510241a1.png)

**Comment by crumdidlyumshis** [comment]
Could it be a checkbox option? Its hard for me to see the dark blue on the dark background. My eyes are getting worse :(

**Comment by Loaal** [comment]
added to [ElvUI_Enhanced](https://github.com/ElvUI-WotLK/ElvUI_Enhanced)

**Comment by crumdidlyumshis** [comment]
Thank you!
