### ISSUE TITLE
Spell panel i s missing

### ISSUE THREAD

**Issue by L0ki13** [ElvUI-WotLK/ElvUI#359]
Hello! I have a clear wow client without any addons. I had install ur ui, and i cant see this panel. trying to find in setting, but I cant. Please help me.
Screenshots: 
[1](https://pp.userapi.com/c639426/v639426407/e008/a3VEZVEaEOw.jpg)
[2](https://pp.userapi.com/c639426/v639426407/e011/5muw-1zgz6k.jpg)
[3](https://pp.userapi.com/c639426/v639426407/e01b/bnXaJ_Lv_Iw.jpg)

**Comment by Bunny67** [comment]
На русском пиши если знаешь. Что за аддон на миникарте?

**Comment by Bunny67** [comment]
Сервер использует кастом патч для игры, который изменяет интерфейс. Под него аддон подгоняться не будет.

**Comment by L0ki13** [comment]
не подскажешь, как и что я могу попробовать сделать, чтобы решить эту проблему?
