### ISSUE TITLE
Watch Frame Item Icons

### ISSUE THREAD

**Issue by lierox90** [ElvUI-WotLK/ElvUI#360]
As you can see on screenshot fragment i have placed, icon of item associeted with quest seems to be little off on the text.

![image](https://cloud.githubusercontent.com/assets/4543689/23770110/0e64556a-0512-11e7-9060-d14e2010e94e.png)

**Comment by Apollyonn** [comment]
This happens with only ElvUI enabled?

**Comment by lierox90** [comment]
It was ok till whole ElvUI update i made like 2 days ago.

10.03.2017 00:13 "Apollyonn" <notifications@github.com> napisał(a):

**Comment by lierox90** [comment]
It was ok till whole ElvUI update i made like 2 days ago.

On image is list of ElvUI addons i use, only them have been updated, the marked one is new addition.

![image](https://cloud.githubusercontent.com/assets/4543689/23782433/d384c388-0554-11e7-9c8f-ca0bf9ecd512.png)
