### ISSUE TITLE
Backporting to 2.4.3

### ISSUE THREAD

**Issue by crumdidlyumshis** [ElvUI-WotLK/ElvUI#361]
Point me in the direction for backporting this to 2.4.3 TBC

I want to really dig into LUA more. I know its possible, not easily feasible. 

Show me where to begin. Where you started with LUA? What guides did you use? 
I have some links to the TBC api and some guides, but nothing that really makes me understand "where to begin."

http://wowwiki.wikia.com/wiki/World_of_Warcraft_API?oldid=1564468

https://github.com/haimanman/SciTE-ru-jx3/blob/master/api/LuaWoW.api

This would be fun and something new for me. TBC private community is growing and soon some really good servers will pop up!

**Comment by Bunny67** [comment]
![wowscrnshot_031717_231105](https://cloud.githubusercontent.com/assets/5816685/24061074/0678f710-0b67-11e7-8006-a7246b3ef6ee.jpg)
:D

**Comment by Bunny67** [comment]
Maybe someday it will appear on 2.4.3

**Comment by crumdidlyumshis** [comment]
WTF HOW DID YOU DO THIS!?

Your a freakin wizard! Can you share me what you have?

![9703336](https://cloud.githubusercontent.com/assets/7307335/24063510/0a0d3244-0b2e-11e7-9c18-71e8b60292c3.jpg)

**Comment by Bunny67** [comment]
No :(

**Comment by crumdidlyumshis** [comment]
hahahaha @ the LOL on the datatext

**Comment by crumdidlyumshis** [comment]
![tim-and-eric-mind-blown](https://cloud.githubusercontent.com/assets/7307335/24063746/f555f8b2-0b2e-11e7-9f56-71ec277eceb6.gif)

**Comment by Bunny67** [comment]
Start on https://gitlab.com/Bunny67/ElvUI-BK
So far, there is not much that works

**Comment by crumdidlyumshis** [comment]
Shit man, you really are the most gifted developer! This is great 👍🏻 awesome work!

**Comment by crumdidlyumshis** [comment]
Anymore updates soon? I will push some if needed. Nothing big though.

**Comment by Bunny67** [comment]
https://github.com/ElvUI-TBC/ElvUI

**Comment by crumdidlyumshis** [comment]
Awesome! Thanks! I will close this :)
