### ISSUE TITLE
Weirt things since new update

### ISSUE THREAD

**Issue by nadszeg** [ElvUI-WotLK/ElvUI#363]
Hi! 

Since the last update, I lost my existing profile and settings, so I had to redo my layout... After that I got a message that said I have to disable ElvUI so I won't get LUA errors. Can you fix this? :(

**Comment by Bunny67** [comment]
Show errors

**Comment by nadszeg** [comment]
It's all good since then :) Sorry :(

**Comment by Bunny67** [comment]
Close?

**Comment by nadszeg** [comment]
I re-enabled my addons after disabling them, and restarted the game. After that I get no errors.

**Comment by Bunny67** [comment]
/run SetCVar("scriptErrors", 1)
To turn on LUA error or use addon BugSack
