### ISSUE TITLE
New nameplates

### ISSUE THREAD

**Issue by Tristan000** [ElvUI-WotLK/ElvUI#364]
1) Possible to add separate reaction colors to Friendly & Friendly NPC plates like it was before? Right now when you do battlegrounds or arenas all friendly players and npc are colored green and its confusing. Before was blue color for NPC and green for Players and it was ok.

2) There seems to be an issue when you disable the healthbar at Friendly NPC, sometimes it will still show on top of the name.

3) Possible to get an option to change the color of the name?

**Comment by Bunny67** [comment]
![wowscrnshot_031117_163553](https://cloud.githubusercontent.com/assets/5816685/23823683/d893b562-0678-11e7-8485-cf9d845f587d.jpg)
1. So it be good?

2. random bug :(

**Comment by Tristan000** [comment]
Ye colors seems ok in the screenshot.

Also there are some lua errors when you instal the UI.

1) Message: Interface\AddOns\ElvUI\core\core.lua:764: attempt to call method 'UpdateAllPlates' (a nil value)
Time: 03/11/17 15:37:57
Count: 2
Stack: [C]: in function `UpdateAllPlates'
Interface\AddOns\ElvUI\core\core.lua:764: in function `UpdateAll'
Interface\AddOns\ElvUI\core\install.lua:236: in function `SetupTheme'
Interface\AddOns\ElvUI\core\install.lua:755: in function <Interface\AddOns\ElvUI\core\install.lua:755>

2) Message: Interface\AddOns\ElvUI\core\core.lua:764: attempt to call method 'UpdateAllPlates' (a nil value)
Time: 03/11/17 15:38:00
Count: 1
Stack: [C]: in function `UpdateAllPlates'
Interface\AddOns\ElvUI\core\core.lua:764: in function `UpdateAll'
Interface\AddOns\ElvUI\core\install.lua:334: in function `SetupResolution'
Interface\AddOns\ElvUI\core\install.lua:775: in function <Interface\AddOns\ElvUI\core\install.lua:775>

3) Message: Interface\AddOns\ElvUI\core\core.lua:764: attempt to call method 'UpdateAllPlates' (a nil value)
Time: 03/11/17 15:38:02
Count: 1
Stack: [C]: in function `UpdateAllPlates'
Interface\AddOns\ElvUI\core\core.lua:764: in function `UpdateAll'
Interface\AddOns\ElvUI\core\install.lua:610: in function `SetupLayout'
Interface\AddOns\ElvUI\core\install.lua:786: in function <Interface\AddOns\ElvUI\core\install.lua:786>

4) Message: ...dOns\ElvUI\modules\nameplates\elements\healthBar.lua:95: attempt to index field 'db' (a nil value)
Time: 03/11/17 15:39:50
Count: 3
Stack: [C]: ?
...dOns\ElvUI\modules\nameplates\elements\healthBar.lua:95: in function `ConfigureElement_HealthBar'
...rface\AddOns\ElvUI\modules\nameplates\nameplates.lua:295: in function <...rface\AddOns\ElvUI\modules\nameplates\nameplates.lua:279>

5) Message: ...rface\AddOns\ElvUI\modules\nameplates\nameplates.lua:372: attempt to call field '?' (a nil value)
Time: 03/11/17 15:41:16
Count: 1
Stack: (tail call): ?
...rface\AddOns\ElvUI\modules\nameplates\nameplates.lua:372: in function `ForEachPlate'
Interface\AddOns\ElvUI_Config\nameplates.lua:816: in function <Interface\AddOns\ElvUI_Config\nameplates.lua:812>
(tail call): ?
[C]: ?
[string "safecall Dispatcher[5]"]:9: in function <[string "safecall Dispatcher[5]"]:5>
(tail call): ?
...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:799: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:614>
(tail call): ?
[C]: ?
[string "safecall Dispatcher[6]"]:9: in function <[string "safecall Dispatcher[6]"]:5>
(tail call): ?
...Ons\ElvUI_Config\Libraries\AceGUI-3.0\AceGUI-3.0.lua:314: in function `Fire'
...ries\AceGUI-3.0\widgets\AceGUIWidget-ColorPicker.lua:33: in function <...ries\AceGUI-3.0\widgets\AceGUIWidget-ColorPicker.lua:21>
...ries\AceGUI-3.0\widgets\AceGUIWidget-ColorPicker.lua:67: in function `opacityFunc'
[string "*:OnClick"]:4: in function <[string "*:OnClick"]:1>
[C]: ?

**Comment by Bunny67** [comment]
error fixed and colored added. check

**Comment by Bunny67** [comment]
3. The color of the name of whom?

**Comment by Tristan000** [comment]
I mean the name of a player or npc. Right now it has the same color with the healthbar. Before it was white.

Also i think i found another issue. Sometimes when a nameplates appears it has an empty castbar with a spell icon. The spell icon is the same from a previous targeted person who casted a spell.

**Comment by Bunny67** [comment]
1. check

2. Make a screenshot

**Comment by Bunny67** [comment]
2. random bugs :( should also hide as in the previous version. I could not reproduce :(

**Comment by Bunny67** [comment]
is already too much is not needed when a new bug, create a new issues
