### ISSUE TITLE
Nameplate castbar bug

### ISSUE THREAD

**Issue by Tristan000** [ElvUI-WotLK/ElvUI#365]
This castbar appears as soon as the nameplate show and hides after 1 second.

It took me a while to reproduce it and take a clear screenshot.
![123](https://cloud.githubusercontent.com/assets/20983405/23824182/883239ca-067a-11e7-9987-280fc30de47a.jpg)
![1234](https://cloud.githubusercontent.com/assets/20983405/23824367/061e0ee2-067e-11e7-8fa3-c3283997e188.jpg)

**Comment by Tristan000** [comment]
Also Disable castbar option doesn't work.

**Comment by Bunny67** [comment]
not fix?

**Comment by Tristan000** [comment]
This was a rare bug, i will try to reproduce it now and i will tell you in 10 minutes.

**Comment by Tristan000** [comment]
Not fixed.

**Comment by Bunny67** [comment]
Check how it will be possible again

**Comment by Tristan000** [comment]
It seems that its fixed now. Tried multiple times and i wasn't able to reproduce it.

Question: Did you finish with this nameplates? I mean, are you going to add more features to them? Like Show/Hide & Color filters like the old nameplates?

**Comment by Bunny67** [comment]
Yes. Not in ElvUI. No, in the future yes.

**Comment by Bunny67** [comment]
filters support is added
