### ISSUE TITLE
Nameplates combo points bug

### ISSUE THREAD

**Issue by Tristan000** [ElvUI-WotLK/ElvUI#368]
Combo points appear to random nameplates.

![combo](https://cloud.githubusercontent.com/assets/20983405/23831967/3ed5c2d2-0734-11e7-9436-cb3f0023f27a.jpg)
![combo 2](https://cloud.githubusercontent.com/assets/20983405/23831997/0e025db8-0735-11e7-98a7-50d68737792b.jpg)

**Comment by Bunny67** [comment]
https://youtu.be/HttPhd19sh0
Can not reproduce

**Comment by Tristan000** [comment]
Try to enable all nameplates, the nameplate you attacked must not be visible. Try to attack the dummy and then move away.

**Comment by Bunny67** [comment]
Make sure you enable Lua Errors

**Comment by Bunny67** [comment]
On FRIENDLY_PLAYER and FRIENDLY_NPC can not show them

**Comment by Tristan000** [comment]
No lua errors, i made a video. will upload it now and post it here.

**Comment by Bunny67** [comment]
https://youtu.be/xTGMSVRzqgw

**Comment by Tristan000** [comment]
pause at 0.10 and look left

**Comment by Bunny67** [comment]
Check

**Comment by Tristan000** [comment]
fixed
