### ISSUE TITLE
Guild Notes - Overlapping Elements

### ISSUE THREAD

**Issue by datbunneh** [ElvUI-WotLK/ElvUI#369]
![guild_notes](https://cloud.githubusercontent.com/assets/9550798/23857859/5529c1ae-0807-11e7-9382-37aea245d1d5.png)

As far as I remember, if officer notes are present, then those buttons overlap them instead.

**Comment by Bunny67** [comment]
Blizzard interface bug. Change general font size

**Comment by datbunneh** [comment]
And there is no way to fix it without changing font size?

**Comment by Bunny67** [comment]
No

**Comment by Bunny67** [comment]
GUILD_DETAIL_NORM_HEIGHT = 195
GUILD_DETAIL_OFFICER_HEIGHT = 255

**Comment by Bunny67** [comment]
You can change these values and add their any of addon

**Comment by datbunneh** [comment]
But I cannot make the entire frame containing both fields larger?

**Comment by Bunny67** [comment]
GUILD_DETAIL_NORM_HEIGHT = 195 -- one
GUILD_DETAIL_OFFICER_HEIGHT = 255 -- both
