### ISSUE TITLE
Nameplates Target Scale Applied in Combat when Turned Off

### ISSUE THREAD

**Issue by datbunneh** [ElvUI-WotLK/ElvUI#373]
Nameplate grows in size after combat starts (115%):
![nameplates_target_scale](https://cloud.githubusercontent.com/assets/9550798/23864923/b4ae55f8-081c-11e7-92f4-c064aa2cac7c.png)
However it's turned off in options:
![nameplates_target_scale_options](https://cloud.githubusercontent.com/assets/9550798/23864960/c785744a-081c-11e7-8896-61b049d16b5b.png)

**Comment by Bunny67** [comment]
120% :) Change Bad Scale

**Comment by datbunneh** [comment]
Changing to 120% did not work, it's still getting scaled when turned off.

**Comment by Bunny67** [comment]
![wowscrnshot_031317_200038](https://cloud.githubusercontent.com/assets/5816685/23865767/c35a4160-0827-11e7-8790-f3499e7dede3.jpg)

**Comment by datbunneh** [comment]
Oh crap, did not get your point. Thanks!
