### ISSUE TITLE
Nameplates Health Animations

### ISSUE THREAD

**Issue by datbunneh** [ElvUI-WotLK/ElvUI#374]
Not sure if it's intended, but after latest updates the animation of health gain/depletion is missing.
It instantly drops to the new value after barely noticable delay.

**Comment by Bunny67** [comment]
This feature will not be added

**Comment by datbunneh** [comment]
But why is it removed?

**Comment by Bunny67** [comment]
https://github.com/ElvUI-WotLK/ElvUI#i-would-like-to-request-a-feature-where-do-i-go

**Comment by datbunneh** [comment]
You mean it was removed in original ElvUI?

**Comment by Bunny67** [comment]
There he was not at all

**Comment by datbunneh** [comment]
Not sure. It's acting quite weird now, not like it used to be. Maybe it's because of a delay.

**Comment by datbunneh** [comment]
Please look for yourself, the behavior changed. Just checked it in dungeon, feels totally different.

**Comment by datbunneh** [comment]
@Bunny67, please reopen, it's not a feature request.

**Comment by Bunny67** [comment]
I don't understand what you want :(

**Comment by datbunneh** [comment]
I think I have a backup of my addons and vars before the update, gonna try to make a video comparison of how it was and how it is now.

**Comment by datbunneh** [comment]
@Bunny67, here is the videos, As I said, behavior changed.
Before: https://www.youtube.com/watch?v=K2_VBm6gukQ
After: https://www.youtube.com/watch?v=j9qp44lkiEk

**Comment by Bunny67** [comment]
this animations healthbar effect not added and will not be added

**Comment by datbunneh** [comment]
So it's removed on purpose?

**Comment by Bunny67** [comment]
Yes

**Comment by datbunneh** [comment]
:(

**Comment by crumdidlyumshis** [comment]
Well that sucks. I liked this animation effect. :( 👎

**Comment by Bunny67** [comment]
https://youtu.be/SEPU6ddx7Cs
Will be added to the plugin
