### ISSUE TITLE
Good Color Does Not Apply on Nameplates

### ISSUE THREAD

**Issue by datbunneh** [ElvUI-WotLK/ElvUI#375]
Just got through a dungeon and could only see two colors - bad and bad transition.

**Comment by Bunny67** [comment]
good color for tanked. bad color for dps

**Comment by Bunny67** [comment]
You role?

**Comment by datbunneh** [comment]
My role is dps and here are my options:
![nameplate_colors_options](https://cloud.githubusercontent.com/assets/9550798/23867104/7d810894-0823-11e7-9a13-672f3130e6f5.png)
I've seen only red and orange nameplates.

**Comment by Bunny67** [comment]
Will be fixed closer to the weekend

**Comment by Bunny67** [comment]
Now it works as it should?

**Comment by datbunneh** [comment]
Somewhat. What is weird is when I duel with npcs in Argent Tournament (on a mount with lance), their nameplates are orange.
