### ISSUE TITLE
Nameplates No Target Overlap

### ISSUE THREAD

**Issue by datbunneh** [ElvUI-WotLK/ElvUI#377]
I don't know, maybe it's intended. When I have no target all nameplates do not look transparent but I can see borders of nameplates that are in background.
![nameplates_no_target_overlap](https://cloud.githubusercontent.com/assets/9550798/23905861/04629e5c-08d5-11e7-82da-1f33b40c70af.png)

**Comment by Bunny67** [comment]
Blizzard bug. not fix

**Comment by datbunneh** [comment]
@Bunny67, just tested out on how it was working before.
Looks like border used to have lower strata than background, so it simply was disappearing behind it.
I don't know, which one is better though.

**Comment by Bunny67** [comment]
This option is better. It is also used in TidyPlates

**Comment by datbunneh** [comment]
Okay. :>
