### ISSUE TITLE
[Minimap] Shaman Weapon Buffs

### ISSUE THREAD

**Issue by Will-Scarlet** [ElvUI-WotLK/ElvUI#379]
It seems that instead of the weapon buffs shamans use showing within Player Buffs they proc on the minimap. I don't know if this is intentional or not but is very inconvenient if it can not be disabled.

**Comment by silentwinter** [comment]
Not sure how it works with Shamans, but for other classes that use weapon enchants, it comes on the move-able pannel. Toggle anchors and move around to where you want. 

http://imgur.com/a/28Fop
