### ISSUE TITLE
watch frame error

### ISSUE THREAD

**Issue by TheRealestMcCoy** [ElvUI-WotLK/ElvUI#382]
Date: 2017-03-28 16:25:20
ID: 1
Error occured in: Global
Count: 1
Message: ..\FrameXML\Cooldown.lua line 3:
   attempt to compare number with nil
Debug:
   [C]: ?
   ..\FrameXML\Cooldown.lua:3: CooldownFrame_SetTimer()
   ..\FrameXML\WatchFrame.lua:1194: WatchFrameItem_UpdateCooldown()
   ..\FrameXML\WatchFrame.lua:1210: WatchFrameItem_OnEvent()
   [string "*:OnEvent"]:1:
      [string "*:OnEvent"]:1

**Comment by Loaal** [comment]
Server-side bug.
