### ISSUE TITLE
Spellflash issue

### ISSUE THREAD

**Issue by Delinquent1** [ElvUI-WotLK/ElvUI#383]
Hello guys and thank you for your efforts keeping this ui alive.
After you latest update of the whole ui, Spellflash is not working anymore.
Reading through forums and various sites it is problem with spellflash and not elvui.
http://git.tukui.org/Elv/elvui/issues/807
According to those posts, the issue has to do with the action bar libraries that spellflash is using that do not correspond with the modified action bar libraries elvui is using.
Is there any work around that comes from the top of your heads to make this addon work again somehow?
Supposely i could ask for a solution to the responsible addon forums however, it is not mentained any more for 3.3.5 version so i suppose it is kinda pointless.
Thank you very much for you time and effort.
Hoping to hear from you soon!
Cheers

**Comment by Loaal** [comment]
I guess without direct editing of Spellflash files its imposible.
1. You need to open `Interface\AddOns\SpellFlashCore\SpellFlashCore.lua`
2. find line with `local function RegisterFrames()`
3. Add few lines of [code](https://gist.github.com/Loaal/f68ec8043d1bd9f53dc780d200c46d25/revisions?diff=split)
