### ISSUE TITLE
Проблемка с неймплейтами.

### ISSUE THREAD

**Issue by freesay** [ElvUI-WotLK/ElvUI#387]
Здравствуй. В одном из последних обновлений появился один досадный момент. Частенько неймплейты не выходят из прозрачности, во время экшена и резкой смены цели. Как-то очень уж привык ориентироваться на эти индикаторы. А с этим багом трудно сразу сообразить кто в таргете, каково значение агро. Не сказать, что раельную трудность представляет, но несколько сбивает с толку.
![wowscrnshot_041217_141702](https://cloud.githubusercontent.com/assets/19500175/24967123/c0a4ac48-1fb1-11e7-8fbf-2a5a42d61aea.jpg)

**Comment by silentwinter** [comment]
Don't understand Russian, but pretty sure I understand what he is talking about.

Pretty annoying bug ATM.

**Comment by freesay** [comment]
Hi. One of the latest updates has one annoying moment. Often, the neumptyts do not come out of transparency, during combat and a sharp change of purpose. I'm used to focusing on these indicators. With this bug it is difficult to immediately figure out who is in the target, what is the significance of agro.

**Comment by silentwinter** [comment]
[img]http://imgur.com/a/JEGkt[/img]

**Comment by silentwinter** [comment]
Seems to work fine on a single target, but when there are more than 2+ targets, the problem seems to happen.

**Comment by silentwinter** [comment]
-What is odd is it works fine on dummy.

**Comment by silentwinter** [comment]
http://imgur.com/a/OndTX

Was able to reproduce on Dummy

**Comment by silentwinter** [comment]
Played around with it for awhile, I was able to reproduce the problem : https://www.youtube.com/watch?v=zCmJhDdnsNc

I think the problem is, if the target switches during the animation (before the target-bar goes to its full size/alpha) it derps out and fails to register the current target.

Just my guess.

**Comment by silentwinter** [comment]
Was able to fix it- 

ElvUI \ modules \ nameplates \ nameplates.lua

Search for phrase "ScheduleTimer"

change value 0.17 to 0.

Should fix like this.

**Comment by silentwinter** [comment]
@Bunny67

**Comment by freesay** [comment]
Фикс не помог. Все так же при резкой смене таргета неймплейты остаются прозрачными.
![2017-04-15 20-07-10](https://cloud.githubusercontent.com/assets/19500175/25065433/b61e83a2-2218-11e7-88b2-188ce11ac8fb.png)

**Comment by silentwinter** [comment]
It is because Bunny forgot to change the Scheduletimer on Line 421.

Browse to Line 421 on nameplates.lua, and change the value to 0 from 0.17

`	if not noTargetFrame then
		mod:ScheduleTimer("SetTargetFrame", 0, frame)
	end`
