### ISSUE TITLE
Квадрат по середине?

### ISSUE THREAD

**Issue by Daenerya** [ElvUI-WotLK/ElvUI#392]
После последнего обновления периодически появляется квадрат по центру экрана и не пропадает вплоть до релога. Бывает, что он практически не заметен, но границы квадрата разглядеть можно (см. скрин №2).

![wowscrnshot_042017_072759](https://cloud.githubusercontent.com/assets/26564604/25213982/9bdce3f6-2562-11e7-87dc-88f40928e369.jpg)

![wowscrnshot_041817_082744](https://cloud.githubusercontent.com/assets/26564604/25214323/a0686ea2-2564-11e7-8691-33525e8a03ca.jpg)

**Comment by Daenerya** [comment]
На данный момент квадрата нет. Смею предположить, что это из-за аддона Doom CooldownPulse.

**Comment by Daenerya** [comment]
![wowscrnshot_042017_081058](https://cloud.githubusercontent.com/assets/26564604/25214570/e67a0210-2565-11e7-80db-f8cb145f3cc7.jpg)

**Comment by Bunny67** [comment]
На этом не вижу квадрата:(

**Comment by Daenerya** [comment]
Открой скрин на весь экран, там видны границы еле-еле видные...
