### ISSUE TITLE
Информация о персонаже

### ISSUE THREAD

**Issue by Daenerya** [ElvUI-WotLK/ElvUI#393]
После последнего обновления был замечен следующий баг с открытием окна персонажа в бою.

Еще добавлю, так как не хочется плодить кучу тем:
+ Панель тотемов - во время боя невозможно поменять тотемы на панели самих тотемов, как и выбрать другой зов с тотемами...

+ Панель с метками - после обновления их невозможно скрыть, даже сотню раз релогаясь (в настройках они скрыты).

![wowscrnshot_041817_071028](https://cloud.githubusercontent.com/assets/26564604/25214769/2d4fe97e-2567-11e7-99df-c8277d41f3e5.jpg)

**Comment by Apollyonn** [comment]
Totem bar fixed with this a217e940a652d9fe91d83a2833470da7adc5160a
