### ISSUE TITLE
Баг с фреймами боссов.

### ISSUE THREAD

**Issue by freesay** [ElvUI-WotLK/ElvUI#395]
Наблюдаю баг с фреймами боссов в цлк. Не знаю как в других инстах, пока не ходил. Не обновляется значение хп. Критично, на самом деле. 
Сделал несколько скриншотов:
Сделал первый скриншот - 
![wowscrnshot_042617_132922](https://cloud.githubusercontent.com/assets/19500175/25449890/e1d017ee-2ac5-11e7-97a7-43a2623ab489.jpg)
И спустя секунду сделал второй -
![wowscrnshot_042617_132924](https://cloud.githubusercontent.com/assets/19500175/25449914/f812df82-2ac5-11e7-850d-f5f06e4849fa.jpg)
То есть, дело в том, что в какой-то момент значение хп на фреймах боссов, как бы, замерзает. И если кликнуть по нему, то он начинает показывать текущее значение. 
Но есть еще один нюанс. Иногда хп на фреймах "замерзает" насовсем. Я имею ввиду рамки боссов, те, что справа. Но в таргете значение хп продолжает функционировать нормально. 
На третьем скриншоте это показано - 
![wowscrnshot_042617_132958](https://cloud.githubusercontent.com/assets/19500175/25450038/5a78cb32-2ac6-11e7-8f29-0dd1052f1bb1.jpg)

Очень неприятный баг. Устанавливал аддон на чистый клиент совсем недавно. То есть с чистым WTF, без кэша.

**Comment by silentwinter** [comment]
This bug is due to problem with how the HP is being updated. As far as I understand, the HP on boss frame doesn't get updated unless the unit is targetted. So, until the unit is targetted, the HP will not be updated.

It is pretty annoying bug in Gunship and Blood Prince Council, but, it is a berable bug.

**Comment by silentwinter** [comment]
Seems to be working properly now!
