### ISSUE TITLE
Наложение индикаторов здоровья.

### ISSUE THREAD

**Issue by freesay** [ElvUI-WotLK/ElvUI#396]
Один досаждающий нюанс - каждый раз при новом заходе в игру, активируется галочка "Наложение имен". Всякий раз приходится лезть в настройки и отключать её =) 

![wowscrnshot_042617_182415](https://cloud.githubusercontent.com/assets/19500175/25450235/e62849aa-2ac6-11e7-80d0-73c4995f4b27.jpg)

**Comment by Bunny67** [comment]
В настройках елва изменяется

**Comment by freesay** [comment]
Точно, нашел, спасибо.
