### ISSUE TITLE
Правый чат - Recount/Skada/Omen (!!!)

### ISSUE THREAD

**Issue by Daenerya** [ElvUI-WotLK/ElvUI#400]
Очень напрягает данная проблема, приходится каждый раз удалять подчистую WTF папку и заново настраивать все аддоны, чтобы отображались Recount/Skada/Omen в правом окне чата. Когда отключаешь ElvUI - вуаля, все появляется, но как только включаешь ElvUI обратно - пиписькометры и аггро "улетают" за пределы экрана и ничего не помогает вернуть их на свое место. Сталкиваюсь с этой проблемой 4-ый раз за 2 месяца просто перезаходя в игру, ничего при этом не меняя в конфигурациях интерфейса. Исправьте, пожалуйста.

![wowscrnshot_052617_051337](https://cloud.githubusercontent.com/assets/26564604/26478089/d9347a24-4197-11e7-8677-f930c5b9b204.jpg)

![wowscrnshot_052617_051910](https://cloud.githubusercontent.com/assets/26564604/26478093/dc720382-4197-11e7-9f4b-9821f20e6ea7.jpg)

**Comment by Loaal** [comment]
Не смог воспроизвести баг.
Удостоверься, что используешь последнюю версию [ElvUI_AddOnSkins](https://github.com/ElvUI-WotLK/ElvUI_AddOnSkins)

Чтобы избежать приоблемы с потерей настроек, папку WTF можно бекапить, либо использовать встроенную в конфигуратор [функцию экспорта/импорта профилей](https://www.youtube.com/watch?v=-U9OdFjAeqU).

**Comment by Daenerya** [comment]
Стоит последняя версия, обновляю все по кд.
Если бы помогал бэкап и манипуляции с профилями, этой темы бы не было.)))
Увы, ни первый способ, ни второй проблемы не решает.

До этого, последние 2 раза у меня слетала скада из-за того, что я создала новые акки, перенесла туда существующие профили и начала редактировать аддоны под новых персонажей, затем зашла на основной аккаунт с шаманом и скады там не обнаружила, делала бэкап как говорилось выше и пробовала импортировать различные профили и настройки в том числе, но чуда не свершилось, пришлось удалить WTF.
В этот раз я абсолютно ничего не трогала, просто сделала полноценный релог на аккаунт и снова эта же картина. В чем может быть проблема? На других персонажах на этом же аккаунте и с этим же профилем такой проблемы нет.

**Comment by Loaal** [comment]
Напиши мне в [Discord](https://discord.gg/NCQxpm5) (_Pinya_), попробуем разбраться.

**Comment by Bunny67** [comment]
Должно быть исправлено в https://github.com/ElvUI-WotLK/ElvUI_AddOnSkins
