### ISSUE TITLE
Nameplates > KillTheHealer

### ISSUE THREAD

**Issue by Svannie** [ElvUI-WotLK/ElvUI#401]
The function of the addon that identifies healers works fine most of the times, but sometimes it just displays wrong targets, such as retribution paladins and warlocks.
proof
http://i.imgur.com/EvjmUrn.jpg

**Comment by silentwinter** [comment]
The function tracks all the enemies' total damage and healing done. 

The target is identified as a "healer" if healing done is greater than damage done. If the player just fucked around and did no damage, but only healed himself, he will be "wrongfully" marked as a healer.

**Comment by Svannie** [comment]
I understand, I thought it was some kind of  buff or specific spell being cast from enemy to determine spec.  It's all clear now, closing this issue.
