### ISSUE TITLE
Power bar - Energy regen

### ISSUE THREAD

**Issue by Goregrin** [ElvUI-WotLK/ElvUI#405]
Hey,
the option smooth bars does not apply to the power bar. 
Also is it possible to increase the update for the power bars to increase "smoothness"? Not just the player but others aswell?

Thanks

**Comment by silentwinter** [comment]
Click on "UnitFrames", tick "Smooth Bars" and there is an option to control animation speed.

It should work for literally any bars. 

- I hope this was what u meant.

**Comment by Goregrin** [comment]
The transition of energy when i spend like 40 energy is smooth but replenishment is pretty choppy

**Comment by Dettlaf** [comment]
I notice the same problem, you find any way fixing it?

**Comment by Bunny67** [comment]
https://gyazo.com/9366e43e0345b02147c908d1402b741f

**Comment by Loaal** [comment]
Probably fixed with 08a39c9

**Comment by Bunny67** [comment]
Check now
