### ISSUE TITLE
Tooltip Stutter/horizontal twitch movement

### ISSUE THREAD

**Issue by Goregrin01** [ElvUI-WotLK/ElvUI#411]
Hey, there is an issue when you hold shift and compare items from quest log, inventory, crafting and others. The second tooltip starts to move left and right really fast. I tried changing ui scale from ingame interface and via elvui and nothing worked. Is this a known issue?

**Comment by IgorYunusov** [comment]
Hi, I'm not developing this addon)

2017-06-21 18:03 GMT+03:00 Goregrin01 <notifications@github.com>:

**Comment by Goregrin01** [comment]
Thank you :)
