### ISSUE TITLE
Backdrop to the whole UI when I respec

### ISSUE THREAD

**Issue by blaster33333** [ElvUI-WotLK/ElvUI#414]
hi, I found a problem - when i respec (I have dual profile when respec), it makes the whole Elvui backdrop.
=> when I am arcane
![wowscrnshot_070517_215624](https://user-images.githubusercontent.com/29930111/27882604-9bc02890-61cd-11e7-9a05-d489a93ebfe2.jpg)

=> when I respec fo frost 
![wowscrnshot_070517_215637](https://user-images.githubusercontent.com/29930111/27882625-ac75573c-61cd-11e7-8f20-0816b0b52ff7.jpg)

It doesn't make sense, There is no way how to switch this off. There is only Thin Border Theme, but it's something bit different. Try to look on this. Thank you

**Comment by Apollyonn** [comment]
Go to General -> Media -> Colors - > Border Color and set it to 0 0 0.
