### ISSUE TITLE
WorldMap

### ISSUE THREAD

**Issue by wuffi-steel** [ElvUI-WotLK/ElvUI#415]
The card does not cover the unitframe.

![GitHub Logo](http://i.imgur.com/aSHQsFD.jpg)

**Comment by silentwinter** [comment]
It's because you are not using default ElvUI maps.. It does the same thing as Mapster. ( I assume that is the addon you are using )

**Comment by wuffi-steel** [comment]
Bei aktivierung des Blizzart Skinns ist die karte über dem unitframe.
Otherwise no addon is activated.

Can I convert somewhere the original Blizzard skin is also the map over the unitframe?

**Comment by silentwinter** [comment]
I don't understand what you mean; do you mean that you don't have any addon besides ElvUI? Because if that's the case, your map shouldn't look like that. It should be ElvUI backdrop.

**Comment by wuffi-steel** [comment]
![GitHub Logo](http://imgur.com/a/lhle6)

**Comment by wuffi-steel** [comment]
ElvUI Addon
![GitHub Logo](http://i.imgur.com/vzq8UNp.jpg)
ORIGINAL
![GitHub Logo](http://i.imgur.com/ksXpgyc.jpg)
Skins Disabled
![GitHub Logo](http://i.imgur.com/19N33h5.jpg)

I just want the unitframe to be behind the original Blizzard card.
I do not like the black card. Sorry
What do I have to change in the unitframes.lua?

**Comment by wuffi-steel** [comment]
In the current version of ElvUI is the unitframe behind the map.
Or. At Legion

**Comment by silentwinter** [comment]
Ah, I see what you are saying.

I will look into it this afternoon.

**Comment by silentwinter** [comment]
I did look into it for awhile, but couldn't figure out where I could adjust the frame positioning. Maybe someone else could help with this.

**Comment by crumdidlyumshis** [comment]
One idea is to add a frame level fix when skin is disabled. http://wow.gamepedia.com/API_Frame_SetFrameLevel

**Comment by silentwinter** [comment]
@crumdidlyumshis I am aware of frame level, but I just couldn't figure out how to make it work.

I set the health/power/portrait level to under 4 (world map frame level), but it would still pop up in front of it. I will google and take another look tomorrow I guess after I come back from the gym. 

This actually is a nice "homework" for me learning Lua codes a little so.. Plus for me too d: 

In case crum, you wanna take a look too, use /fstack.

**Comment by wuffi-steel** [comment]
Super I unfortunately do not know with lua.
I just noticed the mana or power bar under the name disappears behind the map.

Enjoy the workout

**Comment by silentwinter** [comment]
A little update: I did take a look/test it out for awhile now and I just can't seem to find a way through for this one. Same thing as explained above; the frame level is lower, but it still comes in front of the world map.

Very weird behavior indeed.
