### ISSUE TITLE
Name Plates

### ISSUE THREAD

**Issue by 3majed** [ElvUI-WotLK/ElvUI#416]
when you see someone progress TOGC typed wrong Totc :)
![wowscrnshot_070817_065803](https://user-images.githubusercontent.com/22427035/27985956-2096941c-63ab-11e7-87e7-d0ff19f305da.jpg)

**Comment by Loaal** [comment]
Update your [ElvUI_Enhanced](https://github.com/ElvUI-WotLK/ElvUI_Enhanced)
