### ISSUE TITLE
Hide player in party frames in arenas

### ISSUE THREAD

**Issue by Unknownd0000** [ElvUI-WotLK/ElvUI#418]
Is it possible to hide player frame in party frames while you are in an arenas. It works fine outside of arena but when u enter arena it shows player also.

**Comment by silentwinter** [comment]
Did you disable Party frame? It should work nonetheless.

**Comment by Unknownd0000** [comment]
I want party frames to be shown, but I don't want to see myself there, it works fine when outside of arena or no raid(no display player-myself in party frames), but when I enter arena I see myself in party frames, I guess it gets converted to raid6 frames and it doesn't work to disable display player there.
