### ISSUE TITLE
Дроп фпс и ошибка из-за unitframes

### ISSUE THREAD

**Issue by DafiQwart** [ElvUI-WotLK/ElvUI#424]
unitframes вызывает ошибку луа, фпс дропал до 15-20 кадров.
Так же сбивается размер targetframe хотя в настройках изменения не происходят.
Когда отключал ElvUI становилось 150-200
Вот ошибка Lua - https://pastebin.com/cj5Ks47T

Версию использую последнею 5.35 - https://github.com/ElvUI-WotLK/ElvUI/releases/tag/5.35

![screenshot](https://user-images.githubusercontent.com/30869896/29127450-c92d42c8-7d29-11e7-9fff-93533eb7a53b.png)
![screenshot_1](https://user-images.githubusercontent.com/30869896/29127724-8e6a7bfa-7d2a-11e7-9dc9-f9c514923c67.png)

![msu6itz](https://user-images.githubusercontent.com/30869896/29127738-9b29c3c8-7d2a-11e7-811d-189793652e62.jpg)

**Comment by Bunny67** [comment]
Либо можешь не обновляя Елв в настройках рейда или рейда40 убрать сортировку по Роли
