### ISSUE TITLE
cant get it to show in my addons tap in game

### ISSUE THREAD

**Issue by eclipse3480** [ElvUI-WotLK/ElvUI#425]
so i downloaded the addon and put it in my addons folder but when i open up the game its not in my addons tap dont really know how to fixed it would love a quick respond <3

**Comment by Loaal** [comment]
Make sure you moved **ElvUI** and **ElvUI_Config** to `World of Warcraft\Interface\AddOns` folder.

**Comment by eclipse3480** [comment]
ahhhh now it works thanks alot dude you just saved my day <3
