### ISSUE TITLE
Дефолтная полоска каста и рейд/пати фреймы ElvUI.

### ISSUE THREAD

**Issue by wenaern** [ElvUI-WotLK/ElvUI#427]
Привет. Дело в том, что я использую сторонние фреймы (whoaunitframes), но хочу использовать рейд и пати фреймы от ElvUI. Такое сделать вполне возможно, но вот при включении этих самых фреймов (ElvUI) дефолтная полоска каста у игрока пропадает и становится невидимой. Эту ситуацию можно исправить только сторонним аддоном, но хотелось бы всё же дефолтную.

PS: галочки стоят только на фреймах пати и рейда

**Comment by DJBoxer** [comment]
More people would help you if you said it in english?

Hey. The fact is that I use third-party frames (whoaunitframes), but I want to use raid and party frames from ElvUI. This is quite possible, but when you include these same frames (ElvUI), the default streak of caste in the player disappears and becomes invisible. This situation can be corrected only by a third-party add-on, but I would still want to default.
PS: checkboxes are only on the party and raid frames

**Comment by gamer4eg** [comment]
Пиши на ангельском, быдло.

**Comment by Bunny67** [comment]
Что бы появился стандартный каст бар, отключи его в настройках елва(Рамки юнитов, Игрок, Полоса заклинаний)

**Comment by wenaern** [comment]
Скачал новую версию
И всё ещё не работает это

![wowscrnshot_111817_194155](https://user-images.githubusercontent.com/27071743/32982124-e7899adc-cc98-11e7-92cf-5c3dfafc5da3.jpg)
![wowscrnshot_111817_194241](https://user-images.githubusercontent.com/27071743/32982125-efd00f28-cc98-11e7-8d4c-f3139fc6ecf5.jpg)

**Comment by Bunny67** [comment]
Если в включить Игрока будет норм :D Щас как нить поправлю

**Comment by Bunny67** [comment]
Обнови еще и проверь

**Comment by wenaern** [comment]
Спасибо за фикс!
Всё работает <3

![wowscrnshot_111817_221733](https://user-images.githubusercontent.com/27071743/32983475-9423f908-ccae-11e7-8048-5c11d4e4a9fb.jpg)

**Comment by wenaern** [comment]
Только настоящее пати теперь работает так:
![wowscrnshot_111817_222841](https://user-images.githubusercontent.com/27071743/32983560-f7a96688-ccaf-11e7-8e37-cecda42e1331.jpg)

**Comment by Bunny67** [comment]
Близзард пати должно работать?

**Comment by Bunny67** [comment]
Если нет, то отключить в настройках елва Отключение фреймов Blizzard, поставь галку на Группа

**Comment by wenaern** [comment]
Близзард_пати быть не должно видно, если включены елв_пати
Можешь подсказать конкретнее в какой вкладке находится то что ты сказал %)
В скинах нет группы

**Comment by Bunny67** [comment]
![wowscrnshot_111817_214053](https://user-images.githubusercontent.com/5816685/32983663-2b9342fe-cca9-11e7-986a-03b53859f019.jpg)

**Comment by wenaern** [comment]
Оу, точно! Теперь не видно близзард_пати
Извини, не знал про эту настройку %)
Спасибо ещё раз, и за внимание в том числе)
