### ISSUE TITLE
Dots on target are grayed out

### ISSUE THREAD

**Issue by Chalapacho** [ElvUI-WotLK/ElvUI#429]
Since commit 531914b4c5ef68016df211c461473177de29ea2a (update oUF) my dots on my target are grayed out. I already tried resetting my ElvUI settings to default and disabling all my other addons, but still same issue. Am i missing a new setting i need to disable or something? Thanks for your help!

Screenshot attached
![wowscrnshot_082017_103737](https://user-images.githubusercontent.com/10513365/29493364-8002c032-8594-11e7-88b9-d4b76c544b4d.jpg)

**Comment by Lackschott** [comment]
So is there a solution ? I got the same and dont know how to fix this.
