### ISSUE TITLE
Add project-ascension suport

### ISSUE THREAD

**Issue by gamer4eg** [ElvUI-WotLK/ElvUI#432]
I apologize for machine translation ... =)
On the project-ascension.com server, the system of character classes has been completely redone. And the character is available mana, And rage, And energy.
Can you add the ability to display all of these resources at the same time on the player's bar?

**Comment by Apollyonn** [comment]
Ascension is a heavily modified custom server and it requires a lot of work for this addon to make it fully compatible. As far as i know its not going to happen anytime soon if ever.

**Comment by gamer4eg** [comment]
I'm not asking for full compatibility!
I would just like to add two bars for rage and energy into the player's frame ...

**Comment by Kkthnx** [comment]
Look at it this way, if they start making custom modifications for one server then everyone else is gonna want the same treatment. You can simply make a plugin handle this in theory if you wanted to do so. @gamer4eg That's that best you are gonna get.

**Comment by crumdidlyumshis** [comment]
Yeah this is something custom that is very specific to a very specific server. As @Kkthnx said, you can make an addon specific to your needs that can hook into the Unitframes. Sorry and good luck! 😉
