### ISSUE TITLE
24 hour clock isn't working

### ISSUE THREAD

**Issue by Aldwew** [ElvUI-WotLK/ElvUI#434]
Even toggled the clock stays in 12 hour mode

**Comment by crumdidlyumshis** [comment]
![wowscrnshot_110517_165539](https://user-images.githubusercontent.com/7307335/32420079-d4dd6b6e-c24a-11e7-89bc-0f09df36a750.jpg)

**Comment by Aldwew** [comment]
Have to check that out, thanks!
