### ISSUE TITLE
Nameplate buff filters

### ISSUE THREAD

**Issue by Tristan000** [ElvUI-WotLK/ElvUI#437]
I think there is something wrong with the nameplate buff/debuff filters.

In this screenshot i casted earth shield and whithout any filters, it shows.
![1](https://user-images.githubusercontent.com/20983405/31694827-24ca36b6-b3af-11e7-9dfc-0bc3c4cb56d5.jpg)
Here i choose the filter to block buffs whithout duration, but it blocks my earth shield that has duration.
![2](https://user-images.githubusercontent.com/20983405/31694843-49e416e2-b3af-11e7-8bd0-f4a87cf2b9d8.jpg)

In this screenshot i have 2 buffs on the target and whithout filters they show.
![3](https://user-images.githubusercontent.com/20983405/31694899-a1f1618c-b3af-11e7-9561-d97cc27d0808.jpg)
Here i choose the filter to block non personal buffs, but it blocks my buffs too.
![4](https://user-images.githubusercontent.com/20983405/31694921-bc797d0a-b3af-11e7-9e75-9e71f5aaa3fd.jpg)

Other filters are working fine, only problem is with blockNoDuration and blockNonPersonal.

**Comment by Bunny67** [comment]
They are used for whitelist filter
Place "blockNonPersonal" or “blockNoDuration“ filter first, then your whitelist filter after.

**Comment by Tristan000** [comment]
I see, thanks for answer.
