### ISSUE TITLE
Style filter scale conflict with threat scale

### ISSUE THREAD

**Issue by Tristan000** [ElvUI-WotLK/ElvUI#438]
I don't know if this works as intented but it seems that there is a conflict with threat scale and style filter scale.
First of all if i'm not mistaken, in order to disable the threat scaling, we have to set both Good and Bad scale at 100%.
![wowscrnshot_101817_132056](https://user-images.githubusercontent.com/20983405/31713965-bb152050-b408-11e7-94ad-262f078121f3.jpg)
Now at Style filters i set the scale to be at max.
![wowscrnshot_101817_132103](https://user-images.githubusercontent.com/20983405/31713966-bb492864-b408-11e7-9753-093e1f0a900d.jpg)
When someone gets threat from the boss, the nameplate scales back to normal and it ignores style filter scale. I don't know if this is correct but shouldn't count style filter scale as base scale and then add the threat scale?

![wowscrnshot_101817_132129](https://user-images.githubusercontent.com/20983405/31713967-bb6d028e-b408-11e7-963f-b9dbd789d346.jpg)

**Comment by Bunny67** [comment]
Check
