### ISSUE TITLE
Style filter scale sometimes not working

### ISSUE THREAD

**Issue by Tristan000** [ElvUI-WotLK/ElvUI#439]
It seems that there is another problem with style filter scale. Sometimes when the nameplate appears the scale is the default one, instead of the style filter.
https://i.imgur.com/f6ka5hD.gifv

i don't know if it helps but these are my scale settings.
![wowscrnshot_101917_190323](https://user-images.githubusercontent.com/20983405/31781518-4fca0b5e-b501-11e7-84ce-5fc6ba967ea7.jpg)
![wowscrnshot_101917_190318](https://user-images.githubusercontent.com/20983405/31781519-4ff4eacc-b501-11e7-80d2-cc0e6afa4128.jpg)
![wowscrnshot_101917_190312](https://user-images.githubusercontent.com/20983405/31781528-560dd57c-b501-11e7-9271-57a2416419b9.jpg)

**Comment by Bunny67** [comment]
https://github.com/ElvUI-WotLK/ElvUI/commit/24db58d5407dbd07742b380a7ebcbe8e84ce58ef  installed?

**Comment by Tristan000** [comment]
Yes

**Comment by Bunny67** [comment]
I can not reproduce :(

**Comment by Tristan000** [comment]
I think it happens only if you show/hide the same nameplate too many times.

**Comment by Bunny67** [comment]
https://imgur.com/f6Ujh8A

**Comment by Tristan000** [comment]
Did you try it with the same settings as i have? I deleted everything and i made a new instalation of elvui with new profile and it still happens.
https://i.gyazo.com/400d5195720797f235a54c40f1721fb7.mp4 :(

**Comment by Tristan000** [comment]
Ok i think this happens only if you disable "Use target Scale"

**Comment by Bunny67** [comment]
I reproduced the bug. How to be free, I will correct :)

**Comment by Bunny67** [comment]
check now
