### ISSUE TITLE
Unitframe aura timer

### ISSUE THREAD

**Issue by LiNK2088** [ElvUI-WotLK/ElvUI#44]
Could you make an options to modify or hide the timers on the unitframes buffs/debuffs pls

**Comment by crumdidlyumshis** [comment]
Possible to add or close?

**Comment by crumdidlyumshis** [comment]
I think this is added? Aura Bars? Close?

**Comment by Bunny67** [comment]
Such a possibility has appeared in https://github.com/ElvUI-WotLK/ElvUI_CustomTweaks
