### ISSUE TITLE
Tooltip disappearing randomly (doesn't happen with other tooltip mods)

### ISSUE THREAD

**Issue by jonomurphy** [ElvUI-WotLK/ElvUI#444]
Some strange reason, my elvui tooltip will randomly disappear on occasion. I tested other tooltip mods to see if it was the game, but they always worked.

**Comment by Apollyonn** [comment]
Try latest update.

**Comment by jonomurphy** [comment]
Still disappears

**Comment by Bunny67** [comment]
where does it disappear?

**Comment by jonomurphy** [comment]
Essentially whenever I get into combat, it will randomly just go away and not come back. I'll reproduce it on YT.

**Comment by jonomurphy** [comment]
Please find YT footage attached showcasing the issue I'm having. As you can see, it seems to occur after combat state, and doesn't come back.

https://www.youtube.com/watch?v=rCpDs2JPYnE&feature=youtu.be

**Comment by crumdidlyumshis** [comment]
Can you list all the addons you have installed? This is definitely strange.

**Comment by jonomurphy** [comment]
Sure. I have another tooltip addon called tiptac, but of course it is always disabled when I try to use the elvui variant. 

https://imgur.com/a/P3Uxn - shows addons
