### ISSUE TITLE
Paladin buffs do not show up on UnitFrames

### ISSUE THREAD

**Issue by 3majed** [ElvUI-WotLK/ElvUI#446]
If you click on any target or even if you see your player UnitFrame it shows all buffs without paladins. I don't know if its only me or you have the same thing but it was working before

**Comment by 3majed** [comment]
since no one answer, or fix this - found old copy of elvui and it works great without buffs/ nameplates issue (when you switch to tank and still red even when you have aggro) 
[ElvUI-master (1).zip](https://github.com/ElvUI-WotLK/ElvUI/files/1463757/ElvUI-master.1.zip) this was downloaded from here Aug 4th

**Comment by Bunny67** [comment]
Set Maximum Duration Buff/Debuff to 1800 for a specific unit. Default by 300
