### ISSUE TITLE
Aura bars 

### ISSUE THREAD

**Issue by Dettlaf** [ElvUI-WotLK/ElvUI#449]
Aura Bars doesn't have xOffset, and i want to put them in the middle so i attach them to Debuffs and that is partially what i want, only problem is they are not horizontaly in the centar.
![wowscrnshot_111617_211948](https://user-images.githubusercontent.com/30580010/32913875-f762ddbe-cb13-11e7-9a80-cb6f72ba9b4c.jpg)

**Comment by Bunny67** [comment]
https://www.curseforge.com/wow/addons/elvui-aurabars-movers

**Comment by Bunny67** [comment]
is supported

**Comment by Dettlaf** [comment]
It worked, thanks a lot!
