### ISSUE TITLE
Stats showing after closing character status

### ISSUE THREAD

**Issue by leolulz** [ElvUI-WotLK/ElvUI#451]
Running the latest commit from today.

When you login it looks like this
![wowscrnshot_111817_152047](https://user-images.githubusercontent.com/16959456/32981287-ddf2c09e-cc74-11e7-96b0-0eb0d6ea2ffb.jpg)

Once you open the character status pane it looks like this
![wowscrnshot_111817_151810](https://user-images.githubusercontent.com/16959456/32981279-bc39c790-cc74-11e7-94b2-61013992c3b1.jpg)

When you close the character status pane it looks like this
![wowscrnshot_111817_151809](https://user-images.githubusercontent.com/16959456/32981289-e224a6a0-cc74-11e7-9404-d13d026eefe4.jpg)

You can solve it by reloading the ui, tho the stats appear as soon as you open the character status pane again

**Comment by Bunny67** [comment]
Install GS for 3.3.5

**Comment by leolulz** [comment]
I had GearScore3.1.20b that i think is the last 3.3.5 release?
Anyhow i got GearScoreLite (http://www.wowinterface.com/downloads/info14865-GearScoreLite.html#info) and now it works.

**Comment by Bunny67** [comment]
3.1.17 WotLK
