### ISSUE TITLE
Проблема с отображением баффов/дебаффов

### ISSUE THREAD

**Issue by Vitoshka** [ElvUI-WotLK/ElvUI#454]
Первый вопрос, можно ли сделать **раздельное независимое** включение баффов/дебаффов из вкладки **а)** ElvUI (баффы/дебаффы)  и вкладки **b)** ElvUI юнитфреймы(игрок/баффы/дебаффы) что бы не было дублирования, но в тоже время можно было комбинировать, к примеру, ставить отображение  баффов игрока **a)**, справа вверху, а дебаффы включить в пункте **b)** над юнитфреймом игрока и наоборот, а то получается можно только отключить или же чтобы было дублирование.

пример неправильного дублирования: http://s018.radikal.ru/i513/1711/db/cf177ce66add.jpg

Второй вопрос, можно ли сделать выбор размера шрифта и выбора самого шрифта текста для кастбара игрока/цели/цель цели/фокуса/питомца?

Спасибо за помощь.

**Comment by Bunny67** [comment]
1-го к сожалению не будет.
2-е стало доступно в https://github.com/ElvUI-WotLK/ElvUI_CustomTweaks
