### ISSUE TITLE
World map and interface disappering when mouseover questlog

### ISSUE THREAD

**Issue by Chaoticx** [ElvUI-WotLK/ElvUI#455]
First of all, when on a world map, there is no border/background for quest objectives : https://i.imgur.com/ijG4rnE.jpg
Second, when you move and open world map to look for a quest, when you mouseover another quest on the  right, or try to mouseover a reward item, the whole interface desappers: 
https://i.imgur.com/3kKzp7E.jpg , https://i.imgur.com/vkf6cLn.jpg

**Comment by Frenlock** [comment]
hmmm can't confirm ...
![wowscrnshot_112117_191950](https://user-images.githubusercontent.com/24683355/33086687-0d524944-cef1-11e7-9105-970faa27c666.jpg)

**Comment by crumdidlyumshis** [comment]
What addons are you using?

**Comment by Chaoticx** [comment]
Disabled all addons to check if it is the cause, same thing happened. It has something to do with map transperency while moving. Also tried another version of elvui, and everything was fine,

**Comment by Chaoticx** [comment]
Working fine now, thanks
