### ISSUE TITLE
Recount title font keeps resetting

### ISSUE THREAD

**Issue by jonomurphy** [ElvUI-WotLK/ElvUI#457]
not a huge issue, but whenever I log in, the recount title font [So the thing that says 'Damage/DPS'] is always a different font to that which I assign it.

It is weird because when i go into config, the font I want IS picked, but i have to pick it again for it to work.

Nothing big, just thought i would mention!

**Comment by Bunny67** [comment]
fixed in https://github.com/ElvUI-WotLK/ElvUI_AddOnSkins
