### ISSUE TITLE
XP bar

### ISSUE THREAD

**Issue by Frenlock** [ElvUI-WotLK/ElvUI#458]
Sometimes the experience bar show wrong visual percentage (but the mouseover text its ok) .
Update : It happened when I left a battleground (warsong gulch) .
![wowscrnshot_112317_231238](https://user-images.githubusercontent.com/24683355/33188668-4dc88178-d0a4-11e7-9bca-9751a0e907a3.jpg)

**Comment by Bunny67** [comment]
If the error is repeated, please select the text format for the XP bar and check whether it will display correctly

**Comment by Frenlock** [comment]
Yea I tested the ,,current,, text format and now the bar show correctly , I think the problem appear when its set to none .
