### ISSUE TITLE
Новые ошибки в UI

### ISSUE THREAD

**Issue by Vitoshka** [ElvUI-WotLK/ElvUI#459]
## Мною были замечены следующие конфликтные и не конфликтные ошибки

**1)**
```
1x GearScoreLite-3.1.15\GearScoreLite.lua:47: attempt to perform arithmetic on local 'ItemLevel' (a nil value)
ElvUI_Enhanced-1.02\Modules\Misc\characterFrame.lua:550: in function `ItemLevel'
ElvUI_Enhanced-1.02\Modules\Misc\characterFrame.lua:111: in function `updateFunc'
ElvUI_Enhanced-1.02\Modules\Misc\characterFrame.lua:958: in function `PaperDollFrame_UpdateStatCategory'
ElvUI_Enhanced-1.02\Modules\Misc\characterFrame.lua:1005: in function `PaperDollFrame_UpdateStats'
ElvUI_Enhanced-1.02\Modules\Misc\characterFrame.lua:1104: in function `PaperDoll_InitStatCategories'
ElvUI_Enhanced-1.02\Modules\Misc\characterFrame.lua:1974: in function `Initialize'
ElvUI_Enhanced-1.02\Modules\Misc\characterFrame.lua:2170: in function <...ddOns\ElvUI_Enhanced\Modules\Misc\characterFrame.lua:2169>
CallbackHandler-1.0-6:155: in function <...ibraries\CallbackHandler-1.0\CallbackHandler-1.0.lua:155>
<string>:"safecall Dispatcher[1]":4: in function <[string "safecall Dispatcher[1]"]:4>
<in C code>: ?
<string>:"safecall Dispatcher[1]":13: in function `?'
CallbackHandler-1.0-6:90: in function `Fire'
ElvUI-5.36\core\core.lua:1064: in function `InitializeModules'
ElvUI-5.36\core\core.lua:1184: in function `Initialize'
ElvUI-5.36\init.lua:131: in function <ElvUI\init.lua:130>
```
**2)**

В дополнение к этой ошибке. периодически не отображается (иногда даже с многочисленным логаутом) вот эта панель при входе в игру, с включённым аддоном gearscore lite и без него

http://s61.radikal.ru/i174/1711/0c/a62a11be45db.jpg
http://i075.radikal.ru/1711/cb/409dd0e60e53.jpg

**3)**
```
1x ...aks\categories\unitframes\UnitframeSpacingLimits.lua:7: attempt to index field 'general' (a nil value):
ElvUI_CustomTweaks-1.30\core.lua:246: in function `callback'
LibElvUIPlugin-1.0-13:91: in function <...\Libraries\LibElvUIPlugin-1.0\LibElvUIPlugin-1.0.lua:87>
<in C code>: ?
<in C code>: in function `LoadAddOn'
ElvUI-5.36\init.lua:195: in function `ToggleConfig'
ElvUI-5.36\init.lua:99: in function <ElvUI\init.lua:98>

Locals:
self = nil
n = 6
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
 CastbarFont = <function> @ ElvUI_CustomTweaks\categories\unitframes\CastbarFont.lua:90:
 BagsTextFormat = <function> @ ElvUI_CustomTweaks\categories\datatexts\BagsTextFormat.lua:20:
 ClickThroughActionBars = <function> @ ElvUI_CustomTweaks\categories\actionbars\ClickThroughActionBars.lua:31:
 PushedColor = <function> @ ElvUI_CustomTweaks\categories\actionbars\PushedColor.lua:21:
 AuraIconSpacing = <function> @ ElvUI_CustomTweaks\categories\unitframes\AuraIconSpacing.lua:34:
 UnitFrameSpacingLimits = <function> @ ElvUI_CustomTweaks\categories\unitframes\UnitframeSpacingLimits.lua:6:
 PowerBarTexture = <function> @ ElvUI_CustomTweaks\categories\unitframes\PowerBarTexture.lua:24:
 BagButtons = <function> @ ElvUI_CustomTweaks\categories\bags\BagButtons.lua:25:
 CastbarCustomBackdrop = <function> @ ElvUI_CustomTweaks\categories\unitframes\CastbarCustomBackdrop.lua:17:
 CastbarText = <function> @ ElvUI_CustomTweaks\categories\unitframes\CastbarText.lua:108:
 MinimapSizeLimits = <function> @ ElvUI_CustomTweaks\categories\minimap\MinimapSizeLimits.lua:6:
 ChatMaxLines = <function> @ ElvUI_CustomTweaks\categories\chat\MaxLines.lua:19:
 AuraIconText = <function> @ ElvUI_CustomTweaks\categories\unitframes\AuraIconText.lua:23:
 RaidControl = <function> @ ElvUI_CustomTweaks\categories\misc\RaidControl.lua:19:
}
(for control) = "UnitFrameSpacingLimits"
_ = "UnitFrameSpacingLimits"
func = <function> @ ElvUI_CustomTweaks\categories\unitframes\UnitframeSpacingLimits.lua:6:
E = <table> {
 GetTimeInfo = <function> @ ElvUI\core\math.lua:305:
 Bags = <table> {}
 privateVars = <table> {}
 modules = <table> {}
 CancelTimer = <function> @ ElvUI\Libraries\AceTimer-3.0\AceTimer-3.0.lua:161:
 FormatMoney = <function> @ ElvUI\core\math.lua:331:
 ExitVehicleShowFrames = <function> @ ElvUI\core\core.lua:914:
 StaticPopup_EscapePressed = <function> @ ElvUI\core\staticpopups.lua:437:
 CopyTable = <function> @ ElvUI\core\core.lua:551:
 DispelClasses = <table> {}
 SetMoversPositions = <function> @ ElvUI\core\movers.lua:457:
 ScheduleTimer = <function> @ ElvUI\Libraries\AceTimer-3.0\AceTimer-3.0.lua:108:
 PriestColors = <table> {}
 RegisterModule = <function> @ ElvUI\core\core.lua:983:
 SetupTheme = <function> @ ElvUI\core\install.lua:194:
 media = <table> {}
 SetUpAnimGroup = <function> @ ElvUI\core\animation.lua:6:
 bags = <table> {}
 data = <table> {}
 Role = "Melee"
 UIScale = <function> @ ElvUI\core\pixelperfect.lua:12:
 db = <table> {}
 ToggleConfigMode = <function> @ ElvUI\core\config.lua:54:
 SetEnabledState = <function> @ ElvUI\Libraries\AceAddon-3.0\AceAddon-3.0.lua:455:
 Hook = <function> @ ElvUI\Libraries\AceHook-3.0\AceHook-3.0.lua:274:
 Options = <table> {}
 Layout = <table> {}
 tDeleteItem = <function> @ ElvUI\core\animation.lua:281:
 LoadCommands = <function> @ ElvUI\core\commands.lua:143:
 StringSplitMultiDelim = <function> @ ElvUI\core\core.lua:741:
 HiddenFrame = <unnamed> {}
 DisableAddon = <function> @ ElvUI\core\commands.lua:28:
 UnregisterAllEvents = <function> @ BugSack\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:202:
 diffGetRight = 0
 UIFrameFade = <function> @ ElvUI\core\animation.lua:220:
 MinimapWidt
```

**4)**
```
49x AceConfigDialog-3.0-50:1630: attempt to call method 'IsVisible' (a nil value)

Locals:
```

**5)**

Также возникает баг с отображением панели спелов пета, при перезагрузке интерфейса ElvUI, при входе в Инст, перемещении среди континентами, телепортом. В данной ситуации, помогает логаут, причём иногда бывает необходим многократный.** 

http://s016.radikal.ru/i334/1711/2d/c0b46ce1093e.jpg

**6)**
```
1x Gatherer-Astrolabe-0.4\Swag\LibSwag.lua:407: Usage: GameTooltip:SetText("text" [, color])
Gatherer-Astrolabe-0.4\Swag\LibSwag.lua:407: in function <Gatherer\Swag\LibSwag.lua:403>
QuestHelper-1.4.1\collect.lua:26: in function `SetText'
ElvUI_Enhanced-1.02\Modules\Misc\characterFrame.lua:1663: in function <...ddOns\ElvUI_Enhanced\Modules\Misc\characterFrame.lua:1660>
ElvUI_Enhanced-1.02\Modules\Misc\characterFrame.lua:1656: in function <...ddOns\ElvUI_Enhanced\Modules\Misc\characterFrame.lua:1645>
Locals:
this = GameTooltip {
 0 = <userdata>
 numMoneyFrames = 2
 comparing = false
 SetText = <function> @ QuestHelper\collect.lua:24:
 SetInboxItem = <function> defined =[C]:-1
 template = "Transparent"
 shoppingTooltips = <table> {}
 SetQuestLogItem = <function> defined =[C]:-1
 SetGuildBankItem = <function> defined =[C]:-1
 SetTradeTargetItem = <function> defined =[C]:-1
 SetHyperlink = <function> defined =[C]:-1
 SetTradePlayerItem = <function> defined =[C]:-1
 Hide = <function> defined =[C]:-1
 SetSendMailItem = <function> defined =[C]:-1
 SetUnitBuff = <function> defined =[C]:-1
 updateTooltip = 0.15999999716878
 SetInventoryItem = <function> defined =[C]:-1
 hasMoney = 1
 ClearLines = <function> @ Gatherer\Swag\LibSwag.lua:412:
 SetLootRollItem = <function> defined =[C]:-1
 SetUnitAura = <function> defined =[C]:-1
 ignoreUpdates = true
 SetAuctionSellItem = <function> defined =[C]:-1
 SetBagItem = <function> defined =[C]:-1
 SetUnitDebuff = <function> defined =[C]:-1
 SetTradeSkillItem = <function> defined =[C]:-1
 SetLootItem = <function> defined =[C]:-1
 SetQuestItem = <function> defined =[C]:-1
 SetAuctionItem = <function> defined =[C]:-1
}
line = 11
```

**7)**
```
1x Gatherer-Astrolabe-0.4\Swag\LibSwag.lua:407: Usage: GameTooltip:SetText("text" [, color])
Gatherer-Astrolabe-0.4\Swag\LibSwag.lua:407: in function <Gatherer\Swag\LibSwag.lua:403>
QuestHelper-1.4.1\collect.lua:26: in function `SetText'
ElvUI_Enhanced-1.02\Modules\Misc\characterFrame.lua:1665: in function <...ddOns\ElvUI_Enhanced\Modules\Misc\characterFrame.lua:1660>

Locals:
this = GameTooltip {
 0 = <userdata>
 numMoneyFrames = 2
 comparing = false
 SetText = <function> @ QuestHelper\collect.lua:24:
 SetInboxItem = <function> defined =[C]:-1
 template = "Transparent"
 shoppingTooltips = <table> {}
 SetQuestLogItem = <function> defined =[C]:-1
 SetGuildBankItem = <function> defined =[C]:-1
 SetTradeTargetItem = <function> defined =[C]:-1
 SetHyperlink = <function> defined =[C]:-1
 SetTradePlayerItem = <function> defined =[C]:-1
 Hide = <function> defined =[C]:-1
 SetSendMailItem = <function> defined =[C]:-1
 SetUnitBuff = <function> defined =[C]:-1
 updateTooltip = 0.023999993503094
 SetInventoryItem = <function> defined =[C]:-1
 hasMoney = 1
 ClearLines = <function> @ Gatherer\Swag\LibSwag.lua:412:
 SetLootRollItem = <function> defined =[C]:-1
 SetUnitAura = <function> defined =[C]:-1
 ignoreUpdates = true
 SetAuctionSellItem = <function> defined =[C]:-1
 SetBagItem = <function> defined =[C]:-1
 SetUnitDebuff = <function> defined =[C]:-1
 SetTradeSkillItem = <function> defined =[C]:-1
 SetLootItem = <function> defined =[C]:-1
 SetQuestItem = <function> defined =[C]:-1
 SetAuctionItem = <function> defined =[C]:-1
}
line = 10
```

**8)**
```
1x AIO_Client\index.lua:56: bad argument #2 to 'tonumber' (number expected, got string)
AIO_Client\index.lua:56: in function `GetInventoryItemLink'
ElvUI_Enhanced-1.02\Modules\Misc\characterFrame.lua:476: in function <...ddOns\ElvUI_Enhanced\Modules\Misc\characterFrame.lua:453>
ElvUI_Enhanced-1.02\Modules\Misc\characterFrame.lua:555: in function `ItemLevel'
ElvUI_Enhanced-1.02\Modules\Misc\characterFrame.lua:111: in function `updateFunc'
ElvUI_Enhanced-1.02\Modules\Misc\characterFrame.lua:958: in function `PaperDollFrame_UpdateStatCategory'
ElvUI_Enhanced-1.02\Modules\Misc\characterFrame.lua:1005: in function `PaperDollFrame_UpdateStats'
ElvUI_Enhanced-1.02\Modules\Misc\characterFrame.lua:1104: in function `PaperDoll_InitStatCategories'
ElvUI_Enhanced-1.02\Modules\Misc\characterFrame.lua:1974: in function `Initialize'
ElvUI_Enhanced-1.02\Modules\Misc\characterFrame.lua:2170: in function <...ddOns\ElvUI_Enhanced\Modules\Misc\characterFrame.lua:2169>
CallbackHandler-1.0-6:155: in function <...ibraries\CallbackHandler-1.0\CallbackHandler-1.0.lua:155>
<string>:"safecall Dispatcher[1]":4: in function <[string "safecall Dispatcher[1]"]:4>
<in C code>: ?
<string>:"safecall Dispatcher[1]":13: in function `?'
CallbackHandler-1.0-6:90: in function `Fire'
ElvUI-5.36\core\core.lua:1064: in function `InitializeModules'
ElvUI-5.36\core\core.lua:1184: in function `Initialize'
ElvUI-5.36\init.lua:131: in function <ElvUI\init.lua:130>
```

**Comment by Bunny67** [comment]
1, 2, 3, 6, 7, 8 поправил, обнови [ElvUI_CustomTweaks ](https://github.com/ElvUI-WotLK/ElvUI_CustomTweaks) и [ElvUI_Enhanced](https://github.com/ElvUI-WotLK/ElvUI_Enhanced)
5 серверная ошибка
4 Если стоит отдельный Ace3 попробуй отключить его и проверить

**Comment by Vitoshka** [comment]
Отдельный Ace3 не стоит, ошибка достаточно редкая, но бывает.

**Comment by Bunny67** [comment]
Ошибка точно не в ElvUI, скорее всего другого аддона, который использует Ace3. Найди аддоны которые используют Ace3 и попробуй найти более свежие версии для лича

**Comment by Vitoshka** [comment]
Обновил ElvUI_CustomTweaks и ElvUI_Enhanced при входе в игру появилась 1 ошибка

1x AIO_Client\index.lua:56: bad argument #2 to 'tonumber' (number expected, got string)
AIO_Client\index.lua:56: in function `GetInventoryItemLink'
ElvUI_Enhanced-1.02\Modules\Misc\characterFrame.lua:476: in function <...ddOns\ElvUI_Enhanced\Modules\Misc\characterFrame.lua:453>
ElvUI_Enhanced-1.02\Modules\Misc\characterFrame.lua:553: in function `ItemLevel'
ElvUI_Enhanced-1.02\Modules\Misc\characterFrame.lua:111: in function `updateFunc'
ElvUI_Enhanced-1.02\Modules\Misc\characterFrame.lua:956: in function `PaperDollFrame_UpdateStatCategory'
ElvUI_Enhanced-1.02\Modules\Misc\characterFrame.lua:1003: in function `PaperDollFrame_UpdateStats'
ElvUI_Enhanced-1.02\Modules\Misc\characterFrame.lua:1102: in function `PaperDoll_InitStatCategories'
ElvUI_Enhanced-1.02\Modules\Misc\characterFrame.lua:1972: in function `Initialize'
ElvUI_Enhanced-1.02\Modules\Misc\characterFrame.lua:2168: in function <...ddOns\ElvUI_Enhanced\Modules\Misc\characterFrame.lua:2167>
CallbackHandler-1.0-6:155: in function <...ibraries\CallbackHandler-1.0\CallbackHandler-1.0.lua:155>
<string>:"safecall Dispatcher[1]":4: in function <[string "safecall Dispatcher[1]"]:4>
<in C code>: ?
<string>:"safecall Dispatcher[1]":13: in function `?'
CallbackHandler-1.0-6:90: in function `Fire'
ElvUI-5.36\core\core.lua:1064: in function `InitializeModules'
ElvUI-5.36\core\core.lua:1184: in function `Initialize'
ElvUI-5.36\init.lua:131: in function <ElvUI\init.lua:130>

**Comment by Bunny67** [comment]
Можешь залить AIO_Client и все что с ним связано

**Comment by Bunny67** [comment]
Если есть дискорд, то https://discord.gg/PYFgRUq. Можешь там его скинуть

**Comment by Vitoshka** [comment]
После всех исправлений словил ещё одну ошибку

1x ...ustomTweaks\categories\minimap\MinimapSizeLimits.lua:7: attempt to index field 'size' (a nil value):
ElvUI_CustomTweaks-1.30\core.lua:246: in function `callback'
LibElvUIPlugin-1.0-13:91: in function <...\Libraries\LibElvUIPlugin-1.0\LibElvUIPlugin-1.0.lua:87>
<in C code>: ?
<in C code>: in function `LoadAddOn'
ElvUI-5.36\init.lua:195: in function `ToggleConfig'
ElvUI-5.36\init.lua:99: in function <ElvUI\init.lua:98>

Locals:
self = nil
n = 6
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
 CastbarFont = <function> @ ElvUI_CustomTweaks\categories\unitframes\CastbarFont.lua:90:
 BagsTextFormat = <function> @ ElvUI_CustomTweaks\categories\datatexts\BagsTextFormat.lua:20:
 ClickThroughActionBars = <function> @ ElvUI_CustomTweaks\categories\actionbars\ClickThroughActionBars.lua:31:
 PushedColor = <function> @ ElvUI_CustomTweaks\categories\actionbars\PushedColor.lua:21:
 AuraIconSpacing = <function> @ ElvUI_CustomTweaks\categories\unitframes\AuraIconSpacing.lua:34:
 UnitFrameSpacingLimits = <function> @ ElvUI_CustomTweaks\categories\unitframes\UnitframeSpacingLimits.lua:6:
 PowerBarTexture = <function> @ ElvUI_CustomTweaks\categories\unitframes\PowerBarTexture.lua:24:
 BagButtons = <function> @ ElvUI_CustomTweaks\categories\bags\BagButtons.lua:25:
 CastbarCustomBackdrop = <function> @ ElvUI_CustomTweaks\categories\unitframes\CastbarCustomBackdrop.lua:17:
 CastbarText = <function> @ ElvUI_CustomTweaks\categories\unitframes\CastbarText.lua:108:
 MinimapSizeLimits = <function> @ ElvUI_CustomTweaks\categories\minimap\MinimapSizeLimits.lua:6:
 ChatMaxLines = <function> @ ElvUI_CustomTweaks\categories\chat\MaxLines.lua:19:
 AuraIconText = <function> @ ElvUI_CustomTweaks\categories\unitframes\AuraIconText.lua:23:
 RaidControl = <function> @ ElvUI_CustomTweaks\categories\misc\RaidControl.lua:19:
}
(for control) = "MinimapSizeLimits"
_ = "MinimapSizeLimits"
func = <function> @ ElvUI_CustomTweaks\categories\minimap\MinimapSizeLimits.lua:6:
E = <table> {
 GetTimeInfo = <function> @ ElvUI\core\math.lua:305:
 Bags = <table> {}
 privateVars = <table> {}
 modules = <table> {}
 CancelTimer = <function> @ ElvUI\Libraries\AceTimer-3.0\AceTimer-3.0.lua:161:
 FormatMoney = <function> @ ElvUI\core\math.lua:331:
 ExitVehicleShowFrames = <function> @ ElvUI\core\core.lua:914:
 StaticPopup_EscapePressed = <function> @ ElvUI\core\staticpopups.lua:437:
 CopyTable = <function> @ ElvUI\core\core.lua:551:
 DispelClasses = <table> {}
 SetMoversPositions = <function> @ ElvUI\core\movers.lua:457:
 ScheduleTimer = <function> @ ElvUI\Libraries\AceTimer-3.0\AceTimer-3.0.lua:108:
 PriestColors = <table> {}
 RegisterModule = <function> @ ElvUI\core\core.lua:983:
 SetupTheme = <function> @ ElvUI\core\install.lua:194:
 media = <table> {}
 SetUpAnimGroup = <function> @ ElvUI\core\animation.lua:6:
 bags = <table> {}
 data = <table> {}
 Role = "Melee"
 UIScale = <function> @ ElvUI\core\pixelperfect.lua:12:
 db = <table> {}
 ToggleConfigMode = <function> @ ElvUI\core\config.lua:54:
 SetEnabledState = <function> @ ElvUI\Libraries\AceAddon-3.0\AceAddon-3.0.lua:455:
 Hook = <function> @ ElvUI\Libraries\AceHook-3.0\AceHook-3.0.lua:274:
 Options = <table> {}
 Layout = <table> {}
 tDeleteItem = <function> @ ElvUI\core\animation.lua:281:
 LoadCommands = <function> @ ElvUI\core\commands.lua:143:
 StringSplitMultiDelim = <function> @ ElvUI\core\core.lua:741:
 HiddenFrame = <unnamed> {}
 DisableAddon = <function> @ ElvUI\core\commands.lua:28:
 UnregisterAllEvents = <function> @ BugSack\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:202:
 diffGetRight = 0
 UIFrameFade = <function> @ ElvUI\core\animation.lua:220:
 MinimapWidth = 145
 StaticPop
  ---

**Comment by Vitoshka** [comment]
Новая ошибка, исправьте по возможности пожалуйста.

1x AIO_Client\index.lua:82: attempt to concatenate a nil value
<in C code>: ?
<in C code>: ?
<in C code>: ?
<in C code>: ?
DBM-Core\DBM-Core.lua:950: in function <DBM-Core\DBM-Core.lua:948>
ElvUI-5.36\modules\chat\chat.lua:774: in function <ElvUI\modules\chat\chat.lua:764>
WIM-3.3.7\Sources\Hooks.lua:109: in function <WIM\Sources\Hooks.lua:102>
(tail call): ?:
(tail call): ?:
Interface\FrameXML\ItemRef.lua:183: in function <Interface\FrameXML\ItemRef.lua:2>:
Blizzard_CombatLog\Blizzard_CombatLog.lua:3616: in function <...ace\AddOns\Blizzard_CombatLog\Blizzard_CombatLog.lua:3560>
<in C code>: in function `SetItemRef'
DeathRecap.lua:342: in function <...lvUI_Enhanced\Modules\Blizzard\AddOns\DeathRecap.lua:336>
(tail call): ?:
(tail call): ?:
(tail call): ?:
Interface\FrameXML\ChatFrame.lua:3034: in function <Interface\FrameXML\ChatFrame.lua:3033>:
(tail call): ?:
<string>:"*:OnHyperlinkClick":1: in function <[string "*:OnHyperlinkClick"]:1>
(tail call): ?:
<in C code>: ?

Locals:
(*temporary) = <function> defined =[C]:-1
 = <function> defined *:OnTooltipSetItem:1
 = <function> @ AIO_Client\index.lua:75:

  ---

**Comment by Vitoshka** [comment]
Новая проблема с отображением на панели персонажа числового значения Gearscore, с последними патчами оно стало раздробленным (00,00 или бывает так 0,0 и 0,0 в одном окне, когда раньше было 1-м числом. В настройках ГС ничего не менял, у меня стоит https://wow.curseforge.com/projects/gearscorelite/files/427784 

как было:
http://s04.radikal.ru/i177/1711/ac/0440a6364a5b.jpg

как стало:
http://s018.radikal.ru/i526/1711/42/38633a485296.jpg

http://s002.radikal.ru/i198/1711/60/76effd1968f5.jpg

**Comment by Bunny67** [comment]
1. Возможно ошибка не елва, что делал до того как появилась?

2 Это показывает средний уровень предметов, скорее всего гс отключен

**Comment by Vitoshka** [comment]
1. При настройке елва, вот только что точно настраивал, не помню.
2. Переустановил GSLite, всё заработало.

**Comment by Bunny67** [comment]
Надо вспомнить :)

**Comment by Vitoshka** [comment]
Миникарту и то что с ней связано, включая Enhanced, а также юнитфреймы себя и цели, включая Enhanced.

**Comment by Vitoshka** [comment]
Ещё одна незначительная ошибка отображения: http://s018.radikal.ru/i521/1711/0c/a9ec5883964f.jpg

**Comment by Vitoshka** [comment]
Словил ещё одну ошибку, исправьте пожалуйста по возможности:

81x AIO_Client\index.lua:56: bad argument #2 to 'tonumber' (number expected, got string)
AIO_Client\index.lua:56: in function <AIO_Client\index.lua:52>
ElvUI-5.36\modules\tooltip\tooltip.lua:181: in function `GetItemLvL'
ElvUI-5.36\modules\tooltip\tooltip.lua:225: in function `?'
CallbackHandler-1.0-6:147: in function <...ack\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:147>
<string>:"safecall Dispatcher[1]":4: in function <[string "safecall Dispatcher[1]"]:4>
<in C code>: ?
<string>:"safecall Dispatcher[1]":13: in function `?'
CallbackHandler-1.0-6:92: in function `Fire'
AceEvent-3.0-4 (ElvUI):120: in function <...AddOns\ElvUI\Libraries\AceEvent-3.0\AceEvent-3.0.lua:119>

  ---

**Comment by Loaal** [comment]
Ошибки вызванны кодом AIO_Client, который находится внутри MPQ файла, требуемого для игры на сервере. Я отправлял им пару недель назад исправленную версию на рассмотрение.
