### ISSUE TITLE
Вопрос относительно настройки миникарты

### ISSUE THREAD

**Issue by Vitoshka** [ElvUI-WotLK/ElvUI#460]
Подскажите, что это за панель (выделена красным контуром), как её менять, что то в неё добавлять и можно ли её отключить, если, да то как в eng/rus версии?

http://s019.radikal.ru/i643/1711/63/2868715e93e9.jpg

Спасибо)

**Comment by Bunny67** [comment]
Показывает есть ли на тебе рейдовые баффы, ее можно отключить
