### ISSUE TITLE
World Map

### ISSUE THREAD

**Issue by Noob1e** [ElvUI-WotLK/ElvUI#463]
We can't move or change the camera angle (by clicking right/left mouse buttons) while the World Map is opened.  Is there a way to make it non-stable like this?

**Comment by Apollyonn** [comment]
Seems to be working fine. https://gyazo.com/2b3c6d6ae4f6eabdfcbe676ed062ec8d
Are you using any other addons that modify the world map?

**Comment by Noob1e** [comment]
Yea, it works fine if you're using the "smaller world map" option. But with the full-screen mode I'm not able to move. Is there a way to change size of "smaller world map"? Or a way to make the full-screen mode work like the small one?
