### ISSUE TITLE
Bags/Inventory

### ISSUE THREAD

**Issue by Noob1e** [ElvUI-WotLK/ElvUI#465]
Is it possible to categorize the items in our bags? Or can you make "Baggins" addon skin compatible with ElvUI?

https://postimg.org/image/9jk4advmd/

**Comment by crumdidlyumshis** [comment]
Unfortunately this is something not part of the retail ElvUI. But we can add a skin for the addon your requesting to make it free as part of ElvUI

**Comment by Noob1e** [comment]
Yes, it would be great if you can add skin for that addon. Should I create a new thread on AddonSkins section?

**Comment by Noob1e** [comment]
Don't need to this anymore. Using AdiBags (v1.1 Beta 7 works fine if anyone else interests - https://www.wowace.com/projects/adibags/files/452440)
