### ISSUE TITLE
Error in BG(?)

### ISSUE THREAD

**Issue by LNMaarten** [ElvUI-WotLK/ElvUI#466]
I get this error when I enter BG's it seems, not 100% sure if it's exclusive to BG's yet or just some popup:

Message: CollectionsMicroButton:SetPoint(): EJMicroButton is dependent on this
Time: 12/21/17 14:15:06
Count: 1
Stack: CollectionsMicroButton:SetPoint(): EJMicroButton is dependent on this
Interface\SharedXML\SharedBasicControls.lua:208: in function <Interface\SharedXML\SharedBasicControls.lua:207>
[C]: ?
[C]: ?
[C]: in function `SetPoint'
Interface\AddOns\ElvUI\core\toolkit.lua:80: in function `Point'
...terface\AddOns\ElvUI\Modules\actionbars\microbar.lua:103: in function `UpdateMicroPositionDimensions'
...terface\AddOns\ElvUI\Modules\actionbars\microbar.lua:131: in function <...terface\AddOns\ElvUI\Modules\actionbars\microbar.lua:128>
(tail call): ?
[C]: in function `UpdateMicroButtons'
...rface\AddOns\Blizzard_TalentUI\Blizzard_TalentUI.lua:364: in function <...rface\AddOns\Blizzard_TalentUI\Blizzard_TalentUI.lua:358>
[C]: in function `Show'
Interface\FrameXML\UIParent.lua:2456: in function `SetUIPanel'
Interface\FrameXML\UIParent.lua:2297: in function `ShowUIPanel'
Interface\FrameXML\UIParent.lua:2166: in function <Interface\FrameXML\UIParent.lua:2162>
[C]: in function `SetAttribute'
Interface\FrameXML\UIParent.lua:2950: in function <Interface\FrameXML\UIParent.lua:2938>
[C]: in function `ShowUIPanel'
...rface\AddOns\MoveAnything\Libs\!NoTaint\!NoTaint.lua:5: in function <...rface\AddOns\MoveAnything\Libs\!NoTaint\!NoTaint.lua:3>
[C]: in function `PlayerTalentFrame_Toggle'
Interface\FrameXML\UIParent.lua:694: in function `ToggleTalentFrame'
Interface\FrameXML\MainMenuBarMicroButtons.lua:465: in function <Interface\FrameXML\MainMenuBarMicroButtons.lua:464>

Locals: errorMessage = "CollectionsMicroButton:SetPoint(): EJMicroButton is dependent on this"
DisplayMessageInternal = <function> defined @Interface\SharedXML\SharedBasicControls.lua:191
MESSAGE_TYPE_ERROR = 0

**Comment by Bunny67** [comment]
You play on Legion?

**Comment by LNMaarten** [comment]
Yea I just saw I posted it on the WOTLK addon... can I move it or do I need to create a new issue?

**Comment by Bunny67** [comment]
https://git.tukui.org/elvui/elvui/issues this ElvUI for Legion
