### ISSUE TITLE
Style filter Interuptible/Non-Interupt Bug

### ISSUE THREAD

**Issue by Tristan000** [ElvUI-WotLK/ElvUI#473]
**Description**
At Style filter when you select "Interuptible" or "Non-Interuptible" and the target is casting an interuptible spell, the nameplate gets styled but when the target stops casting the nameplate doesn not change back. You have to re target it to fix it.
![wowscrnshot_011018_020401](https://user-images.githubusercontent.com/20983405/34750345-4f97452c-f5af-11e7-8229-6bd6b4765842.jpg)
![wowscrnshot_011018_020430](https://user-images.githubusercontent.com/20983405/34750350-547bf704-f5af-11e7-9085-205691b11247.jpg)
![wowscrnshot_011018_020432](https://user-images.githubusercontent.com/20983405/34750353-56c2dd5c-f5af-11e7-8f25-11fce2fee2ef.jpg)

**Version Number**
5.40

**Comment by Bunny67** [comment]
fixed
