### ISSUE TITLE
Style Filter Buffs/ Debuffs Bug

### ISSUE THREAD

**Issue by Tristan000** [ElvUI-WotLK/ElvUI#474]
**Description**
When you put a buff or debuff to style filter and you apply the debuff, the nameplate does not change as expected. You have to retarget the nameplate in order to apply the style filter. Also if the buff/debuff expires the nameplate does not change back, again you have to retarget in order to fix it.
![wowscrnshot_011018_024813](https://user-images.githubusercontent.com/20983405/34750712-481f3186-f5b1-11e7-859a-650822c398ab.jpg)
![wowscrnshot_011018_024928](https://user-images.githubusercontent.com/20983405/34750713-4a0a6470-f5b1-11e7-8eb7-7b53298d68ff.jpg)
![wowscrnshot_011018_024934](https://user-images.githubusercontent.com/20983405/34750717-4bde2d18-f5b1-11e7-87f7-0eb7ee09852a.jpg)
![wowscrnshot_011018_025115](https://user-images.githubusercontent.com/20983405/34750718-4d9e108c-f5b1-11e7-88df-28cbf27017d0.jpg)

**Version Number**
5.40

**Comment by Bunny67** [comment]
Check now
