### ISSUE TITLE
[Plugins] Deadlinks

### ISSUE THREAD

**Issue by snwflake** [ElvUI-WotLK/ElvUI#475]
**Description**
Links to some plugins return 404

https://github.com/ElvUI-Wotlk/ElvUI_AuraBarsMovers
https://github.com/ElvUI-Wotlk/ElvUI_BagControl
https://github.com/ElvUI-Wotlk/ElvUI_DataTextColors

**Comment by Crumdidlyumshis** [comment]
I will correct this tomorrow. AuraBarsMovers, BagControl, and DataTextColors will need to be added. RightClick is no longer a plug-in as it is now a functionality within the ElvUI addon itself.

**Comment by Crumdidlyumshis** [comment]
Fixed. Check repo again :)

**Comment by snwflake** [comment]
👍
