### ISSUE TITLE
Error: Profile Import

### ISSUE THREAD

**Issue by Noob1e** [ElvUI-WotLK/ElvUI#480]
**Description**
When I try to import a profile, I get some errors

```
Interface\AddOns\ElvUI_AddOnSkins\Modules\Embed.lua:33: attempt to index field '?' (a nil value) 
Interface\AddOns\ElvUI_AddOnSkins\Modules\Embed.lua:27: attempt to index field '?' (a nil value) 
Interface\AddOns\ElvUI_AddOnSkins\Modules\Embed.lua:216: attempt to perform arithmetic on field 'leftWindowWidth' (a nil value)
```

**Version Number**
5.40

**Comment by Loaal** [comment]
Some variable names was changed.
Best solution will be to reload UI (it will fix wrong changed variables) and after that re-export your profile to prevent same error next time.
