### ISSUE TITLE
It says font not set 

### ISSUE THREAD

**Issue by gcoder1991** [ElvUI-WotLK/ElvUI#482]
this is the my fonts
![qq 20180131011255](https://user-images.githubusercontent.com/25083861/35580407-ebc38c6a-0623-11e8-87b1-cd42e84e3764.png)

this is the error
![image](https://user-images.githubusercontent.com/25083861/35580353-bcc82970-0623-11e8-928f-21d9bd0dba3b.png)

just installed and login , i see the errors, they all says that font not set, what can i do?
its zh_cn client

**Comment by Crumdidlyumshis** [comment]
I’m honestly not sure, not at computer. But could be a corrupted font file? Just a thought.

**Comment by gcoder1991** [comment]
i used the addon Tukui befor, its also says the error "font not set", and then i make the font dir, the error 

disappeared.

I found the evlui yesterday, and try it, so the error you see, i dont think the font file is corrupt. becousue is ok for tukui, version 11.5. 

what can i do to fix this bug？thx for your reply

**Comment by gcoder1991** [comment]
i know what's wrong with it, the addon use 
        SML_MT_font["伤害数字"]		= [[Fonts\ARKai_DB.ttf]]
	SML_MT_font["默认"]			= [[Fonts\ARKai_T.ttf]]
	SML_MT_font["聊天"]			= [[Fonts\ARHei.ttf]]
and there not have .ttf named them in my fonts file
