### ISSUE TITLE
Map bug and druid unit frame bug

### ISSUE THREAD

**Issue by RandomDudoo** [ElvUI-WotLK/ElvUI#484]
**Description**
Sometimes quests marker on map working is wrong.  Not sure how correctly explain this, there is screenshots:

That how it looks when im not move.

![wowscrnshot_020318_234726](https://user-images.githubusercontent.com/33762074/35768838-0896cd36-093d-11e8-8a0e-a0d9355bf1a3.jpg)

These when im do some movement. 

![wowscrnshot_020318_234732](https://user-images.githubusercontent.com/33762074/35768856-29779ff8-093d-11e8-8f5e-4d1b9c7bad0f.jpg)

As can you see markers shows only when i do some movement;

And about druid frame. Mostly times ( 90%> ) i don't see my mana bar (look at screenshots). 
/reloadui doesn't fix map and druid mana bar issue. Only restart the game is help.

**Version Number**
Version: 5.40 according ElvUI.toc

**Steps to Reproduce**
No idea. But its seems to me that is happens when i teleporting. Kalimdor > EK. or just TP in dungeon.

**Comment by Apollyonn** [comment]
I don't understand the problem with world map. If you mean the world map fades when you move, you can change it in the settings.

**Comment by RandomDudoo** [comment]
It was about quests markers. It shows (blue glow) only when i moving. But that bug happens rarely. And i  don't really care about it.
And now about changes that you made. Bug still here. Bug i just get used to it.
Energy instead of mana, that new never see that bug before.
![wowscrnshot_020618_063759](https://user-images.githubusercontent.com/33762074/35834308-23bfd81c-0b10-11e8-9949-043875f0b128.jpg)
Energy text, that new too.
![wowscrnshot_020618_063808](https://user-images.githubusercontent.com/33762074/35834367-601177da-0b10-11e8-8724-80e3d6b4e0e3.jpg)
After 5 sec or so. Its almost ok.
![wowscrnshot_020618_063816](https://user-images.githubusercontent.com/33762074/35834419-9f7c7eec-0b10-11e8-8067-5d03da0786ae.jpg)

**Comment by Apollyonn** [comment]
Whats the bug exactly with mana bar? because i think it works as it should.
https://gyazo.com/2725c68c5b08e62b7565a21d6f614395
https://gyazo.com/6bcf6cba02fd00a4f1cb76b2af1865cb

**Comment by RandomDudoo** [comment]
Well.. mostly times i simple don't have it. Its doesn't show up. About previously screenshots yes its worked as intend. (except first one)  I just don't know that, because see mana bar rarely. 
For example.
![wowscrnshot_020618_064314](https://user-images.githubusercontent.com/33762074/35839856-b6771af4-0b2d-11e8-8a4a-fd059991f990.jpg)

**Comment by Apollyonn** [comment]
If your mana is full, mana bar will hide.

**Comment by RandomDudoo** [comment]
Ohh so looks like i create problem from my ignorance.  whoops

**Comment by Apollyonn** [comment]
Druid mana bar will now always be visible, even if its full while at bear or cat form. If you want to hide it when its full, check Auto hide option.
![elvui](https://user-images.githubusercontent.com/19589902/36267684-31b3ff92-127d-11e8-9378-e44d6c0f2da3.png)
