### ISSUE TITLE
Freeze when opening panels or maximize the world map

### ISSUE THREAD

**Issue by NonIdentifie** [ElvUI-WotLK/ElvUI#486]
**Description**
When I enter the game and I open any panel the screen freeze for a second, this also happens every time when I want to maximize the world map, I have tried to deactivate all addons and only activate elvui and it keeps happening
**Version Number**
5.40

**Comment by iseos** [comment]
Так же, при первом открытии любой панели фризится на секунду. Версия 5.40. На старых версиях такого не было (примерно пол года назад скачивал).

**Comment by Loaal** [comment]
Should be fixed in 6.0 release
