### ISSUE TITLE
World map does not stay enlarged...

### ISSUE THREAD

**Issue by Lameoxx** [ElvUI-WotLK/ElvUI#489]
**Description**
if i click the button to enlarge the world map it goes back to the smaller version after i relog.... can u change this somehow?

**Version Number**
newest version, status 11.02.2018

**Only ElvUI Enabled**
got still the problem

**Comment by Crumdidlyumshis** [comment]
I would download latest and try again. I have tried on multiple characters and cannot reproduce.

**Comment by Bunny67** [comment]
fixed
