### ISSUE TITLE
[Question] Is it possible to disable the display of lua errors?

### ISSUE THREAD

**Issue by snwflake** [ElvUI-WotLK/ElvUI#492]
So, WoW gives you the option to disable the displaying of lua errors at `Interface > Help > 'Display lua errors'`.
I don't have that option checked, but enabled the ElvUI debug mode once (`/luaerror on`). After toggling it off (`/luaerror off`) nothing happened, and I receive a bunch of errors throughout the day.

This is incredibly annoying and hence the question: Is it possible to disable it again?

**Comment by Crumdidlyumshis** [comment]
Well our goal is to eliminate all ElvUI errors and if you are recovering errors, it would be best to share those so we can fix them if possible.

**Comment by snwflake** [comment]
That wasn't the question.
There are a lot of addons which are not maintained anymore and unless you want to fix them, I would appreciate not getting spammed with errors, while hovering an item ;)

**Comment by Apollyonn** [comment]
![52ceb6edb2e777bf502f4ab831f98e25](https://user-images.githubusercontent.com/19589902/36267954-f38e4e10-127d-11e8-899e-20d18fa0a69a.png)
Uncheck Display Lua errors

**Comment by snwflake** [comment]
> I don't have that option checked,...

**Comment by snwflake** [comment]
Any news?

**Comment by snwflake** [comment]
FIxed it myself.
Changed [`E:LuaError(val)`]( https://github.com/ElvUI-WotLK/ElvUI/blob/d7de9d91e2781445eea0a9fe719705f45355ad00/ElvUI/core/commands.lua#L77-L91 ) from
```lua
function E:LuaError(msg)
	msg = lower(msg);
	if(msg == "on") then
		DisableAllAddOns();
		EnableAddOn("ElvUI");
		EnableAddOn("ElvUI_Config");
		SetCVar("scriptErrors", 1);
		ReloadUI();
	elseif(msg == "off") then
		SetCVar("scriptErrors", 0);
		E:Print("Lua errors off.");
	else
		E:Print("/luaerror on - /luaerror off");
	end
end
```

to

```lua
function E:LuaError(msg)
	msg = lower(msg);
	if(msg == "on") then
		DisableAllAddOns();
		EnableAddOn("ElvUI");
		EnableAddOn("ElvUI_Config");
		SetCVar("scriptErrors", 1);
		ReloadUI();
	elseif(msg == "off") then
		SetCVar("scriptErrors", 0);
                SetCVar("showErrors", 0)
		E:Print("Lua errors off. Really...");
	else
		E:Print("/luaerror on - /luaerror off");
	end
end
```
