### ISSUE TITLE
DrDamage

### ISSUE THREAD

**Issue by Sheengor** [ElvUI-WotLK/ElvUI#495]
**Description**
Не корректно работает аддон DrDamage(нет отображения цифр урона/лечения на встроенной панели действий в ElvUi), если же ее отключить и использовать стандартный интерфейс проблемы нет

**Version Number**
<5.40>
http://ibb.co/fZJeRS - стандартный интерфейс
http://ibb.co/d69m6S - ElvUI

**Comment by Vitoshka** [comment]
Works with ElvUi**[DrDamage](https://cdn.discordapp.com/attachments/422912922025590784/441327431727448064/DrDamage.rar)**

**Comment by Loaal** [comment]
Compatibility fix added into [ElvUI_Enhanced](https://github.com/ElvUI-WotLK/ElvUI_Enhanced)
