### ISSUE TITLE
loot empty row

### ISSUE THREAD

**Issue by Frenlock** [ElvUI-WotLK/ElvUI#497]
**Description**
 The loot window sometimes show an aditional empty row .

**Version Number**
 5.40

**Steps to Reproduce**

1. Random loot

**Expected Behavior**
 that empty row shouldn exist
![wowscrnshot_021618_145614](https://user-images.githubusercontent.com/24683355/36319644-3a8e6fb0-134c-11e8-80c1-52f0f7f3977a.jpg)

**Actual Behavior**
 empty row exist

**Only ElvUI Enabled**

**Blizzard Issue?**

**Additional Information**

**Error Log**

```

```

**Comment by Crumdidlyumshis** [comment]
I think I have come across this on certain private servers. I could be wrong but I believe it is a server issue. However, if dont mind, try using the default UI for a bit until you come across this issue.

**Comment by Loaal** [comment]
Server related issue.
