### ISSUE TITLE
Shaman weapon enchant duration not properly displayed

### ISSUE THREAD

**Issue by snwflake** [ElvUI-WotLK/ElvUI#498]
**Description**
The duration of Shaman weapon enchant buffs (Windfury, Flametongue, Earthliving) are not properly displayed

**Version Number**
5.40 ~ 6ba055e

**Steps to Reproduce**
1. Use e.g. [Windfury](https://db.rising-gods.de/?spell=58804) on main hand 
2. Wait

**Expected Behavior**
Buff duration should be equal to enchant duration

**Actual Behavior**
Buff duration differs from actual enchant duration

**Only ElvUI Enabled**
confirmed

**Blizzard Issue?**
Not sure/unable to test

**Additional Information**
The buffs duration updates, once a buff is added/removed from the buff bar, so I assume the duration doesn't get checked/is updated only if the frame is updated.
Let me know if you need further information

![](https://i.imgur.com/eGmkBSP.png)

If I would dismount in that situation, and my mount would be removed from the buff list, the duration would update.

**Comment by NonIdentifie** [comment]
Same problem here.

**Comment by Loaal** [comment]
Should be fixed in 6.0 release.
