### ISSUE TITLE
Buff/debuff spacing

### ISSUE THREAD

**Issue by Auranim** [ElvUI-WotLK/ElvUI#502]
In 2015 someone asked:

> On the player buffs and debuffs, it is possible to add a horizontal gap.
> However, on the unitframe buffs and debuffs, this is not possible.
> Could you add this feature please.

To which it had been responded as added. However, I can't find this function. Can you point me in the right direction?

**Comment by Apollyonn** [comment]
https://github.com/ElvUI-WotLK/ElvUI_CustomTweaks
