### ISSUE TITLE
Shadow Word: pain dont show in target frame or over player

### ISSUE THREAD

**Issue by cronix91** [ElvUI-WotLK/ElvUI#503]
**Description**
My Shadow word: Pain dont show anywhere when i have it on someone. Tried to reset filters, reset all elvui and still not working. Disable other addons too but didnt work that either.. 

![elvuibugor](https://user-images.githubusercontent.com/32375295/37842812-7ab6fe80-2ec3-11e8-912e-49dd8002cbf5.png)

Like you can see here you can see it nowhere except from mik's scrolling battle text

**Version Number**
Version: 5.36

**Expected Behavior**
See debuff over player and over target frame

**Actual Behavior**
Dont see debuff over player and over target frame

**Blizzard Issue?**
Working here!

![working woithout elvui](https://user-images.githubusercontent.com/32375295/37843129-5a936c64-2ec4-11e8-9e32-c3bb169cddb7.png)

**Comment by Bunny67** [comment]
check in blacklist

**Comment by cronix91** [comment]
Thanks alot! a bit work later i got it working! 👍  Really dont know how it got blacklisted tho.
