### ISSUE TITLE
Action Bars 4 and 5 not working after latest update.

### ISSUE THREAD

**Issue by miby1400** [ElvUI-WotLK/ElvUI#505]
**Description**
After downloading the latest version my action (4 and 5) bars won't work anymore.

**Version Number**
5.4.1

**Steps to Reproduce**

1. Drag the fishing pole into action bar no.5
2. Drag the fishing skill into action bar no.5
3. Equip the fishing pole by clicking the fishing pole in the action bar **(not working)**.
4. Click the fishing skill (in the action bar) to start fishing **(not working)**.

**Expected Behavior**
The bar "Fishing" should appear as usual when fishing.

**Actual Behavior**
Nothing. And ofcourse its the same with all the other things in these action bars.

**Only ElvUI Enabled**
I did this with only ElvUi enabled and it still doesen't work as it should.

**Blizzard Issue?**
Clicking the action bars, equipping the fishing pole and fishing works fine with 0 addons enabled.

**Additional Information**

**Error Log**

```

```

**Comment by Bunny67** [comment]
run command in chat /fstack and move cursor on bars and make screenshot

**Comment by miby1400** [comment]
![wowscrnshot_032518_132915](https://user-images.githubusercontent.com/14054564/37874510-bf016062-3030-11e8-8282-bd491789e66d.jpg)


I noticed now: it works when left clicking...I must have been used to right clicking :)

**Comment by Bunny67** [comment]
fixed

**Comment by miby1400** [comment]
Noticing the same thing on other action bars now. Right-clicking doesent work anymore.
