### ISSUE TITLE
ElvUI automatically updated to TukUI.

### ISSUE THREAD

**Issue by DarkDanny** [ElvUI-WotLK/ElvUI#506]
**Description**
I was doing some Heroic grinding (on a 3.3.5a private server) & I got into a dungeon (Violet Hold.) Soon as I loaded in, a text box showed up & then my screen automatically went to another loading screen (as if I had used the /reloadui command) but when it finally put me back into the game, I was very unhappy to see that it had automatically updated me to TukUI & I use ElvUI purposely because I dislike the look of TukUI. I already know that I'm probably going to have to completely re-install ElvUI & overwrite my existing ElvUI folder & all my settings alongside it, I would just like to know how to prevent my addon from being "auto updated" in the future.

**Version Number**
5.27

**Steps to Reproduce**
Unknown.

**Expected Behavior**
It shouldn't have automatically updated me to TukUI.

**Actual Behavior**
It updated me to TukUI.

**Only ElvUI Enabled**
Isn't related to other addons

**Blizzard Issue?**
Is not a Blizzard related issue.

**Additional Information**
[This is what shows up every time I log in](https://i.imgur.com/s6v6QL8.jpg)

**Error Log**
No error appeared when this happened.
```

**Comment by Bunny67** [comment]
April Fools

**Comment by DarkDanny** [comment]
Okay, you got me lmao. When do I get to go back to not TukUI? :O

**Comment by Bunny67** [comment]
check /aprilfools or download latest release

**Comment by DarkDanny** [comment]
I updated to 5.41 & everything seems to be back to normal except for it still has that light grey TukUI border around everything & the general tab on left is [missing](https://i.imgur.com/o1fyv6j.jpg)

**Comment by Bunny67** [comment]
change border color in general options

**Comment by DarkDanny** [comment]
Did the general options move? It was above DT Bars last I remember.

**Comment by Bunny67** [comment]
enable lua errors and reloadui and toggle setting

**Comment by DarkDanny** [comment]
Message:

 Interface\AddOns\ElvUI_Config\General.lua:34: bad argument #2 to 'gsub' (string/function/table expected)
Time: 04/01/18 03:02:49
Count: 1
Stack: [C]: ?
[C]: in function `gsub'
Interface\AddOns\ElvUI_Config\General.lua:34: in main chunk
[C]: ?
[C]: in function `LoadAddOn'
Interface\AddOns\ElvUI\init.lua:196: in function `ToggleConfig'
...rface\AddOns\ElvUI\modules\datatexts\elvuiconfig.lua:53: in function `onClick'
...terface\AddOns\ElvUI\modules\datatexts\datatexts.lua:204: in function <...terface\AddOns\ElvUI\modules\datatexts\datatexts.lua:202>

Locals:

**Comment by Bunny67** [comment]
try reinstalling the addon. delete old files and copy new files

**Comment by Bunny67** [comment]
or update elvui plugins. You had a very old version

**Comment by DarkDanny** [comment]
I will do that. I should export my profile settings so I don't lose everything yeah?

**Comment by Bunny67** [comment]
Do not delete the folder WTF

**Comment by DarkDanny** [comment]
Oh okay. All of ElvUI settings are saved there and not inside the ElvUI folder itself then?

**Comment by Bunny67** [comment]
Yes

**Comment by DarkDanny** [comment]
Ahh that seemed to fix it & I have everything back to normal! Thank you @Bunny67 I love you, but I also hate you for such a cruel April Fools joke.  :^)

**Comment by Bunny67** [comment]
:)
