### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by Vitoshka** [ElvUI-WotLK/ElvUI#507]
**Description**
Возникают периодически данные ошибки при входе в игру и настройке ElvUI

**Version Number**
5.41

**Error Log**

1x ElvUI_Enhanced-1.03\Modules\Misc\characterFrame.lua:1623: attempt to index field 'backdrop' (a nil value)
ElvUI_Enhanced-1.03\Config\Config.lua:639: in function <ElvUI_Enhanced\Config\Config.lua:639>
(tail call): ?:
<in C code>: ?
<string>:"safecall Dispatcher[2]":9: in function <[string "safecall Dispatcher[2]"]:5>
(tail call): ?:
AceConfigDialog-3.0-50:821: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:642>
(tail call): ?:
<in C code>: ?
<string>:"safecall Dispatcher[3]":9: in function <[string "safecall Dispatcher[3]"]:5>
(tail call): ?:
AceGUI-3.0-34 (ElvUI_Config):314: in function `Fire'
...braries\AceGUI-3.0\widgets\AceGUIWidget-CheckBox.lua:68: in function <...braries\AceGUI-3.0\widgets\AceGUIWidget-CheckBox.lua:57>:

  ---

171x AceConfigDialog-3.0-50:1630: attempt to call method 'IsVisible' (a nil value)

Locals:

  ---

65x AceConfigDialog-3.0-50:1630: attempt to call method 'IsVisible' (a nil value)

Locals:

  ---

44x AceConfigDialog-3.0-50:1630: attempt to call method 'IsVisible' (a nil value)

Locals:

  ---

1x ElvUI_CustomTweaks-1.30\categories\chat\MaxLines.lua:48: attempt to index local 'self' (a nil value)
ElvUI_CustomTweaks-1.30\categories\chat\MaxLines.lua:24: in function <...dOns\ElvUI_CustomTweaks\categories\chat\MaxLines.lua:24>
(tail call): ?:
<in C code>: ?
<string>:"safecall Dispatcher[2]":9: in function <[string "safecall Dispatcher[2]"]:5>
(tail call): ?:
AceConfigDialog-3.0-50:821: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:642>
AceConfigDialog-3.0-50:873: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:861>
(tail call): ?:
<in C code>: ?
<string>:"safecall Dispatcher[3]":9: in function <[string "safecall Dispatcher[3]"]:5>
(tail call): ?:
AceGUI-3.0-34 (ElvUI_Config):314: in function `Fire'
...uest\libs\AceGUI-3.0\widgets\AceGUIWidget-Slider.lua:109: in function <...uest\libs\AceGUI-3.0\widgets\AceGUIWidget-Slider.lua:96>:

  ---

1x ElvUI_CustomTweaks-1.30\categories\chat\MaxLines.lua:48: attempt to index local 'self' (a nil value)
ElvUI_CustomTweaks-1.30\categories\chat\MaxLines.lua:24: in function <...dOns\ElvUI_CustomTweaks\categories\chat\MaxLines.lua:24>
(tail call): ?:
<in C code>: ?
<string>:"safecall Dispatcher[2]":9: in function <[string "safecall Dispatcher[2]"]:5>
(tail call): ?:
AceConfigDialog-3.0-50:821: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:642>
AceConfigDialog-3.0-50:873: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:861>
(tail call): ?:
<in C code>: ?
<string>:"safecall Dispatcher[3]":9: in function <[string "safecall Dispatcher[3]"]:5>
(tail call): ?:
AceGUI-3.0-34 (ElvUI_Config):314: in function `Fire'
...uest\libs\AceGUI-3.0\widgets\AceGUIWidget-Slider.lua:76: in function <...uest\libs\AceGUI-3.0\widgets\AceGUIWidget-Slider.lua:74>:

**Comment by Bunny67** [comment]
Скины включены?

**Comment by Vitoshka** [comment]
Да, скины включены

**Comment by Vitoshka** [comment]
Также по поводу скинов, можно ли добавить данный функционал выбора отображения и для Омена трит метра и для рекаунта? [Пример](https://d.radikal.ru/d37/1804/ca/6233ff584ffb.jpg)

**Comment by Bunny67** [comment]
Последние ошибки должна быть исправлены, 1-ю не удалось воспроизвести.

По поводу скинов, если не забуду, добавлю. Лучше в аддон_скинах создай тикет

**Comment by Vitoshka** [comment]
словил ещё пару

117x ElvUI-5.41\Libraries\oUF\elements\castbar.lua:112: attempt to perform arithmetic on field 'castID' (a nil value)
(tail call): ?:
<in C code>: in function `CastSpell'
Interface\FrameXML\SpellBookFrame.lua:350: in function `SpellButton_OnClick':
<string>:"*:OnClick":4: in function <[string "*:OnClick"]:1>

Locals:
(*temporary) = "LeftButton"
(*temporary) = false
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = <function> defined =[C]:-1

  ---

103x AceConfigDialog-3.0-50:1630: attempt to call method 'IsVisible' (a nil value)

Locals:

  ---
