### ISSUE TITLE
Необходимо исправление

### ISSUE THREAD

**Issue by Vitoshka** [ElvUI-WotLK/ElvUI#508]
**Description**
Графические ошибки в интерфейсе ElvUI

**Version Number**
5.41

**Error Log**
Когда в общих настройках включаю отображение имени на облачке сообщения то показывается такое:
https://d.radikal.ru/d43/1804/52/98e9a6ec380a.jpg

====

https://d.radikal.ru/d33/1804/ca/3119bcbd643b.jpg

https://d.radikal.ru/d36/1804/4d/c05f97734ecc.jpg

====

Проблема отображения перезарядки, можно ли сделать функцию, чтобы цифра клавиши скрывалась, когда спел на перезарядке и идёт отсчёт, чтобы не было наложения? 

https://c.radikal.ru/c11/1804/9a/801f5e37df69.jpg

====

Проблема выхода за края цифр отсчёта, может можно сделать возможность масштабирования или как отличный вариант 5m, 4m, 1m (белый цвет) и далее отсчёт в секундах  59-6 (жёлтый цвет), а 5-1 (красный, увеличенный цвет)

https://a.radikal.ru/a29/1804/a1/89be86cd271c.jpg

**Comment by Bunny67** [comment]
1-е поправил, 2-4 к сожалению не поправить, 5 ну в элве так и есть(без плагинов) кроме увеличения, его норм не получится реализовать
