### ISSUE TITLE
Language setting problem

### ISSUE THREAD

**Issue by yihu0259** [ElvUI-WotLK/ElvUI#510]
**Description**
The config setting cannot work in Simplified Chinese language in all ElvUI versions
the locales in English and Taiwanese versions works well while the Chinese version didn't display any instructions, the printscreen picture are shown as attachments.
CN
![cn](https://user-images.githubusercontent.com/28259542/38463913-5a70c3c8-3b47-11e8-8d00-b919a89a5b4e.jpg)

EN
![en](https://user-images.githubusercontent.com/28259542/38463914-5aa22044-3b47-11e8-92b0-6df8dc6948fd.jpg)

TW
![tw](https://user-images.githubusercontent.com/28259542/38463915-5ad40e2e-3b47-11e8-8819-d411a3546945.jpg)

**Version Number**
5.41 and all other former versions

**Steps to Reproduce**

1. Step 1
2. Step 2
3. Step 3
4. Step 4

**Expected Behavior**
The locale file is there and the instruction setting should work well in Simplified Chinese. 

**Actual Behavior**
Not work

**Only ElvUI Enabled**

**Blizzard Issue?**

**Additional Information**

**Error Log**

**Comment by Apollyonn** [comment]
https://github.com/ElvUI-WotLK/ElvUI/issues/529
