### ISSUE TITLE
Boss frame not working

### ISSUE THREAD

**Issue by Svetdwell** [ElvUI-WotLK/ElvUI#511]
**Description**
Boss frame is enabled and not visually showing while in a boss encounter on Sunwell/Angrathar server.
Only DBM's boss frame is appearing.

**Version Number**
 24ff9d8

**Steps to Reproduce**

1. Step 1
2. Step 2
3. Step 3
4. Step 4

**Expected Behavior**
The unit frame should be visible.

**Actual Behavior**
Its invisible.

**Only ElvUI Enabled**

**Blizzard Issue?**

**Additional Information**

**Error Log**

```

```

**Comment by Svetdwell** [comment]
![wowscrnshot_041018_152801](https://user-images.githubusercontent.com/29394139/38556881-dc0b56ea-3cd3-11e8-8c67-d14095cfba7d.jpg)

**Comment by Bunny67** [comment]
Boss Frames support only "bossID" units.
