### ISSUE TITLE
WeakAuras not loading UI

### ISSUE THREAD

**Issue by joao-fidalgo** [ElvUI-WotLK/ElvUI#514]
**Description**
WeakAuras UI doesn't load when using the latest version of ElvUI.

**Version Number**
5.41 from master branch commit 24ff9d8aa4bbe42876b102e4e5d50b623f8cedeb

**Steps to Reproduce**
1. Install ElvUI;
2. Install [WeakAuras 2.0.8](http://www.dalaran-wow.com/forums/community/ui-customization/topic/6903/weakauras-2-0-8-for-3-3-5-beta);
3. Log in;
4. Type /wa in chat;

**Expected Behavior**
WeakAuras UI should open.

**Actual Behavior**
WeakAuras UI doesn't open.

**Error Log**
```
Message: Interface\AddOns\ElvUI\modules\skins\addons\ace3.lua:120: attempt to index field 'scrollBG' (a nil value)
Time: 04/22/18 17:46:40
Count: 1
Stack: [C]: ?
Interface\AddOns\ElvUI\modules\skins\addons\ace3.lua:120: in function `RegisterAsWidget'
...AceGUI-3.0\widgets\AceGUIWidget-MultiLineEditBox.lua:279: in function `?'
...face\AddOns\WeakAuras\libs\AceGUI-3.0\AceGUI-3.0.lua:136: in function <...face\AddOns\WeakAuras\libs\AceGUI-3.0\AceGUI-3.0.lua:125>
...face\AddOns\WeakAuras\libs\AceGUI-3.0\AceGUI-3.0.lua:174: in function `Create'
...terface\AddOns\WeakAurasOptions\WeakAurasOptions.lua:6714: in function `CreateFrame'
...terface\AddOns\WeakAurasOptions\WeakAurasOptions.lua:1200: in function `ShowOptions'
...terface\AddOns\WeakAurasOptions\WeakAurasOptions.lua:1172: in function `ToggleOptions'
Interface\AddOns\WeakAuras\WeakAuras.lua:46: in function `OpenOptions'
Interface\AddOns\WeakAuras\WeakAuras.lua:51: in function `value'
Interface\FrameXML\ChatFrame.lua:4070: in function `ChatEdit_ParseText'
Interface\FrameXML\ChatFrame.lua:3660: in function `ChatEdit_SendText'
Interface\FrameXML\ChatFrame.lua:3698: in function <Interface\FrameXML\ChatFrame.lua:3694>
[C]: in function `ChatEdit_OnEnterPressed'
[string "*:OnEnterPressed"]:1: in function <[string "*:OnEnterPressed"]:1>

Locals: 
```

**Comment by joao-fidalgo** [comment]
**Workaround**
1. Open ElvUI configuration menu
2. Select the Skins tab
3. Uncheck Ace3 checkbox

**Comment by Apollyonn** [comment]
I'm guessing you have the 2.0.8 version, so go to your addons folder WeakAuras\libs\AceGUI-3.0\widget  and find AceGUIWidget-MultiLineEditBox. Add this `scrollBG    = scrollBG,` after line 270.

**Comment by Apollyonn** [comment]
I don't know if there are any other versions of weak auras for wotlk, i never used it before on wotlk, i did a quick search on google and i only found the 2.0.8 one.

**Comment by Tsaav** [comment]
I tried what Apollyonn said and that didn't do anything for me. Anyone have any other solution?

**Comment by Apollyonn** [comment]
it should look like this
![1d8dd3c482aeef33d9282c0271a3ff67](https://user-images.githubusercontent.com/19589902/41501027-264970ba-71a5-11e8-8a08-d925f664e940.png)

![070628cfd6a7afba7108bce54a7a6a3d](https://user-images.githubusercontent.com/19589902/41501026-23ecc6c8-71a5-11e8-8642-da9b9d04d2c3.png)

**Comment by Tsaav** [comment]
Here's what I have right now, looks the same I think
![image](https://user-images.githubusercontent.com/33384632/41501141-64cc2898-716c-11e8-8d6b-388a9bf3dada.png)

Here's the error I'm getting though

> Message: Interface\AddOns\ElvUI\modules\skins\addons\ace3.lua:120: attempt to index field 'scrollBG' (a nil value)
Time: 06/16/18 13:51:27
Count: 1
Stack: [C]: ?
Interface\AddOns\ElvUI\modules\skins\addons\ace3.lua:120: in function `RegisterAsWidget'
...AceGUI-3.0\widgets\AceGUIWidget-MultiLineEditBox.lua:279: in function `?'
...erface\AddOns\Mapster\Libs\AceGUI-3.0\AceGUI-3.0.lua:136: in function <...erface\AddOns\Mapster\Libs\AceGUI-3.0\AceGUI-3.0.lua:125>
...erface\AddOns\Mapster\Libs\AceGUI-3.0\AceGUI-3.0.lua:174: in function `Create'
...terface\AddOns\WeakAurasOptions\WeakAurasOptions.lua:6714: in function `CreateFrame'
...terface\AddOns\WeakAurasOptions\WeakAurasOptions.lua:1200: in function `ShowOptions'
...terface\AddOns\WeakAurasOptions\WeakAurasOptions.lua:1172: in function `ToggleOptions'
Interface\AddOns\WeakAuras\WeakAuras.lua:46: in function `OpenOptions'
Interface\AddOns\WeakAuras\WeakAuras.lua:51: in function `value'
Interface\FrameXML\ChatFrame.lua:4070: in function `ChatEdit_ParseText'
Interface\FrameXML\ChatFrame.lua:3660: in function `ChatEdit_SendText'
Interface\FrameXML\ChatFrame.lua:3698: in function <Interface\FrameXML\ChatFrame.lua:3694>
[C]: in function `ChatEdit_OnEnterPressed'
[string "*:OnEnterPressed"]:1: in function <[string "*:OnEnterPressed"]:1>

Locals:

**Comment by Apollyonn** [comment]
Do you have any other addons active?

**Comment by Tsaav** [comment]
Yeah, but not very many 

![image](https://user-images.githubusercontent.com/33384632/41501298-fd070bd4-716f-11e8-9638-5bc0164d03b3.png)

![image](https://user-images.githubusercontent.com/33384632/41501301-055a2f64-7170-11e8-8b91-05c4da93e3ff.png)

**Comment by Tsaav** [comment]
Aha! It works now! I'll try going through the addons to see which one is causing issues

**Comment by Tsaav** [comment]
Looks like Recount was causing an issue. Looked inside, found another AceGUIWidget-MultiLineEditBox file inside Recount's libs folder. Added the scrollBG = scrollBG, for recount, and that fixed all my issues!
