### ISSUE TITLE
Ошибка

### ISSUE THREAD

**Issue by Vitoshka** [ElvUI-WotLK/ElvUI#523]
**Description**
Словил ошибку при наведении на ссылку на линк достижения в чате.
_There is a periodic error when you hover over the link to the achievement in the chat._

**Version Number**
5.41

**Error Log**
1x ElvUI_Enhanced-1.03\Modules\Tooltip\tooltipicon.lua:28: bad argument #1 to 'find' (string expected, got nil)
ElvUI_Enhanced-1.03\Modules\Tooltip\tooltipicon.lua:28: in function <...ddOns\ElvUI_Enhanced\Modules\Tooltip\tooltipicon.lua:24>
ElvUI_Enhanced-1.03\Modules\Tooltip\tooltipicon.lua:50: in function <...ddOns\ElvUI_Enhanced\Modules\Tooltip\tooltipicon.lua:46>
(tail call): ?:
<in C code>: in function `SetHyperlink'
ElvUI-5.41\modules\chat\chat.lua:841: in function `?'
AceHook-3.0-8 (ElvUI):90: in function <...e\AddOns\ElvUI\Libraries\AceHook-3.0\AceHook-3.0.lua:87>

Locals:
self = GameTooltip {
 SetText = <function> @ QuestHelper\collect.lua:24:
 SetExistingSocketGem = <function> defined =[C]:-1
 SetCurrencyToken = <function> defined =[C]:-1
 SetGuildBankItem = <function> defined =[C]:-1
 hasMoney = 1
 Hide = <function> defined =[C]:-1
 template = "Transparent"
 comparing = false
 SetSocketGem = <function> defined =[C]:-1
 SetUnitDebuff = <function> defined =[C]:-1
 SetLootItem = <function> defined =[C]:-1
 SetQuestItem = <function> defined =[C]:-1
 SetTrainerService = <function> defined =[C]:-1
 numMoneyFrames = 2
 SetInboxItem = <function> defined =[C]:-1
 SetBuybackItem = <function> defined =[C]:-1
 shoppingTooltips = <table> {}
 SetHyperlinkCompareItem = <function> defined =[C]:-1
 SetMerchantItem = <function> defined =[C]:-1
 SetMerchantCostItem = <function> defined =[C]:-1
 SetBackpackToken = <function> defined =[C]:-1
 SetTradeTargetItem = <function> defined =[C]:-1
 SetTradePlayerItem = <function> defined =[C]:-1
 SetSendMailItem = <function> defined =[C]:-1
 SetUnitBuff = <function> defined =[C]:-1
 updateTooltip = 0.12199999652803
 SetInventoryItem = <function> defined =[C]:-1
 SetLootRollItem = <function> defined =[C]:-1
 SetUnitAura = <function> defined =[C]:-1
 ignoreUpdates = true
 SetAuctionSellItem = <function> defined =[C]:-1
 SetBagItem = <function> defined =[C]:-1
 SetHyperlink = <function> defined =[C]:-1
 0 = <userdata>
 SetTradeSkillItem = <function> defined =[C]:-1
 SetQuestLogItem = <function> defined =[C]:-1
 SetAuctionItem = <function> defined =[C]:-1
}
icon = "Interface\Icons\Achievement_Arena_2v2_5"
title = GameTooltipTextLeft1 {
 0 = <userdata>
}
_G = <table> {
 ContainerFrame5Item7 = ContainerFrame5Item7 {}
 MultiCastActionButton6Cooldown = MultiCastActionButton6Cooldown {}
 FriendsFrameFriendsScrollFrameButton16SummonButtonHotKey = FriendsFrameFriendsScrollFrameButton16SummonButtonHotKey {}
 GetTrainerServiceTypeFilter = <function> defined =[C]:-1
 UNIT_NAMES_COMBATLOG_TOOLTIP = "Öâåòîâîå âûäåëåíèå íàçâàíèé îáúåêòîâ."
 KBASE_NUM_FAKE_CATEGORIES = 1
 SetTrainerServiceTypeFilter = <function> defined =[C]:-1
 MerchantItem6AltCurrencyFrameHonorTexture = MerchantItem6AltCurrencyFrameHonorTexture {}
 MetaMap_InstanceMenuMiddle = MetaMap_InstanceMenuMiddle {}
 DecursiveSkipListFrameClose = DecursiveSkipListFrameClose {}
 TutorialFrameLeft19 = TutorialFrameLeft19 {}
 MultiCastActionButton2Cooldown = MultiCastActionButton2Cooldown {}
 ERR_TRADE_EQUIPPED_BAG = "Ñóìêè, ÿâëÿþùèåñÿ ÷àñòüþ ýêèïèðîâêè, íå ïðîäàþòñÿ è íå ïîêóïàþòñÿ."
 PVP_RANK_6_1 = "Êàïðàë"
 MultiBarLeftButton7 = MultiBarLeftButton7 {}
 OPTION_TOOLTIP_SHOW_MULTIBAR4 = "Îòîáðàæåíèå äîïîëíèòåëüíîé ïàíåëè êîìàíä â ïðàâîé ÷àñòè ýêðàíà."
 InterfaceOptionsDisplayPanelShowAggroPercentageText = InterfaceOptionsDisplayPanelShowAggroPercentageText {}
 VideoOptionsFrameDefaults = VideoOptionsFrameDefaults {}
 MerchantItem4AltCurrencyFrameItem1Text = MerchantItem4AltCurrencyFrameItem1Text {}
 BINDING_NAME_NAMEPLATES = "Ïîêàçàòü èíäèêàòîðû âðàãîâ"
 Atr_StackList9 = Atr_StackList9 {}
 IsReferAFriendLinked = <function> defined =[C]:-1
 MAIL_LETTER_TOOLTIP = "Ùåëêíèòå çäåñü, ÷òîáû ñäåëàòü
êîïèþ ýòîãî ïèñüìà."
 UnitFrameManaBar_UnregisterDefaultEvents = <function> @ Interface\FrameXML\UnitFrame.lua:298:
 EAFrame_60513_Name = EAFrame_60513_Name {}
 CALENDAR_RAID_RESET_DESCRIPTION = "%1$s îáíîâèòñÿ â %2$s."
 CHAT_CONFIG_OTHER_COMBAT = <table> {}
 FCFDockOverflowButton_OnClick = <function> @ Interface\FrameXML\FloatingChatFrame.lua:2363:
 TutorialFrameRight19 = TutorialFrameRight19 {}
 ChatFrame6EditBoxFocusMid = ChatFrame6EditBoxFocusMid {}
 BN_UNABLE_TO_RESOLVE_NAME = "Íåâîçìîæíî ïðîøåïòàòü: "%s". Ñëóæáà Battle.net ìîæåò áûòü íåäîñòóïíà."
 WatchFrameItem_OnEvent = <function> defined @Interfa
  ---

**Comment by Apollyonn** [comment]
fixed https://github.com/ElvUI-WotLK/ElvUI_Enhanced/commit/012cbdd32168d33708bfdca16218ee251aacd0a1
