### ISSUE TITLE
Incorrect display of the border of the chat tabs/Некорректное отображение границы вкладок чата 

### ISSUE THREAD

**Issue by Vitoshka** [ElvUI-WotLK/ElvUI#531]
**Description**
Заметил некорректное отображение фона вкладок чата. Данная функция отображения фона вкладок чата у меня отключена, **a)** но при входе в игру или при релоге [у меня показывается вот так](https://b.radikal.ru/b00/1805/11/522cae27bc2b.jpg)
**b)** Далее, когда я нажимаю [Enter](https://b.radikal.ru/b20/1805/8d/6d4c64d66c87.jpg)
Отправляю сообщение или ещё раз нажимаю Enter и **c)** уже [показывает вот так](https://c.radikal.ru/c38/1805/6f/a95366f2e200.jpg)
Можно ли сделать сразу, что бы при загрузке персонажа отображение было, как в последнем пункте **c)**, как на скриншоте?

**I noticed an incorrect display of the background of the chat tabs. This function of displaying the background of chat tabs is turned off, ** a) ** but when logging on to the game or when relogging [I'm showing this here](https://b.radikal.ru/b00/1805/11/522cae27bc2b.jpg)
** b) ** Further, when I press [Enter](https://b.radikal.ru/b20/1805/8d/6d4c64d66c87.jpg)
I send the message or press Enter once more and ** c) ** [already shows like this](https://c.radikal.ru/c38/1805/6f/a95366f2e200.jpg)
Can I do it right away, so that when I load the character, I see the display as in the last paragraph ** c) **, as in the screenshot?**

**Version Number**
5.41

**Comment by Apollyonn** [comment]
Can't reproduce. Try with only elvui enabled on a new profile.

**Comment by Vitoshka** [comment]
После последних обновлений эта графическая ошибка больше не появляется
**After the last updates this graphic bug no longer appears**
