### ISSUE TITLE
DataTexts: CritChance Issue

### ISSUE THREAD

**Issue by dsgassassin** [ElvUI-WotLK/ElvUI#534]
**Description**
DataTexts -> CritChance only shows Melee/Ranged Crit, no option for Spell Crit

**Version Number**
5.41

**Steps to Reproduce**

1. Settings
2. DataTexts
3. Panels
4. Pick one
5. Crit Chance

**Expected Behavior**
Should have separate options for Melee, Ranged and Spell crit chances, as they are different values.

**Actual Behavior**
Only one crit chance option is available.

**Only ElvUI Enabled**

Can be reproduced with only ElvUI enabled.

**Blizzard Issue?**

**Additional Information**

**Error Log**

```

```

**Comment by Loaal** [comment]
Type of displayed critical chance value determined by current player specialization. Datatext behave as expected and will not be changed.
