### ISSUE TITLE
Combat log tab disappears

### ISSUE THREAD

**Issue by Vitoshka** [ElvUI-WotLK/ElvUI#536]
**Description**
Когда автоматически активируется режим [АФК](https://c.radikal.ru/c40/1806/94/9c65fc994bbd.jpg) а потом он отменяется когда я начинаю играть, то у меня [пропадает вкладка лог боя](https://c.radikal.ru/c05/1806/b9/b7c7e25ea35c.jpg). Также вкладка боевой лог пропадает когда я нажимаю [Alt+Z](https://b.radikal.ru/b09/1806/8c/38320f97364c.jpg) два раза, чтобы убрать отображение интерфейса игры и потом чтобы снова включить отображение интерфейса игры обратно. 
В данной ситуации помогает только [перетащить](https://d.radikal.ru/d01/1806/5b/a51c3069ee2a.jpg
) любую вкладку чата и только тогда вкладка чата комбат лог появляется. Также помогает релог.

**When the [AFK](https://c.radikal.ru/c40/1806/94/9c65fc994bbd.jpg) mode is automatically activated and then it is canceled when I start playing, then I [lose the Combat log tab](https://c.radikal.ru/c05/1806/b9/b7c7e25ea35c.jpg). Also, the Combat log tab disappears when I press [ALT+Z](https://b.radikal.ru/b09/1806/8c/38320f97364c.jpg) two times to remove the display of the game interface and then to turn the display of the game interface back on again.
In this situation, it helps to just [drag](https://d.radikal.ru/d01/1806/5b/a51c3069ee2a.jpg
) and drop any chat tab and only then the chat tab of the combat log appears. Relog also helps.**

**Version Number**
5.42

**Additional Information**
Дополнительных аддонов для чата у меня не установлено
**I do not have additional addons for chat**

Спасибо за помощь
**Thx for the help**

**Comment by Loaal** [comment]
Should be fixed in 6.0 release.
