### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by Vitoshka** [ElvUI-WotLK/ElvUI#543]
**Description**
periodic error occurs

**Version Number**
5.43

**Error Log**
2x ElvUI-5.43\modules\tooltip\tooltip.lua:381: attempt to index local 'targetColor' (a nil value)
AceHook-3.0-8 (ElvUI):90: in function <...e\AddOns\ElvUI\Libraries\AceHook-3.0\AceHook-3.0.lua:87>
(tail call): ?:
<in C code>: in function `SetUnit'
Interface\FrameXML\UnitFrame.lua:146: in function `UnitFrame_UpdateTooltip':
Interface\FrameXML\UnitFrame.lua:133: in function <Interface\FrameXML\UnitFrame.lua:120>:

Locals:
actives = <table> {
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = 
  ---
1x ElvUI-5.43\modules\misc\misc.lua:170: bad argument #1 to 'gsub' (string expected, got nil)
ElvUI-5.43\modules\misc\misc.lua:170: in function `?'
CallbackHandler-1.0-6:147: in function <...ibs\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:147>
<string>:"safecall Dispatcher[2]":4: in function <[string "safecall Dispatcher[2]"]:4>
<in C code>: ?
<string>:"safecall Dispatcher[2]":13: in function `?'
CallbackHandler-1.0-6:92: in function `Fire'
AceEvent-3.0-4 (ElvUI):120: in function <...AddOns\ElvUI\Libraries\AceEvent-3.0\AceEvent-3.0.lua:119>

  ---

1x ElvUI-5.43\modules\datatexts\friends.lua:164: bad argument #6 to 'format' (string expected, got nil)
ElvUI-5.43\modules\datatexts\friends.lua:164: in function `onEnter'
ElvUI-5.43\modules\datatexts\datatexts.lua:211: in function <...terface\AddOns\ElvUI\modules\datatexts\datatexts.lua:209>

Locals:
self = LeftChatDataPanelDataText1 {
 0 = <userdata>
 text = <unnamed> {}
 name = "Friends"
 pointIndex = "middle"
}
numberOfFriends = 9
onlineFriends = 4
zonec = <table> {
 b = 0.65
 g = 0.65
 r = 0.65
}
classc = <table> {
 b = 0.45
 g = 0.83
 r = 0.67
}
levelc = <table> {
 b = 0
 font = QuestDifficulty_Difficult {}
 g = 1
 r = 1
}
info = <table> {
 2 = 79
 3 = "HUNTER"
 4 = "Зул'Драк"
 5 = 1
 6 = ""
}
grouped = 2
(for index) = 4
(for limit) = 4
(for step) = 1
i = 4
(*temporary) = <function> defined =[C]:-1
(*temporary) = DatatextTooltip {
 ignoreUpdates = true
 updateTooltip = 0.2
 0 = <userdata>
 comparing = false
 template = "Transparent"
}
DT = <table> {
 SetDefaultModuleLibraries = <function> @ ElvUI\Libraries\AceAddon-3.0\AceAddon-3.0.lua:398:
 RegisterLDB = <function> @ ElvUI\modules\datatexts\datatexts.lua:102:
 modules = <table> {}
 CancelTimer = <function> @ ElvUI\Libraries\AceTimer-3.0\AceTimer-3.0.lua:161:
 IterateEmbeds = <function> @ ElvUI\Libraries\AceAddon-3.0\AceAddon-3.0.lua:473:
 SecureHookScript = <function> @ ElvUI\Libraries\AceHook-3.0\AceHook-3.0.lua:410:
 Data_OnLeave = <function> @ ElvUI\modules\datatexts\datatexts.lua:140:
 LoadDataTexts = <function> @ ElvUI\modules\datatexts\datatexts.lua:222:
 RawHookScript = <function> @ ElvUI\Libraries\AceHook-3.0\AceHook-3.0.lua:395:
 HideBattlegroundTexts = <function> @ ElvUI\modules\datatexts\battleground.lua:91:
 tooltip = DatatextTooltip {}
 SetDefaultModulePrototype = <function> @ ElvUI\Libraries\AceAddon-3.0\AceAddon-3.0.lua:440:
 defaultModuleState = true
 IsEnabled = <function> @ ElvUI\Libraries\AceAddon-3.0\AceAddon-3.0.lua:482:
 UPDATE_BATTLEFIELD_SCORE = <function> @ ElvUI\modules\datatexts\battleground.lua:47:
 ScheduleTimer = <function> @ ElvUI\Libraries\AceTimer-3.0\AceTimer-3.0.lua:108:
 DisableModule = <function> @ ElvUI\Libraries\AceAddon-3.0\AceAddon-3.0.lua:381:
 SetupTooltip = <function> @ ElvUI\modules\datatexts\datatexts.lua:144:
 RegisterMessage = <function> @ Aesa\Libs\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:118:
 UnregisterMessage = <function> @ Aesa\Libs\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:181:
 IsHooked = <function> @ ElvUI\Libraries\AceHook-3.0\AceHook-3.0.lua:493:
 UpdateAllDimensions = <function> @ ElvUI\modules\datatexts\datatexts.lua:127:
 db = <table> {}
 SetEnabledState = <function> @ ElvUI\Libraries\AceAddon-3.0\AceAddon-3.0.lua:455:
 Hook = <function> @ ElvUI\Libraries\AceHook-3.0\AceHook-3.0.lua:274:
 enabledState = true
 RegisterEvent = <function> @ Aesa\Libs\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:118:
 SetupObjectLDB = <function> @ ElvUI\modules\datatexts\datatexts.lua:49:
 IterateModules = <function> @ ElvUI\Libraries\AceAddon-3.0\AceAddon-3.0.lua:468:
 RawHook = <function> @ ElvUI\Libraries\AceHook-3.0\AceHook-3.0.lua:313:
 RegisteredPanels = <table> {}
 Enable = <function> @ ElvUI\Libraries\AceAddon-3.0\AceAddon-3.0.lua:325:
 UnregisterAllEvents = <function> @ Aesa\Libs\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:202:
 GetModule = <function> @ ElvUI\Libraries\AceAddon-3.0\AceAddon-3.0.lua:241:
 defaultModuleLibraries = <table> {}
 TimeLeft = <function> @ ElvUI\Libraries\AceTimer-3.0\AceTimer-3.0.lua:187:
 PointLocation = <table> {}
 ScheduleRepeatingTimer = <function> @ ElvUI\Libraries\AceTimer-3.0\AceTimer-3.0.lua:143:
 CancelAllTimers = <function> defined @ElvU
  ---
1x Interface\FrameXML\FriendsFrame.lua:2149: attempt to concatenate local 'name' (a nil value):
<in C code>: in function `buttonFunc'
Interface\FrameXML\UIPanelTemplates.lua:579: in function `DynamicScrollFrame_Update':
Interface\FrameXML\FriendsFrame.lua:446: in function `FriendsList_Update':
Interface\FrameXML\FriendsFrame.lua:1193: in function <Interface\FrameXML\FriendsFrame.lua:1188>:
(tail call): ?:
<string>:"*:OnEvent":1: in function <[string "*:OnEvent"]:1>

Locals:
(*temporary) = FriendsFrameFriendsScrollFrameButton10 {
 0 = <userdata>
 highlight = <unnamed> {}
 broadcastMessage = FriendsFrameFriendsScrollFrameButton10BroadcastMessage {}
 backgroundLeft = <unnamed> {}
 iconFrame = FriendsFrameFriendsScrollFrameButton10IconFrame {}
 status = FriendsFrameFriendsScrollFrameButton10Status {}
 background = FriendsFrameFriendsScrollFrameButton10Background {}
 backgroundRight = <unnamed> {}
 id = 9
 text = <unnamed> {}
 buttonType = 3
 highlightLeft = <unnamed> {}
 summonButton = FriendsFrameFriendsScrollFrameButton10SummonButton {}
 name = FriendsFrameFriendsScrollFrameButton10Name {}
 gameIcon = FriendsFrameFriendsScrollFrameButton10GameIcon {}
 info = FriendsFrameFriendsScrollFrameButton10Info {}
 highlightRight = <unnamed> {}
 broadcastIcon = FriendsFrameFriendsScrollFrameButton10BroadcastIcon {}
 compactInfo = FriendsFrameFriendsScrollFrameButton10CompactInfo {}
}
(*temporary) = 10
(*temporary) = false
 = <function> @ Interface\FrameXML\FriendsFrame.lua:2128:
 = <function> @ ElvUI\Libraries\AceHook-3.0\AceHook-3.0.lua:100:

  ---

1x Interface\FrameXML\FriendsFrame.lua:2149: attempt to concatenate local 'name' (a nil value):
<in C code>: in function `buttonFunc'
Interface\FrameXML\UIPanelTemplates.lua:579: in function `DynamicScrollFrame_Update':
Interface\FrameXML\FriendsFrame.lua:446: in function `FriendsList_Update':
Interface\FrameXML\FriendsFrame.lua:1193: in function <Interface\FrameXML\FriendsFrame.lua:1188>:
(tail call): ?:
<string>:"*:OnEvent":1: in function <[string "*:OnEvent"]:1>
<in C code>: in function `SetFriendNotes'
Interface\FrameXML\StaticPopup.lua:1757: in function `OnAccept':
Interface\FrameXML\StaticPopup.lua:3473: in function `StaticPopup_OnClick':
<string>:"*:OnClick":1: in function <[string "*:OnClick"]:1>

Locals:
(*temporary) = FriendsFrameFriendsScrollFrameButton10 {
 0 = <userdata>
 highlight = <unnamed> {}
 broadcastMessage = FriendsFrameFriendsScrollFrameButton10BroadcastMessage {}
 backgroundLeft = <unnamed> {}
 iconFrame = FriendsFrameFriendsScrollFrameButton10IconFrame {}
 status = FriendsFrameFriendsScrollFrameButton10Status {}
 background = FriendsFrameFriendsScrollFrameButton10Background {}
 backgroundRight = <unnamed> {}
 id = 9
 text = <unnamed> {}
 buttonType = 3
 highlightLeft = <unnamed> {}
 summonButton = FriendsFrameFriendsScrollFrameButton10SummonButton {}
 name = FriendsFrameFriendsScrollFrameButton10Name {}
 gameIcon = FriendsFrameFriendsScrollFrameButton10GameIcon {}
 info = FriendsFrameFriendsScrollFrameButton10Info {}
 highlightRight = <unnamed> {}
 broadcastIcon = FriendsFrameFriendsScrollFrameButton10BroadcastIcon {}
 compactInfo = FriendsFrameFriendsScrollFrameButton10CompactInfo {}
}
(*temporary) = 10
(*temporary) = false
 = <function> @ Interface\FrameXML\FriendsFrame.lua:2128:
 = <function> @ ElvUI\Libraries\AceHook-3.0\AceHook-3.0.lua:100:

  ---

**Comment by Loaal** [comment]
Should be fixed in 6.0 release.
