### ISSUE TITLE
Player blobs bug when using Mapster

### ISSUE THREAD

**Issue by fatlus** [ElvUI-WotLK/ElvUI#544]
**Description**
There are no player dots on the world map when using Mapster. Instead they are messed up squares and difficult to identify.

**Version Number**
5.4.3

![wowscrnshot_071118_220104](https://user-images.githubusercontent.com/6052285/42596634-a43ce30c-8556-11e8-8484-13b88faaa0a3.jpg)

**Comment by ArthurFkingShelby** [comment]
You can get rid of this by disabling Group Icons from Mapster until its fixed than /reload or relog
