### ISSUE TITLE
Pet Bar

### ISSUE THREAD

**Issue by eskiq** [ElvUI-WotLK/ElvUI#547]
**Description**
Pet Bar doesn't show up on mouseover
**Version Number**
5.43
**Steps to Reproduce**
1.Enable Pet Bar
2.Enable Mouseover
**Expected Behavior**
Show bar on mouseover like other bars
**Actual Behavior**
Its hidden with that option and can't be visable on mouseover
**Only ElvUI Enabled**
yes
**Error Log**
ID: 1
Error occured in: Global
Count: 1
Message: ...rface\AddOns\ElvUI\modules\actionbars\actionbars.lua line 610:
   attempt to index field 'db' (a nil value)
Debug:
   [C]: ?
   ...rface\AddOns\ElvUI\modules\actionbars\actionbars.lua:610: ?()
   ...e\AddOns\ElvUI\Libraries\AceHook-3.0\AceHook-3.0.lua:90:
      ...e\AddOns\ElvUI\Libraries\AceHook-3.0\AceHook-3.0.lua:87
   [C]: ?
   [C]: ?

**Comment by Apollyonn** [comment]
https://gyazo.com/f0bd73e904dca968654c0a39427f1e53
Can't reproduce. Do you have the latest update?

**Comment by eskiq** [comment]
Maybe its something with game client(Sunwell.pl). I started playing there with my friend and we both have same issue on different ElvUI git versions. After moving cursor in place where is hidden bar that error is showing up.

**Comment by Apollyonn** [comment]
Get the latest version, we also don't support old versions of this addon
