### ISSUE TITLE
Stance bar keybinding

### ISSUE THREAD

**Issue by TheRealestMcCoy** [ElvUI-WotLK/ElvUI#548]
**Description**
Stance bar keybinds not updating like should. When rebinding. Also not showing new Keybind

**Version Number**
5.43

**Steps to Reproduce**

1. Step 1 Rebind a stance bar
2. Step 2 default stays showing even if you use escape
3. Step 3 
4. Step 4

**Expected Behavior**
When you in elvui keybind mode and scroll over any bar it shows current keybind pressing escape should clear all keybinds on that action slot. Applting a new bind should update the keybind text.

**Actual Behavior**
Escape did not clear bind wow default bind had to remove from wow keybinds menu. Adding a bind worked, Had to go into wow keybinds to remove old one. Keybind info not showing.

**Only ElvUI Enabled**

**Blizzard Issue?**
Had a similar issue with the 5.4.8 version for mop.

**Additional Information**

**Error Log**

```

```
https://gyazo.com/d167cfc11c5c91f348161368042f7c0b

**Comment by Apollyonn** [comment]
https://gyazo.com/a93f1e6cc3c618fd117778c9a6f918db

**Comment by TheRealestMcCoy** [comment]
https://gyazo.com/2d682afb9b51fe6cc3de3cc536e35b79

**Comment by TheRealestMcCoy** [comment]
https://gyazo.com/82751b84914216289b7240fb8115f917
https://gyazo.com/ee009fd0f875fa089fa9b7cbc0707af0

**Comment by TheRealestMcCoy** [comment]
i have no addons on but elvui and it does not show the keybind

**Comment by TheRealestMcCoy** [comment]
https://gyazo.com/7eacf04c86ce9b3431eb86ca66d07395
all others are showing fine

**Comment by TheRealestMcCoy** [comment]
maybe it has to do with the shadowburn server???

**Comment by TheRealestMcCoy** [comment]
rolled back to 5.39 and its fine so its a bug some where with new update

**Comment by TheRealestMcCoy** [comment]
https://gyazo.com/7089ebd0cb89e7258d457a55351587e0
Proof its a bug

**Comment by Apollyonn** [comment]
fixed in https://github.com/ElvUI-WotLK/ElvUI/commit/6328777d85373f5cc5fb7a39eb2d471e84ec3226

**Comment by TheRealestMcCoy** [comment]
@Apollyonn there is still a issue with this i tried it but now it binds it but if i use the bind it wont do anything and the bind text is offset to the right so say i have 2 auras/stance button and i macro stance 1 to say f1 it looks like its ontop of stance 2 and stance 2 bind is off to the right of stance 2

**Comment by Apollyonn** [comment]
try now

**Comment by Apollyonn** [comment]
https://github.com/ElvUI-WotLK/ElvUI/commit/7935e54b23d71647f7cc0ca2c389b77e7865249d

**Comment by TheRealestMcCoy** [comment]
Works now thanks. Also another question i noticed in this one all items in the bag have the color border for quality can it be turned off or changed to only do uncommon= the white part annoys me. I know the MoP one dosent do white or common quality items?
