### ISSUE TITLE
Problem with addon TradeSkillMaster and ElvUI 

### ISSUE THREAD

**Issue by Vitoshka** [ElvUI-WotLK/ElvUI#550]
**Description**
When I enter the game this errors appears

**Version Number**
5.43

**Additional Information**
Addon [TradeSkillMaster](https://github.com/Yoshiyuka/TradeSkillMaster) for 3.3.5a

**Error Log**
1x TradeSkillMaster-v2.8\Core\Modules.lua:242: attempt to call method 'RegisterSyncCallback' (a nil value)
...deSkillMaster_Crafting\TradeSkillMaster_Crafting.lua:110: in function `RegisterModule':
...deSkillMaster_Crafting\TradeSkillMaster_Crafting.lua:56: in function <...deSkillMaster_Crafting\TradeSkillMaster_Crafting.lua:45>:
(tail call): ?:
<in C code>: ?
<string>:"safecall Dispatcher[1]":9: in function <[string "safecall Dispatcher[1]"]:5>
(tail call): ?:
AceAddon-3.0-12 (ElvUI):558: in function `EnableAddon'
AceAddon-3.0-12 (ElvUI):651: in function <...AddOns\ElvUI\Libraries\AceAddon-3.0\AceAddon-3.0.lua:636>
<in C code>: in function `LoadAddOn'
Interface\FrameXML\UIParent.lua:235: in function `UIParentLoadAddOn':
Interface\FrameXML\UIParent.lua:258: in function `CombatLog_LoadUI':
Interface\FrameXML\UIParent.lua:482: in function <Interface\FrameXML\UIParent.lua:454>:

  ---

1x ...ns\TradeSkillMaster_Crafting\Modules\CraftingGUI.lua:216: attempt to call global 'SpellBook_UpdateProfTab' (a nil value):
...ns\TradeSkillMaster_Crafting\Modules\CraftingGUI.lua:56: in function <...ns\TradeSkillMaster_Crafting\Modules\CraftingGUI.lua:20>:
(tail call): ?:
<in C code>: ?
<string>:"safecall Dispatcher[1]":9: in function <[string "safecall Dispatcher[1]"]:5>
(tail call): ?:
AceAddon-3.0-12 (ElvUI):558: in function `EnableAddon'
AceAddon-3.0-12 (ElvUI):571: in function `EnableAddon'
AceAddon-3.0-12 (ElvUI):651: in function <...AddOns\ElvUI\Libraries\AceAddon-3.0\AceAddon-3.0.lua:636>
<in C code>: in function `LoadAddOn'
Interface\FrameXML\UIParent.lua:235: in function `UIParentLoadAddOn':
Interface\FrameXML\UIParent.lua:258: in function `CombatLog_LoadUI':
Interface\FrameXML\UIParent.lua:482: in function <Interface\FrameXML\UIParent.lua:454>:

  ---

1x TradeSkillMaster_Crafting-v2.5\Modules\Sync.lua:33: attempt to index field 'Sync' (a nil value)
TradeSkillMaster-v2.8\Core\ErrorHandler.lua:406: in function <...erface\AddOns\TradeSkillMaster\Core\ErrorHandler.lua:404>
(tail call): ?:
TradeSkillMaster_Crafting-v2.5\Modules\Sync.lua:26: in function `callback'
TradeSkillMaster-v2.8\Util\Delay.lua:30: in function <TradeSkillMaster\Util\Delay.lua:18>

Locals:
(*temporary) = <function> @ TradeSkillMaster\Core\ErrorHandler.lua:395:
tsmStack = <table> {
 1 = "TSM_Crafting.Sync:BroadcastTradeSkillData(true)"
}
FormatTSMStack = <function> @ TradeSkillMaster\Core\ErrorHandler.lua:357:
obj = <table> {
 SetDefaultModuleLibraries = <function> @ ElvUI\Libraries\AceHook-3.0\AceHook-3.0.lua:100:
 Enable = <function> @ ElvUI\Libraries\AceHook-3.0\AceHook-3.0.lua:100:
 NewModule = <function> @ ElvUI\Libraries\AceHook-3.0\AceHook-3.0.lua:100:
 Callback = <function> @ ElvUI\Libraries\AceHook-3.0\AceHook-3.0.lua:100:
 EnableModule = <function> @ ElvUI\Libraries\AceHook-3.0\AceHook-3.0.lua:100:
 modules = <table> {}
 GetModule = <function> @ ElvUI\Libraries\AceHook-3.0\AceHook-3.0.lua:100:
 IterateEmbeds = <function> @ ElvUI\Libraries\AceHook-3.0\AceHook-3.0.lua:100:
 IsModule = <function> @ ElvUI\Libraries\AceHook-3.0\AceHook-3.0.lua:100:
 baseName = "TradeSkillMaster_Crafting"
 defaultModuleLibraries = <table> {}
 ProcessQueue = <function> @ ElvUI\Libraries\AceHook-3.0\AceHook-3.0.lua:100:
 OpenTradeSkill = <function> @ ElvUI\Libraries\AceHook-3.0\AceHook-3.0.lua:100:
 SetEnabledState = <function> @ ElvUI\Libraries\AceHook-3.0\AceHook-3.0.lua:100:
 ProcessTradeSkills = <function> @ ElvUI\Libraries\AceHook-3.0\AceHook-3.0.lua:100:
 enabledState = true
 BroadcastTradeSkillData = <function> @ ElvUI\Libraries\AceHook-3.0\AceHook-3.0.lua:100:
 OnEnable = <function> @ ElvUI\Libraries\AceHook-3.0\AceHook-3.0.lua:100:
 moduleName = "Sync"
 GetName = <function> @ ElvUI\Libraries\AceHook-3.0\AceHook-3.0.lua:100:
 defaultModuleState = true
 Disable = <function> @ ElvUI\Libraries\AceHook-3.0\AceHook-3.0.lua:100:
 IterateModules = <function> @ ElvUI\Libraries\AceHook-3.0\AceHook-3.0.lua:100:
 name = "TSM_Crafting_Sync"
 SetDefaultModulePrototype = <function> @ ElvUI\Libraries\AceHook-3.0\AceHook-3.0.lua:100:
 IsEnabled = <function> @ ElvUI\Libraries\AceHook-3.0\AceHook-3.0.lua:100:
 orderedModules = <table> {}
 SetDefaultModuleState = <function> @ ElvUI\Libraries\AceHook-3.0\AceHook-3.0.lua:100:
 DisableModule = <function> @ ElvUI\Libraries\AceHook-3.0\AceHook-3.0.lua:100:
}
name = "BroadcastTradeSkillData"
TrackPopStack = <function> @ TradeSkillMaster\Core\ErrorHandler.lua:395:
v = <function> @ TradeSkillMaster_Crafting\Modules\Sync.lua:24:

  ---

**Comment by Loaal** [comment]
Error not related to ElvUI.
