### ISSUE TITLE
Buggy Raid Frames in BGs

### ISSUE THREAD

**Issue by CharlZG** [ElvUI-WotLK/ElvUI#552]
**Description**

Not showing all (raid) frames in battle grounds.

**Version Number**

5.43

**Steps to Reproduce**

1. Enter BG
2. That's all ;)

**Expected Behavior**

All raid frames should appear on the screen in BGs, the frames are set up correctly (works perfectly in manually created raids, be it 10 or 25) 

**Actual Behavior**

ElvUi is not showing all the raid frames in BGs.

**Only ElvUI Enabled**

Keeps doing the same.

**Blizzard Issue?**

Blizzard is showing the raid members as it should, it's just an ElvUi issue.

**Additional Information**

I set up ElvUi as healer.

**Error Log**

```

```

**Comment by kinappy** [comment]
I'm seeing this issue also.

If I join Wintergrasp, only 10 raid frames are shown. Sometimes it might change to 40 later in the battle but not often.

**Comment by kinappy** [comment]
I noticed this is only if I port into Wintergrasp. If I'm already in Wintergrasp when the battle starts then the raid frames are ok.

**Comment by kinappy** [comment]
![image](https://user-images.githubusercontent.com/25764850/50285507-ab5cd180-045c-11e9-92f0-3f54d731bcfd.png)
Smart Raid Filter seems to be the problem for me, unchecking it solved the BG issue

**Comment by snwflake** [comment]
Smart Raid Filter is disabled for me, but I still experience this issue.
It's especially present if raid thresholds are reached (10 to 25, 25 to 40 converstion). The frames just dissapear.
Not sure if this is the same bug.

**Comment by Bunny67** [comment]
check now
