### ISSUE TITLE
DK Runes

### ISSUE THREAD

**Issue by zenots** [ElvUI-WotLK/ElvUI#553]
**Description**

Sometimes after using runes, they stay filled when not usable. AKA: I obliterate twice, have no runes but it shows the runes as available, which shows obliterate as off "cooldown" despite not being usable.

Has only happened with frost+unholy runes for me.

**Version Number**

5.43

**Steps to Reproduce**

Happens when just doing frost DK rotation
Obliterate Obliterate Pestilence Bloostrike
Obliterate Obliterate Obliterate

**Expected Behavior**

The runes should "unfill" when going on cooldown

**Actual Behavior**

The runes stay "filled" despite being on cooldown and unusable.

**Only ElvUI Enabled**

**Blizzard Issue?**

**Additional Information**

**Error Log**

```

```

**Comment by Zidras** [comment]
Just spent 5 mins on a dummy doing fdk rotation. Runes working properly.

**Comment by solarblazin** [comment]
Hi!

https://www.youtube.com/watch?v=WSq8B_z-jUE

Runes get stuck filled and on next rune power update they get their timers updated.
