### ISSUE TITLE
Name plates

### ISSUE THREAD

**Issue by Frenlock** [ElvUI-WotLK/ElvUI#558]
**Description**
Name plates visual bugs

**Version Number**
5.45

**Steps to Reproduce**
1. Enter in combat just with one enemy target 
2. Do some dots on it
3. Look at other nearest enemy nameplates

**Expected Behavior**
It shoud show dots , damage or cast bar just on enemy you are in combat with .

**Actual Behavior**
It does show dots , damage or cast bar on all nearest enemy namaplates instead of just one with you are in combat.
![wowscrnshot_090618_135456](https://user-images.githubusercontent.com/24683355/45154599-c32b8500-b1e0-11e8-8b36-ab12a8823295.jpg)

**Only ElvUI Enabled**
Yes , only elv-ui enabled .

**Blizzard Issue?**
Default nameplates doesn't show dots or damage .

**Additional Information**

**Error Log**

```

```

**Comment by Apollyonn** [comment]
I tried to reproduce it but i can't. Does it happen all the time?

**Comment by Frenlock** [comment]
almost all the time when you are facing multiple nearest enemy and you enter in combat just with one
