### ISSUE TITLE
AFK error

### ISSUE THREAD

**Issue by henryman93** [ElvUI-WotLK/ElvUI#561]
**Description**
When leaving AFK screen, it gives error.

**Version Number**
5.45

**Steps to Reproduce**
1. Go AFK
2. Go out of AFK status

**Expected Behavior**
No error

**Actual Behavior**
Error  in Description

**Only ElvUI Enabled**
I haven't tested with only ElvUI. 

**Blizzard Issue?**
no

**Additional Information**
I don't know how to 100% trigger this error. I've been able to do it almost consistently in Dalaran.

**Error Log**
```
Message: Interface\AddOns\ElvUI\modules\misc\afk.lua:203: attempt to call global 'RemoveExtraSpaces' (a nil value)
Time: 09/15/18 18:48:22
Count: 13
Stack: [C]: in function `RemoveExtraSpaces'
Interface\AddOns\ElvUI\modules\misc\afk.lua:203: in function <Interface\AddOns\ElvUI\modules\misc\afk.lua:198>
```

**Comment by TheRealestMcCoy** [comment]
had the same issue

**Comment by Tomelyr** [comment]
I dunno why, but RemoveExtraSpaces is a function from the Blizzard Chat UI, which itself just wraps string.gsub.
i dunno where the error is tbh, but since it's only in this one file, i would suggesting changing line 203 to
`arg1 = string.gsub(arg1, "     +", "    ")`

**Comment by henryman93** [comment]
So far with this fix I haven't encountered any issues :)

**Comment by Bunny67** [comment]
this fixed in next release
