### ISSUE TITLE
AFK chat panel not working

### ISSUE THREAD

**Issue by henryman93** [ElvUI-WotLK/ElvUI#563]
**Description**
AFK mode chat panel (guild and whispers) no longer appear.

**Version Number**
5.45

**Steps to Reproduce**
1. Go AFK mode
2. Receive whispers and/or guild messages

**Expected Behavior**
Guild/Whisper messages should appear in AFK mode

**Actual Behavior**
No chat panel appears

**Only ElvUI Enabled**
Only ElvUI enabled

**Blizzard Issue?**
No

**Additional Information**
Please see issue 56: https://github.com/ElvUI-WotLK/ElvUI/issues/56
The AFK chat panel appeared in previous iteratations of the addon.

**Error Log**
NA

**Comment by Loaal** [comment]
Should be fixed in 6.0 release.
