### ISSUE TITLE
Баг рейд фреймов.

### ISSUE THREAD

**Issue by freesay** [ElvUI-WotLK/ElvUI#565]
Если включить информационную панель в на рейд фреймах, то случается баг. Высота рейдфрейма сбивается, становится очень маленькой. На скриншоте, полагаю, будет понятней.

Номер версии 5,45

1. Установить галочку "вкл" для информационной панели на рейд фреймах (проверял только на 25 игроков)
2. Вступить в рейдовую группу. 
3. Свернуть игру. 
4. подождать некоторое время, пока не произойдут какие либо изменения в рейде (перемещения, кик, лив, инвайнт)
5. Развернуть игру
6. Наблюдать баг

Рейд фрейм игрока должен иметь высоту равную заданному значению (в данном случае 25, но эффект сохраняется при любом значении).

Высота рейд фрейма игрока, и всех тех, кто попадает в рейд после бага, становится ничтожно малой. 

Баг появляется всегда, будь то соло элв, или с набором аддонов.

Если выйти из мира, находясь в рейде с пойманым багом, а затем вновь войти в игру, то все рейд фреймы принимают высоту забагованного фрейма.

![wowscrnshot_100918_131528](https://user-images.githubusercontent.com/19500175/46663846-d490f400-cbc7-11e8-8f4b-a5bb5b33fc58.jpg)
![wowscrnshot_100918_131604](https://user-images.githubusercontent.com/19500175/46663847-d490f400-cbc7-11e8-85dd-d30609d5e3c2.jpg)
![wowscrnshot_100918_132153](https://user-images.githubusercontent.com/19500175/46663848-d490f400-cbc7-11e8-856a-5a2af041049b.jpg)

**Comment by Bunny67** [comment]
fixed in next release(6.xx)
