### ISSUE TITLE
Party Targets/Pets

### ISSUE THREAD

**Issue by TheRealestMcCoy** [ElvUI-WotLK/ElvUI#568]
**Description**

I have a issue with party targets appearing when i join a party. I have made sure it is not enabaled but it still shows up.

**Version Number**

**Steps to Reproduce**

1. Step 1 Join Party
2. Step 2
3. Step 3
4. Step 4

**Expected Behavior**

**Actual Behavior**

**Only ElvUI Enabled**

**Blizzard Issue?**

**Additional Information**

**Error Log**

```

```

**Comment by Noob1e** [comment]
I was just about the write same bug. I have unchecked party pets but it still shows the pet frames.

**Comment by Loaal** [comment]
Should be fixed in 6.0 release.
