### ISSUE TITLE
2 map errors that still exist

### ISSUE THREAD

**Issue by Frenlock** [ElvUI-WotLK/ElvUI#570]
**Description**

1.Description here : https://github.com/ElvUI-WotLK/ElvUI/issues/447
2.Quests location runs out of the map borders .
**Version Number**
5.45

**Steps to Reproduce**

1. https://github.com/ElvUI-WotLK/ElvUI/issues/447
2. Quests location runs out of the map borders .

**Expected Behavior**

**Actual Behavior**

**Only ElvUI Enabled**
Yes

**Blizzard Issue?**

**Additional Information**

Screenshots
![1](https://user-images.githubusercontent.com/24683355/47190719-c5d6d980-d34b-11e8-977f-2293b3de18fc.jpg)
![2](https://user-images.githubusercontent.com/24683355/47190766-f880d200-d34b-11e8-8a9e-4967e65a1fc4.jpg)

**Error Log**

```

```

**Comment by Bunny67** [comment]
check in next release(6.xx)
