### ISSUE TITLE
Bag sorting getting stuck

### ISSUE THREAD

**Issue by Goregrin** [ElvUI-WotLK/ElvUI#573]
**Description**
When using bag sorting, it gets stuck almost every time at one item which stays gray.
Switching bags sorts this issue.

**Version Number**

**Steps to Reproduce**

1. Have things in bag...
2. Sort bags
3. Elvui says in chat that there is an error
4. Bag sorting is stuck

**Expected Behavior**

**Actual Behavior**

**Only ElvUI Enabled**

**Blizzard Issue?**

**Additional Information**

**Error Log**

```

```

**Comment by Ka0tik** [comment]
Yes this is pretty annoying, the sort script prints in chat that it is confused and is still running when trying to run several times when it gets stuck.

**Comment by Bunny67** [comment]
check in next release(6.xx)
