### ISSUE TITLE
Raid member sorting & hide self

### ISSUE THREAD

**Issue by Chaoticx** [ElvUI-WotLK/ElvUI#574]
**Description**

When in raid party with a few member (2, as  it is arena 3x3) it sorts party members inverted (like party1 is in bottom and party2 in top). Not serous issue, but switching from blizzard ui it really screws macros. I've checked all the options and couldn't solve this.
Also cant hide myself from raid party window  (and yes, i've checked that option, reloaded ui and such). When in normal party everything works fine, as my frame is hidden, but not in raid.

**Version Number**

 5.45

**Steps to Reproduce**

**Expected Behavior**
It shoul sort party members as bblizzard frame does (party1 goes 1st, then party2 2nd and so on), also should hide my frame from raid party window

**Actual Behavior**
it sorts member inverted, also shows my frame 

**Only ElvUI Enabled**

**Blizzard Issue?**

**Additional Information**

**Error Log**

```

```

**Comment by Bunny67** [comment]
check now
