### ISSUE TITLE
[Bug] Nameplates 'clickbox' not resizing

### ISSUE THREAD

**Issue by Zidras** [ElvUI-WotLK/ElvUI#577]
**Description**
Nameplates clickbox (area that makes nameplate selectable) is not updating with the width of the Name or Health Bar.
This is VERY noticeable with friendly namplates with healthbar disabled, to the point I can select the unit without even having the mouse near it (makes it unplayable to click objects like Food on the floor, portals etc).

**Version Number**
6.04

**Steps to Reproduce**
1. Enable nameplates (friendly or enemy)
2. Mouse highlights nameplate way too far from actual unit

**Expected Behavior**
Nameplate hitbox width must match name/healthbar width. See screenshot of DocsNameplates for proper behaviour (see white drawn corners, those are the default clickboxes):
![image](https://user-images.githubusercontent.com/10605951/55274857-314aad00-52d5-11e9-8530-96bb6fba8d44.png)
 

**Actual Behavior**
Mouse highlights nameplate too far away (see screenshot of elvui nameplates; dot was the mouse location, white brackets for rough position of clickbox of highlighted unit)
![image](https://user-images.githubusercontent.com/10605951/55274920-1b89b780-52d6-11e9-9fc7-99beccf6beb0.png)

**Only ElvUI Enabled**
Yes

**Blizzard Issue?**
Blizzard is clueless on nameplates in wotlk.

**Additional Information**
I can provide DocsNameplate files if it helps coding a fix for this nuisance

**Error Log**
No error

**Comment by henryman93** [comment]
Additional info: problem aggravated the further away your camera is.

**Comment by henryman93** [comment]
Updated description with version 6.00

**Comment by Zidras** [comment]
Fixed in "Nameplate" development branch (can't pinpoint the exact commit). When merged to master, I reckon this issue can be closed satisfactorily
![image](https://user-images.githubusercontent.com/10605951/69465743-e147bb80-0d79-11ea-8804-fc53c5066c34.png)
