### ISSUE TITLE
Сортировка вещей

### ISSUE THREAD

**Issue by street-racer777** [ElvUI-WotLK/ElvUI#580]
**Description**

При нажатии на кнопку сортировки сумок/банка, с вероятностью примерно 30-40% один из айтемов станет серым и дальнейшие сортировки, включая эту, будут невозможны. Предмет становится некликабельным и неактивным, его нельзя переместить вручную. Решает такую проблему только перезаход за персонажа(логаут).

**Version Number**

5.45

**Steps to Reproduce**

Помогает только логаут.

**Comment by Bunny67** [comment]
Проверь в следующей версии(6.xx)

**Comment by Loaal** [comment]
duplication #573
