### ISSUE TITLE
Group size not computing infopanel on first instance

### ISSUE THREAD

**Issue by bcfrutuozo** [ElvUI-WotLK/ElvUI#582]
**Description**
The group frame is not calculating the last added group player frame height correctly when the infopanel is enable for group frames

**Version Number**
5.45

**Steps to Reproduce**

1. Step 1 - Log in and enable infopanel on groupframe
2. Step 2 - Logout
3. Step 3 - Log in again and invite a player (the newly added partner frame doesn't compute the infopanel size)
4. Step 4 - Invite another player and verifies that the newly generated frame is misscalculated, while the first one corrects itself on update.

**Expected Behavior**
All partner frames from the party frames should calculate the infopanel size if it's enabled.

**Actual Behavior**
The newly added partner frame from the group frame doesn't calculate the infopanel size.

**Only ElvUI Enabled**
This bug happens only with ElvUI enabled.

**Blizzard Issue?**
This issue occurs only on the ElvUI interface.

**Additional Information**
Print screen uploaded with the image of the error. And how it happens: https://imgur.com/a/zzYw3oO

**Error Log**
There's an error log. Probably just a calculation is missing when create the partner frame from the first time.

**Comment by Bunny67** [comment]
fixed in next release(6.xx)
