### ISSUE TITLE
 Tooltip on Buttons not working (DMG with Dr.Damage and ElvUI)

### ISSUE THREAD

**Issue by Roxas2712** [ElvUI-WotLK/ElvUI#583]
**Description**
 Tooltip on Buttons not working

**Version Number**
 5.4.5 

**Steps to Reproduce**
1. Had Dr. Damage before ElvUI. Worked fine.
2. Donwloaded ElvUI  and build up my UI. (Looks cool btw - thank you)

**Expected Behavior**
The Tooltip on Buttons should also work even if i have now ElvUI 

**Actual Behavior**
Dr. Damage is working fine. The normal tooptip is also updated. But somehow it's not working with the Tooltip on Buttons. With Bartender for example it was running smoothly.

**Only ElvUI Enabled**
Problem seems to come somehow from ElvUI

Thank you!^^
```

**Comment by Loaal** [comment]
Can't reproduce
![image](https://user-images.githubusercontent.com/590348/63808609-0a96ae00-c929-11e9-8503-289191d4d6b2.png)
