### ISSUE TITLE
Нет панелей команд

### ISSUE THREAD

**Issue by FR3MY** [ElvUI-WotLK/ElvUI#584]
**Description**
Нет панелей команд

**Version Number**
5.45

**Only ElvUI Enabled**
Включён только ElvUi

Вот скриншот 

![image](https://user-images.githubusercontent.com/52298121/60298371-981f4700-9954-11e9-84d6-e0bd21d35c44.png)

**Comment by vismutplus** [comment]
Для этого сервера есть другой ElvUI Сделаный на базе того, что тут. Поищи.
Тот что тут не будет работать на Сирусе

**Comment by Bunny67** [comment]
Эта версия не поддерживает Сурус. Будет плагин, который исправляет ошибки на Сирусе.
