### ISSUE TITLE
Конфликтует со многими плагинами.

### ISSUE THREAD

**Issue by Merfinx** [ElvUI-WotLK/ElvUI#587]
В новой 6.0 версии при логине Ельв начинает конфликтовать со многими плагинами (Enhanced, EverySecondsCount etc.) Прикладываю архив с самими ошибками.

Также некорректно поддерживает LBF на Action Bars, с любым скином от Button Facade иконки становятся затемненными. Приложил скриншот.

Плюс ко всему файлик с включенными / отключенными аддонами
https://www.mediafire.com/file/oz8j4mx9hix1vu1/Errors.rar/file
https://www.mediafire.com/view/eegddak1qab1jdb/WoWScrnShot_081419_164341.jpg/file
https://www.mediafire.com/file/l8io76nalvvuqf8/AddOns.txt/file

**Comment by Bunny67** [comment]
Поддержку лбф поправил, а плагины еще не правились под новую версию. К релизу все будут обновлены
