### ISSUE TITLE
Tooltip Gearscore off-center

### ISSUE THREAD

**Issue by rokpusnik** [ElvUI-WotLK/ElvUI#592]
new version has some weird behaviour in the tooltips, offsetting and moving certain texts out of frame... but only sometimes

![image](https://user-images.githubusercontent.com/49006425/63226528-d3165c00-c1da-11e9-9f0b-02fefa66922e.png)

![image](https://user-images.githubusercontent.com/49006425/63226530-e0334b00-c1da-11e9-8c8a-3202e82322ab.png)

![image](https://user-images.githubusercontent.com/49006425/63226545-330d0280-c1db-11e9-814e-0cf2c30a52bd.png)

![image](https://user-images.githubusercontent.com/49006425/63226552-4ddf7700-c1db-11e9-8242-920a3808cb28.png)

**Comment by freesay** [comment]
Подтверждаю. Баг из прошлой версии, но в этой срабатывает гораздо чаще. Возникает из-за проверки спека и итемлвл'а через шифт. 
![WoWScrnShot_082219_204756](https://user-images.githubusercontent.com/19500175/63537353-33c8d000-c51e-11e9-8369-9dce86648718.jpg)
![WoWScrnShot_082219_204758](https://user-images.githubusercontent.com/19500175/63537354-33c8d000-c51e-11e9-99dd-8bdc01142505.jpg)

**Comment by rokpusnik** [comment]
seems to happen when player's name is shorter than their guild + guild rank combined
