### ISSUE TITLE
Role icons on raidframe

### ISSUE THREAD

**Issue by henryman93** [ElvUI-WotLK/ElvUI#594]
**Description**
Missing role icons on raidframe

**Version Number**

 6.00

**Steps to Reproduce**

1. /ec > Unitframes > Raid

**Expected Behavior**

Previous version 5.46 had this option (even though it wasn't working, the 'display frame' did show the template with role icon)

**Actual Behavior**

Option no longer present

**Only ElvUI Enabled**

Only ElvUI 6.00

**Blizzard Issue?**

No

**Additional Information**

![image](https://user-images.githubusercontent.com/10605951/63304451-ffb19d00-c2da-11e9-9869-fd8baed2dbe8.png)

Posted bug report since idk if it was overlooked or intended to drop the feature.

**Error Log**

```

```

**Comment by Apollyonn** [comment]
Role Icons only for party frames in 3.3.5.
