### ISSUE TITLE
Не все ссылки в чате обрабатываются

### ISSUE THREAD

**Issue by freesay** [ElvUI-WotLK/ElvUI#596]
Версия 6.00
Перед установкой кэш, втф и логи вычистил.
Из аддонов только гс, рекаунт, дбм. 
Не обрабатывает некоторые ссылки как с включенными, так и с выключенными аддонами.
![WoWScrnShot_082019_212802](https://user-images.githubusercontent.com/19500175/63375215-00f2d080-c394-11e9-9a83-176b7915f42e.jpg)
![WoWScrnShot_082019_212859](https://user-images.githubusercontent.com/19500175/63375216-018b6700-c394-11e9-816d-b53f8ae07931.jpg)

В прошлой версии все ссылки отлично обрабатывались.

**Comment by Bunny67** [comment]
Ссылки типа www. отключили, возможно вернем.
