### ISSUE TITLE
Скрытие фрейма игрока.

### ISSUE THREAD

**Issue by freesay** [ElvUI-WotLK/ElvUI#597]
В прошлых версиях элва, можно было отметить галочкой пункт для скрытия фрейма игрока вне боя и с фулл хп. Сейчас этой галочки нет. Не уверен, существует ли она еще в актуальных версиях аддона, но, на мой взгляд, галочку такую добавить стоило бы. Спасибо.

**Comment by Bunny67** [comment]
![image](https://user-images.githubusercontent.com/5816685/63441695-803adf80-c43a-11e9-9778-0c01eac67901.png)
Вкладка "Затухание"

**Comment by freesay** [comment]
Не работает. Все время появляется фрейм от любого дуновения ветра.

**Comment by freesay** [comment]
Знаю, что не тикет, но не представляю как иначе сформулировать. Появляется совершенно рандомно, иногда фрейм мигает, иногда с бафами, иногда без баффов, не всегда сразу появляется фрейм при начале каста, в общем, как-то вот так. Живет фрейм свободной жизнью.

**Comment by Bunny67** [comment]
Щас работает как и раньше, только появилась проверка маны. Возможно из за нее и появляется

**Comment by Bunny67** [comment]
Все же походу была проблема :) Проверь теперь :)
