### ISSUE TITLE
Blizzard reviews Addons conditions

### ISSUE THREAD

**Issue by gbaoye** [ElvUI-WotLK/ElvUI#603]
one of the most important of which is whether your Addons take up a lot of visual space

**Comment by Apollyonn** [comment]
I don't understand what you mean.

**Comment by gbaoye** [comment]
I'm glad someone can see this sentence, the game, we care about immersion, not for the result and lose entertainment, we want is beautiful and concise, customizable, to those who pursue efficiency, my English is not good

**Comment by Apollyonn** [comment]
I still don't understand what you want. Give an example.

**Comment by gbaoye** [comment]
Well, I said straight, for the final result of the novice navigation settings, too occupied my sight, the premise of efficiency is a sense of pleasure, should not be because of the constant pursuit of efficiency and gradually ignore the quality of the picture, computer games, has always been entertainment first, picture quality second. Now that this tendency is changing, this is not Blizzard's original intention.

**Comment by gbaoye** [comment]
If someone is looking for efficiency and takes the line of sight, for example, PVP efficiency, team dungeon efficiency, they should customize it themselves, not add it in the default option

**Comment by gbaoye** [comment]
Think of Steve Jobs. What he would do.

**Comment by Crumdidlyumshis** [comment]
Are you some kinda bad poet or just using a bad translator?
