### ISSUE TITLE
lootroll add for zhCN.

### ISSUE THREAD

**Issue by coolaken** [ElvUI-WotLK/ElvUI#606]
loot_roll.lua
----------------------------
or locale == "zhCN" and {
	["(.*)自动放弃了：(.+)，因为他无法拾取该物品$"] = "pass",
	["(.*)自动放弃了：(.+)，因为她无法拾取该物品$"] = "pass",
	["(.*)放弃了：(.+)"] = "pass",
	["(.*)选择了贪婪取向：(.+)"] = "greed",
	["(.*)选择了需求取向：(.+)"] = "need",
	["(.*)选择了分解取向：(.+)"] = "disenchant",
}
---------
add this for zhCN support.

**Comment by Loaal** [comment]
Thanks :+1:
