### ISSUE TITLE
Postal icons squished.

### ISSUE THREAD

**Issue by truekripp** [ElvUI-WotLK/ElvUI#607]
Not sure if it's anywhere else, but this happens while using Postal. It was fixed for a short period and now it's back to being squished.
https://imgur.com/a/GMeoUm4

Version: WotLK ElvUI Release 6.0.1

Figure out what you did last time it was fixed - I have no idea how, but you fixed it in less than an hour or so(pretty sure it was in 6.0.0).

**Comment by rokpusnik** [comment]
fixed in master branch, hasn't been pushed to release yet

**Comment by rokpusnik** [comment]
#600
