### ISSUE TITLE
Bugged Player Icons on Map

### ISSUE THREAD

**Issue by truekripp** [ElvUI-WotLK/ElvUI#608]
Small dots on the map appears as weird buggy squares.
https://imgur.com/a/ZxgbxCn

How's it's supposed to be: 
Circles colored by class, that blinks dependent on combat behavior and/or death behavior.

**Comment by rokpusnik** [comment]
I believe a temporary fix for that is to disable group member icons on Mapster, and I think this has been reported somewhere, tho I can't find it now

**Comment by truekripp** [comment]
Thanks. I'll do so.

**Comment by Bunny67** [comment]
fix in ElvUI_Enhanced
