### ISSUE TITLE
Timers will not show on Debuffs/Buffs on UnitFrame no matter what I do

### ISSUE THREAD

**Issue by sky1700** [ElvUI-WotLK/ElvUI#610]
**Description**
Debuffs/buffs will only show like this on Unitframes for both myself and raid/party members
https://gyazo.com/499993e988d1bb72d23aa79f1543c78c I cannot get text to show on this

**Version Number**
6.01

**Steps to Reproduce**
Not really sure what to put here, I've tried fresh installs of Elvui, I've even tried wiping my WTF folder and doing a completely fresh addon setup. This issue persists through all of it.

**Expected Behavior**
The buff icon should show a text timer.

**Actual Behavior**
The buff icon only shows the icon and a cooldown "clock" effect

**Only ElvUI Enabled**
Yes, this issue continues to occur when only ElvUI is enabled

**Blizzard Issue?**

N/A

**Additional Information**

**Error Log**

```

```

**Comment by Zidras** [comment]
That happens when the icon is too small. If size override is set at 0, reduce number of buffs per row. If you have size override, increase its value until a timer shows.
![image](https://user-images.githubusercontent.com/10605951/71702166-c67b5480-2dc5-11ea-97a8-b23511f4db71.png)
