### ISSUE TITLE
Проблема с отображением текста

### ISSUE THREAD

**Issue by Vitoshka** [ElvUI-WotLK/ElvUI#613]
Текст вылазит за границы и накладывается друг на друга:

https://c.radikal.ru/c14/1908/dd/e096a155cab5.jpg

https://b.radikal.ru/b36/1908/bf/e8807817a195.jpg

https://a.radikal.ru/a29/1908/8d/9d3635b1544f.jpg

**Comment by Bunny67** [comment]
1-е исправлено, 2-3 особенность русского клиента
