### ISSUE TITLE
Casting Demonic Soulstone

### ISSUE THREAD

**Issue by Jezz96** [ElvUI-WotLK/ElvUI#614]
**Description**
When casting a Demonic Soulstone the Castbar is not visable and gives a LUA error

**Version Number**
6.01

**Steps to Reproduce**
1. Create a Soulstone
2. Cast Demonic Soulstone on anyone 
3. No CastBar appears and a LUA error is given

**Expected Behavior**
Should see a normal Castbar

**Actual Behavior**
There is no CastBar and instead you get a LUA error
![Wow_4ipjJ786yr](https://user-images.githubusercontent.com/54687946/63976437-3e98dd00-caa9-11e9-8777-daf95ec69622.jpg)

**Only ElvUI Enabled**
Yes

**Blizzard Issue?**
N/A

**Additional Information**
N/A

**Error Log**

```
Message: ...AddOns\ElvUI\Modules\UnitFrames\Elements\CastBar.lua:351: attempt to concatenate a nil value
Time: 08/29/19 22:08:09
Count: 1
Stack: [C]: ?
...AddOns\ElvUI\Modules\UnitFrames\Elements\CastBar.lua:351: in function `PostCastStart'
...face\AddOns\ElvUI\Libraries\oUF\elements\castbar.lua:201: in function <...face\AddOns\ElvUI\Libraries\oUF\elements\castbar.lua:115>
(tail call): ?

Locals: 
```

**Comment by Bunny67** [comment]
fix 606ef72
