### ISSUE TITLE
Проблема отображения цели в группе

### ISSUE THREAD

**Issue by Vitoshka** [ElvUI-WotLK/ElvUI#618]
Заметил проблему, когда я состою в группе и кто-то выбирает цель, то [слетают настройки](https://c.radikal.ru/c00/1909/3c/7b64f4d4f13e.jpg) мини-фрейма цели группы, что интересно, ползунок настройки находится на одном месте и, чтобы вернуть те настройки, которые были настроены заранее его нужно подвигать вперёд, назад, и всё [становиться на свои места](https://b.radikal.ru/b35/1909/87/41e2ec958f00.jpg), но так нужно делать каждый раз, когда вступаешь в группу.

**Comment by Bunny67** [comment]
Проверь теперь

**Comment by Vitoshka** [comment]
Всё работает нормально, спасибо
