### ISSUE TITLE
Проблема с itemlvl в тултипе и в ячейках вещей других персонажей (осмотр)

### ISSUE THREAD

**Issue by Vitoshka** [ElvUI-WotLK/ElvUI#619]
После последних обновлений, в тултипе (раздел Подсказка в Елве, в меню) перестал показываться цветовой itemlvl персонажа на которого навожу курсор (аддоном _Gearscore_ я не пользуюсь). 
Заметил также если просматривать **на других персонажах**, у которых есть трансмогрифицированные вещи, следующий визуальный баг, если  вещь трансмогрифицирована вещью, которая ниже по уровню, например персонаж трансмогрифицировал фиолетовые 277 сапоги синими сапогами 200, то при просмотре этого персонажа, у него, в ячейке сапоги будет отображаться 200 синий itemlvl, а не 277 фиолетовый. Когда я просматриваю **свои** трансмогрифицированные вещи, такого визуального бага не наблюдаю.

**Comment by Bunny67** [comment]
Это врятли можно исправить. То что API отдает, то и показывается.

**Comment by Vitoshka** [comment]
Что интересно он стал показываться с зажатым Shift? Это какое-то нововведение в ElvUi?

**Comment by Bunny67** [comment]
Он всегда показывает с зажатым шифтом. Остальное поправил в аддоне под сервер.
