### ISSUE TITLE
Дебаффы над неймплейтами (отображение кулдауна)

### ISSUE THREAD

**Issue by Suonu** [ElvUI-WotLK/ElvUI#620]
Можно ли вернуть как раньше, чтобы отображение было по часовой стрелкой, а не как сейчас только по вертикали или горизонтали
https://imgur.com/a/jMOXexb

**Comment by Bunny67** [comment]
раньше кд не было. скорее всего появится возможность такой кд  отключить

**Comment by Suonu** [comment]
ясно спасибо
