### ISSUE TITLE
Проблема с отображением подсказки

### ISSUE THREAD

**Issue by Vitoshka** [ElvUI-WotLK/ElvUI#622]
Периодически появляется [баг в тултипе](https://d.radikal.ru/d35/1909/14/a7bf9e03d2ed.jpg), когда навожу на другого персонажа курсор (не выделяя его в цель). Первый раз вот такой граф. баг (лишнее пространство). 
Второй раз когда навожу на этого же персонажа, это лишнее пространство исчезает и тултип отображается нормально.

**Comment by Vitoshka** [comment]
Также заметил подобный баг и когда навожу курсор на инфо-текст Гильдия у себя на левой панели.

**Comment by Vitoshka** [comment]
Проблема после последних обновлений не решилась, + помимо лишнего пространства в подсказке периодически съезжает также текст в сторону, вправо. Проверьте пож.

**Comment by Bunny67** [comment]
По подсказке ничего не менялось. Данный баг воспроизвести не получается.
