### ISSUE TITLE
Проблема с иконкой на кастбаре индикатора здоровья цели

### ISSUE THREAD

**Issue by Vitoshka** [ElvUI-WotLK/ElvUI#625]
Заметил [неправильное](https://c.radikal.ru/c13/1909/0a/5ea66fb9dbd3.jpg) отображение иконки кастуемого заклинания цели, она стала прямоугольная, то бишь вытянулась, хотя раньше была квадратная и не было искажений, можно это как то подкорректировать.

**Comment by Vitoshka** [comment]
Проблема после обновления [не решилась](https://b.radikal.ru/b15/1909/f2/3a254d6ee87e.jpg)

**Comment by Vitoshka** [comment]
Мобы были разные (те, которые что-то кастуют), иконка всё та же, **сплюснутая**

**Comment by Bunny67** [comment]
Терь должно быть норм.

Не заливай плиз скрины на радикал, их можно в сообщение добавлять
![image](https://user-images.githubusercontent.com/5816685/64630953-db8b3c80-d3fe-11e9-9b91-2820cd5dfb68.png)

**Comment by Vitoshka** [comment]
Протестировал после обновы, прямоугольник стал горизонтальный,
![WoWScrnShot_091119_012049](https://user-images.githubusercontent.com/30943063/64654870-258e1580-d433-11e9-9531-24bba10bded4.jpg)
прибл. линией выделил зону квадрата и видно насколько выходит за рамки иконка.

**Comment by Vitoshka** [comment]
Странно что раньше показывало именно равносторонний квадрат, а теперь только прямоугольник иконки, это может зависеть от игровых настроек Индикаторов здоровья?
