### ISSUE TITLE
Castbar of item won't show and generates lua error

### ISSUE THREAD

**Issue by henryman93** [ElvUI-WotLK/ElvUI#628]
**Description**

Happened while using item (from quest). Castbar of said item won't show and lua error.
Caused by Display Target enabled.

**Version Number**

6.01

**Steps to Reproduce**

1. Enable Player Castbar Display Target
2. Use item/world clickable that triggers castbar

**Expected Behavior**

Show item castbar

**Actual Behavior**

Lua error.

**Only ElvUI Enabled**

Reproductible with /luaerror on

**Blizzard Issue?**

No

**Additional Information**

More information from myself and another member on the comments below

**Error Log**

```
Message: ...AddOns\ElvUI\Modules\UnitFrames\Elements\CastBar.lua:351: attempt to concatenate a nil value
Time: 09/09/19 17:28:04
Count: 6
Stack: [C]: ?
...AddOns\ElvUI\Modules\UnitFrames\Elements\CastBar.lua:351: in function `PostCastStart'
...face\AddOns\ElvUI\Libraries\oUF\elements\castbar.lua:201: in function <...face\AddOns\ElvUI\Libraries\oUF\elements\castbar.lua:115>
(tail call): ?

Locals: 
```

**Comment by rokpusnik** [comment]
is it The Rokk's cooking quest in Outland? I've encountered something similar to this using those quest items before

**Comment by henryman93** [comment]
No, it was a collar from Alterac Valley quest and the irondeep clickable

**Comment by Apollyonn** [comment]
Is there any other place we can test this except Alterac Valley?

**Comment by henryman93** [comment]
I've an idea (untested) which are the repeatables of Argent Tournament (there are a few quests that give a usable quest item as well as a clickable that has a open time). I'll try to find conditions to reproduce this for debugging purposes and I'll post here. Thx

**Comment by henryman93** [comment]
ICC chests give same error

**Comment by henryman93** [comment]
@Apollyonn For debugging, you can reproduce with argent quest "You've done it this time, Kul", by opening the boxes to rescue Captive Aspirants. As soon as I click the box, lua error and no progressbar.
Also found the underlying cause of bug: Display target enabled on castbar 👍 Editing the main report
