### ISSUE TITLE
Channeled cast bar not showing during combat

### ISSUE THREAD

**Issue by Triksterism** [ElvUI-WotLK/ElvUI#631]
**Description**
When casting a channeled ability (Example: Volley), the castbar disappears after the first 'tick' -- The ability still works but the castbar is non-existant. -- I posted this same report a month ago and it was closed (seemingly someone thought it to be fixed, but it isn't).

**Version Number**
6.01 (Release as of 2 days ago)

**Steps to Reproduce**
1. /use !Volley
2. Click the ground where I wish to cast the ability
3. Ability begins to cast (with castbar showing)
4. Castbar disappears once it hits the first tick bar on the castbar
5. Ability still does damage (issue is purely visual).

**Expected Behavior**
Castbar should persist through every 'tick' of a channeled ability.

**Actual Behavior**
Castbar disappears after the first 'tick' of a channeled ability.

**Only ElvUI Enabled**
I can reproduce it when ElvUI is the only enabled addon.

**Blizzard Issue?**
I don't think so.

**Additional Information**
Here's a timestamped video of the issue: https://www.twitch.tv/videos/470803149?t=36m10s

**Error Log**

```

```

**Comment by Bunny67** [comment]
Is the bug still present?

**Comment by Triksterism** [comment]
It works now, thank you.
