### ISSUE TITLE
Changing font for nameplate debuffs doesnt actually change the font

### ISSUE THREAD

**Issue by Triksterism** [ElvUI-WotLK/ElvUI#632]
**Description**
I changed the nameplate debuff/buff fonts from "PT Sans Narrow" to "Expressway" (same font I use all throughout ElvUI but the font remains as "PT Sans Narrow"

**Version Number**
6.01 -- Latest update as of 2 days ago

**Steps to Reproduce**
1. Navigate to nameplate settings
2. Change font via dropdown to desired font
3. Watch debuffs/buffs on nameplate
4. Font has not changed

**Expected Behavior**
Font should change based on user's selection

**Actual Behavior**
Font remains as default (PT Sans Narrow)

**Only ElvUI Enabled**
N/A

**Blizzard Issue?**
No

**Additional Information**
N/A

**Error Log**
N/A

**Comment by Bunny67** [comment]
Fixed in latest commits
