### ISSUE TITLE
Проблема совместимости ElvUi и TankTotals

### ISSUE THREAD

**Issue by Vitoshka** [ElvUI-WotLK/ElvUI#633]
**Description**
Проблема совместимости с библиотекой, когда вхожу в игру возникает ошибка

**Version Number**
6.01

**Error Log**
1x TankTotals-4.20\Components\UI.lua:231: attempt to index field 'TitleBar' (a nil value)
TankTotals-4.20\TankTotals.lua:71: in function <TankTotals\TankTotals.lua:69>
(tail call): ?:
<in C code>: ?
<string>:"safecall Dispatcher[1]":9: in function <[string "safecall Dispatcher[1]"]:5>
(tail call): ?:
AceAddon-3.0-12:593: in function <...s\ElvUI\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0.lua:586>
(tail call): ?:
TankTotals-4.20\TankTotals.lua:392: in function `?'
CallbackHandler-1.0-6 (Ace3):147: in function <...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:147>
<string>:"safecall Dispatcher[1]":4: in function <[string "safecall Dispatcher[1]"]:4>
<in C code>: ?
<string>:"safecall Dispatcher[1]":13: in function `?'
CallbackHandler-1.0-6 (Ace3):92: in function `Fire'
AceEvent-3.0-4:120: in function <...s\ElvUI\Libraries\Ace3\AceEvent-3.0\AceEvent-3.0.lua:119>

  ---

**Comment by Loaal** [comment]
Не могу воспроизвести.
Ошибка появляется если отключить ElvUI?

**Comment by Vitoshka** [comment]
нет, не появляется
