### ISSUE TITLE
No stats in character frame

### ISSUE THREAD

**Issue by mattek922** [ElvUI-WotLK/ElvUI#637]
Hello
I've got some issue, I updated to the newest version of Elvui with all plugins and since I updated it I cannot see stats, I've read that someone else reported it and they've told him that feature has been merged to Enhanced addon but it doesn't work for me, Just got blank space there. When I get back to older version of it, everything is fine and I got stats on character frame.

https://imgur.com/a/xttqIDJ

**Comment by Lightball-TFK** [comment]
Delete the elvui and elvui-enhanced from your add-on folder and download them again. That worked for me.

**Comment by mattek922** [comment]
Thank you very much! For quick reply and solution! That worked out :D I don't know why I haven't figured out by myself lol
