### ISSUE TITLE
Проблемы после последнего обновления

### ISSUE THREAD

**Issue by Vitoshka** [ElvUI-WotLK/ElvUI#638]
**Description**
Словил много ошибок после последних обновлений: 
_**cleanup skins part 3
cleanup skins part 2
cleanup skins part 1**_
(возможно это связано с Sirus проверьте пож., если да, то оформлю тикет в https://github.com/Bunny67/ElvUI_Sirus

**Version Number**
6.01

**Steps to Reproduce**
Когда захожу в игру

**Error Log**
1x ElvUI-6.01\Modules\Skins\Blizzard\BGScore.lua:39: attempt to index global 'WorldStateScoreFrameClass' (a nil value)
<string>:"safecall Dispatcher[1]":4: in function <[string "safecall Dispatcher[1]"]:4>
<in C code>: ?
<string>:"safecall Dispatcher[1]":13: in function `?'
CallbackHandler-1.0-6 (Ace3):92: in function `Fire'
ElvUI-6.01\Modules\Skins\Skins.lua:686: in function `Initialize'
ElvUI-6.01\Modules\Skins\Skins.lua:704: in function <ElvUI\Modules\Skins\Skins.lua:703>
CallbackHandler-1.0-6 (Ace3):157: in function <...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:157>
<string>:"safecall Dispatcher[1]":4: in function <[string "safecall Dispatcher[1]"]:4>
<in C code>: ?
<string>:"safecall Dispatcher[1]":13: in function `?'
CallbackHandler-1.0-6 (Ace3):92: in function `Fire'
ElvUI-6.01\Core\Core.lua:1049: in function `CallLoadedModule'
ElvUI-6.01\Core\Core.lua:1074: in function `InitializeModules'
ElvUI-6.01\Core\Core.lua:1225: in function `Initialize'
ElvUI-6.01\Init.lua:204: in function <ElvUI\Init.lua:203>

  ---

1x ElvUI-6.01\Modules\Skins\Skins.lua:178: attempt to index local 'btn' (a nil value)
ElvUI-6.01\Modules\Skins\Blizzard\Character.lua:274: in function <...ce\AddOns\ElvUI\Modules\Skins\Blizzard\Character.lua:22>
<string>:"safecall Dispatcher[1]":4: in function <[string "safecall Dispatcher[1]"]:4>
<in C code>: ?
<string>:"safecall Dispatcher[1]":13: in function `?'
CallbackHandler-1.0-6 (Ace3):92: in function `Fire'
ElvUI-6.01\Modules\Skins\Skins.lua:686: in function `Initialize'
ElvUI-6.01\Modules\Skins\Skins.lua:704: in function <ElvUI\Modules\Skins\Skins.lua:703>
CallbackHandler-1.0-6 (Ace3):157: in function <...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:157>
<string>:"safecall Dispatcher[1]":4: in function <[string "safecall Dispatcher[1]"]:4>
<in C code>: ?
<string>:"safecall Dispatcher[1]":13: in function `?'
CallbackHandler-1.0-6 (Ace3):92: in function `Fire'
ElvUI-6.01\Core\Core.lua:1049: in function `CallLoadedModule'
ElvUI-6.01\Core\Core.lua:1074: in function `InitializeModules'
ElvUI-6.01\Core\Core.lua:1225: in function `Initialize'
ElvUI-6.01\Init.lua:204: in function <ElvUI\Init.lua:203>

  ---

1x ElvUI-6.01\Modules\Skins\Blizzard\DressingRoom.lua:18: attempt to call upvalue 'SetDressUpBackground' (a nil value)
<string>:"safecall Dispatcher[1]":4: in function <[string "safecall Dispatcher[1]"]:4>
<in C code>: ?
<string>:"safecall Dispatcher[1]":13: in function `?'
CallbackHandler-1.0-6 (Ace3):92: in function `Fire'
ElvUI-6.01\Modules\Skins\Skins.lua:686: in function `Initialize'
ElvUI-6.01\Modules\Skins\Skins.lua:704: in function <ElvUI\Modules\Skins\Skins.lua:703>
CallbackHandler-1.0-6 (Ace3):157: in function <...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:157>
<string>:"safecall Dispatcher[1]":4: in function <[string "safecall Dispatcher[1]"]:4>
<in C code>: ?
<string>:"safecall Dispatcher[1]":13: in function `?'
CallbackHandler-1.0-6 (Ace3):92: in function `Fire'
ElvUI-6.01\Core\Core.lua:1049: in function `CallLoadedModule'
ElvUI-6.01\Core\Core.lua:1074: in function `InitializeModules'
ElvUI-6.01\Core\Core.lua:1225: in function `Initialize'
ElvUI-6.01\Init.lua:204: in function <ElvUI\Init.lua:203>

  ---

1x ElvUI-6.01\Modules\Skins\Blizzard\Friends.lua:163: attempt to index global 'GuildFrameColumnHeader3' (a nil value)
<string>:"safecall Dispatcher[1]":4: in function <[string "safecall Dispatcher[1]"]:4>
<in C code>: ?
<string>:"safecall Dispatcher[1]":13: in function `?'
CallbackHandler-1.0-6 (Ace3):92: in function `Fire'
ElvUI-6.01\Modules\Skins\Skins.lua:686: in function `Initialize'
ElvUI-6.01\Modules\Skins\Skins.lua:704: in function <ElvUI\Modules\Skins\Skins.lua:703>
CallbackHandler-1.0-6 (Ace3):157: in function <...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:157>
<string>:"safecall Dispatcher[1]":4: in function <[string "safecall Dispatcher[1]"]:4>
<in C code>: ?
<string>:"safecall Dispatcher[1]":13: in function `?'
CallbackHandler-1.0-6 (Ace3):92: in function `Fire'
ElvUI-6.01\Core\Core.lua:1049: in function `CallLoadedModule'
ElvUI-6.01\Core\Core.lua:1074: in function `InitializeModules'
ElvUI-6.01\Core\Core.lua:1225: in function `Initialize'
ElvUI-6.01\Init.lua:204: in function <ElvUI\Init.lua:203>

  ---

1x ElvUI-6.01\Modules\Skins\Blizzard\LFD.lua:131: attempt to index global 'LFDParentFramePortrait' (a nil value)
<string>:"safecall Dispatcher[1]":4: in function <[string "safecall Dispatcher[1]"]:4>
<in C code>: ?
<string>:"safecall Dispatcher[1]":13: in function `?'
CallbackHandler-1.0-6 (Ace3):92: in function `Fire'
ElvUI-6.01\Modules\Skins\Skins.lua:686: in function `Initialize'
ElvUI-6.01\Modules\Skins\Skins.lua:704: in function <ElvUI\Modules\Skins\Skins.lua:703>
CallbackHandler-1.0-6 (Ace3):157: in function <...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:157>
<string>:"safecall Dispatcher[1]":4: in function <[string "safecall Dispatcher[1]"]:4>
<in C code>: ?
<string>:"safecall Dispatcher[1]":13: in function `?'
CallbackHandler-1.0-6 (Ace3):92: in function `Fire'
ElvUI-6.01\Core\Core.lua:1049: in function `CallLoadedModule'
ElvUI-6.01\Core\Core.lua:1074: in function `InitializeModules'
ElvUI-6.01\Core\Core.lua:1225: in function `Initialize'
ElvUI-6.01\Init.lua:204: in function <ElvUI\Init.lua:203>

  ---

1x ElvUI-6.01\Modules\Skins\Blizzard\Mail.lua:95: attempt to index global 'InboxTitleText' (a nil value)
<string>:"safecall Dispatcher[1]":4: in function <[string "safecall Dispatcher[1]"]:4>
<in C code>: ?
<string>:"safecall Dispatcher[1]":13: in function `?'
CallbackHandler-1.0-6 (Ace3):92: in function `Fire'
ElvUI-6.01\Modules\Skins\Skins.lua:686: in function `Initialize'
ElvUI-6.01\Modules\Skins\Skins.lua:704: in function <ElvUI\Modules\Skins\Skins.lua:703>
CallbackHandler-1.0-6 (Ace3):157: in function <...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:157>
<string>:"safecall Dispatcher[1]":4: in function <[string "safecall Dispatcher[1]"]:4>
<in C code>: ?
<string>:"safecall Dispatcher[1]":13: in function `?'
CallbackHandler-1.0-6 (Ace3):92: in function `Fire'
ElvUI-6.01\Core\Core.lua:1049: in function `CallLoadedModule'
ElvUI-6.01\Core\Core.lua:1074: in function `InitializeModules'
ElvUI-6.01\Core\Core.lua:1225: in function `Initialize'
ElvUI-6.01\Init.lua:204: in function <ElvUI\Init.lua:203>

  ---

1x ElvUI-6.01\Modules\Skins\Blizzard\Spellbook.lua:46: attempt to index a nil value
<string>:"safecall Dispatcher[1]":4: in function <[string "safecall Dispatcher[1]"]:4>
<in C code>: ?
<string>:"safecall Dispatcher[1]":13: in function `?'
CallbackHandler-1.0-6 (Ace3):92: in function `Fire'
ElvUI-6.01\Modules\Skins\Skins.lua:686: in function `Initialize'
ElvUI-6.01\Modules\Skins\Skins.lua:704: in function <ElvUI\Modules\Skins\Skins.lua:703>
CallbackHandler-1.0-6 (Ace3):157: in function <...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:157>
<string>:"safecall Dispatcher[1]":4: in function <[string "safecall Dispatcher[1]"]:4>
<in C code>: ?
<string>:"safecall Dispatcher[1]":13: in function `?'
CallbackHandler-1.0-6 (Ace3):92: in function `Fire'
ElvUI-6.01\Core\Core.lua:1049: in function `CallLoadedModule'
ElvUI-6.01\Core\Core.lua:1074: in function `InitializeModules'
ElvUI-6.01\Core\Core.lua:1225: in function `Initialize'
ElvUI-6.01\Init.lua:204: in function <ElvUI\Init.lua:203>

  ---

1x ElvUI-6.01\Modules\Skins\Blizzard\Taxi.lua:16: attempt to index global 'TaxiPortrait' (a nil value)
<string>:"safecall Dispatcher[1]":4: in function <[string "safecall Dispatcher[1]"]:4>
<in C code>: ?
<string>:"safecall Dispatcher[1]":13: in function `?'
CallbackHandler-1.0-6 (Ace3):92: in function `Fire'
ElvUI-6.01\Modules\Skins\Skins.lua:686: in function `Initialize'
ElvUI-6.01\Modules\Skins\Skins.lua:704: in function <ElvUI\Modules\Skins\Skins.lua:703>
CallbackHandler-1.0-6 (Ace3):157: in function <...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:157>
<string>:"safecall Dispatcher[1]":4: in function <[string "safecall Dispatcher[1]"]:4>
<in C code>: ?
<string>:"safecall Dispatcher[1]":13: in function `?'
CallbackHandler-1.0-6 (Ace3):92: in function `Fire'
ElvUI-6.01\Core\Core.lua:1049: in function `CallLoadedModule'
ElvUI-6.01\Core\Core.lua:1074: in function `InitializeModules'
ElvUI-6.01\Core\Core.lua:1225: in function `Initialize'
ElvUI-6.01\Init.lua:204: in function <ElvUI\Init.lua:203>

  ---

1x ElvUI-6.01\Modules\Skins\Blizzard\WatchFrame.lua:19: attempt to index global 'WatchFrameCollapseExpandButton' (a nil value)
<string>:"safecall Dispatcher[1]":4: in function <[string "safecall Dispatcher[1]"]:4>
<in C code>: ?
<string>:"safecall Dispatcher[1]":13: in function `?'
CallbackHandler-1.0-6 (Ace3):92: in function `Fire'
ElvUI-6.01\Modules\Skins\Skins.lua:686: in function `Initialize'
ElvUI-6.01\Modules\Skins\Skins.lua:704: in function <ElvUI\Modules\Skins\Skins.lua:703>
CallbackHandler-1.0-6 (Ace3):157: in function <...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:157>
<string>:"safecall Dispatcher[1]":4: in function <[string "safecall Dispatcher[1]"]:4>
<in C code>: ?
<string>:"safecall Dispatcher[1]":13: in function `?'
CallbackHandler-1.0-6 (Ace3):92: in function `Fire'
ElvUI-6.01\Core\Core.lua:1049: in function `CallLoadedModule'
ElvUI-6.01\Core\Core.lua:1074: in function `InitializeModules'
ElvUI-6.01\Core\Core.lua:1225: in function `Initialize'
ElvUI-6.01\Init.lua:204: in function <ElvUI\Init.lua:203>

  ---

**Comment by Bunny67** [comment]
Поправил в https://github.com/Bunny67/ElvUI_Sirus
