### ISSUE TITLE
Проблема с иконками на миникарте

### ISSUE THREAD

**Issue by Vitoshka** [ElvUI-WotLK/ElvUI#640]
**Description**
Как видно по скрину, иконки одного и того-же класса различаются, возможно это связано из-за наложения иконок Mapstep, так как там такие иконки присутствуют (не полный круг с пустым пространством посередине 
![WoWScrnShot_091919_205250](https://user-images.githubusercontent.com/30943063/65269462-decea880-db21-11e9-8b88-c61da5945bfc.jpg)

**Version Number**
6.01

**Comment by Bunny67** [comment]
Кружки которые с без заполнение, это юниты которые не в твоей пати.
