### ISSUE TITLE
Bank Items Doesn't Count

### ISSUE THREAD

**Issue by Noob1e** [ElvUI-WotLK/ElvUI#643]
**Description**
Mouse hovering on an item in the bank doesn't show the actual count number. It doesn't add items in the bank to the calculation, but only items in the inventory.

**Version Number**
6.01

**Steps to Reproduce**

1. Buy 2 same items
2. Put one of them in your inventory
3. Put the other on into the bank

**Expected Behavior**
It should count them all together. If it counts seperately ("[B]ank Count:" - "[I]nventory Count:" - "[T]otal Count:") would be much better.

**Actual Behavior**
It calculates only the items in the inventory.

**Blizzard Issue?**
Nope

**Additional Information**
![Bank-Inventory Count](https://user-images.githubusercontent.com/27544010/65385953-d94daa00-dd3d-11e9-946c-0b08dbc4a999.png)

**Comment by Bunny67** [comment]
Unfortunately, we can’t find out where the item is when you hover over it.
Use this: ![image](https://user-images.githubusercontent.com/5816685/65387152-06558900-dd4d-11e9-967d-9020f4e0ca10.png)

**Comment by rokpusnik** [comment]
Altoholic addon has that function I think, and its tooltips work with ElvUI so you can use that instead (or bunny could see how that addon does it (I believe it uses DataStore as a dependency)
