### ISSUE TITLE
Агро

### ISSUE THREAD

**Issue by koneforest** [ElvUI-WotLK/ElvUI#646]
Доброго дня. 
Хочу предложить ввести функцию отображения вашего агро, по отношению к таргету, прям на хп баре таргета, как это выполнено в стандартной версии. Это бы сильно упростило слежение за своим агро.
![агр](https://user-images.githubusercontent.com/55813133/65639832-a0d5f680-dff1-11e9-917c-7529803c0d30.PNG)
![агро](https://user-images.githubusercontent.com/55813133/65639833-a0d5f680-dff1-11e9-8162-6ce03ecad0d1.PNG)

**Comment by Bunny67** [comment]
Можно использовать тег на агро создав кастомный текст, либо добавив куда либо в другое место:
![image](https://user-images.githubusercontent.com/5816685/65789283-bb30e100-e165-11e9-8a69-d81d175cca1c.png)
[threatcolor][threat:percent]

**Comment by koneforest** [comment]
Выполнил все как Вы предлагали и столкнулся с проблемой. Что бы появилось значение агро, необходимо после нанесения удара, отменить таргет и взять моба снова. Цифра агро статична и не изменяется до тех пор, пока вновь, не выберешь цель по новой в таргет, только после отмены и взятия по новой меняется значение агро по отношению к мобу. Можно ли как то это исправить, или есть ли возможность завязать отображение на омене, т.к нет отображения в реальном времени.

**Comment by Bunny67** [comment]
Обнови елв, теперь должно обновлять нормально
