### ISSUE TITLE
Reputation Messages

### ISSUE THREAD

**Issue by Noob1e** [ElvUI-WotLK/ElvUI#650]
**Description**
I get a detailed chat message when I get reputation of any faction and I don't know how to disable them (I don't remember how did I enabled them as well).

I just want to know how can I disable the messages.

**Version Number**
6.04

**Steps to Reproduce**
1. Kill a mob that gives reputation or complete a quest.

**Additional Information**
![WoWScrnShot_092919_195045](https://user-images.githubusercontent.com/27544010/65835938-50aeab00-e2f5-11e9-9c32-b612ba5b0d22.jpg)
![WoWScrnShot_092919_195011](https://user-images.githubusercontent.com/27544010/65835939-50aeab00-e2f5-11e9-91ef-2f6e654faf54.jpg)
![WoWScrnShot_092919_194935](https://user-images.githubusercontent.com/27544010/65835940-50aeab00-e2f5-11e9-8d69-c97ad59cf85f.jpg)

**Comment by Bunny67** [comment]
When the ElvUI is off, are there any messages?

**Comment by Noob1e** [comment]
After your reply, I disabled ElvUI but still got the messages. Then I found out that it was because of the "Zygor Guides" addon.
Sorry for wasting your time.
