### ISSUE TITLE
Freeze when killing an npc in Icecrown Citadel

### ISSUE THREAD

**Issue by OfficialNoobsmoke** [ElvUI-WotLK/ElvUI#657]
**Description**
Whenever an NPC dies in ICC the game freezes for like 0.5-1 second.

**Version Number**
6.04

**Steps to Reproduce**
1.Enter in Icecrown Citadel.
2.Start killing bosses / mobs and the game freezes for 0.5 - 1 second after each npc killed.

**Expected Behavior**
The game shouldn't freeze.

**Actual Behavior**
The game freezes for 0.5 - 1 second.

**Only ElvUI Enabled**
Yes. I had only ElvUI enabled and I managed to reproduce it.

**Blizzard Issue?**
No, I could not reproduce it with no addon.

**Additional Information**
Older versions are not having this issue and it only occurs in ICC.

**Error Log**
No errors
```

```

**Comment by Zidras** [comment]
Here's a clip of me freezing to oblivion when adds start dying: https://clips.twitch.tv/DependableFaintKoupreyMrDestructoid

(PS: the computer is by no means lacking hardware. Lag or graphical performance isn't the issue - raid aoe spell particles are present before the freeze and game runs fine; freeze start after deaths. Problem introduced in elvui v6)

Hope this helps

**Comment by mrnuggets** [comment]
Same happens to me, same spot as Zidras, and i have a great PC as well, and even with the lowest settings the freeze happens.

**Comment by Zidras** [comment]
This was for me by far the most gamechanging fix in v6. No more freeze on adds, Mind Control,... everything is buttery smooth. Thank you!
