### ISSUE TITLE
Nameplate Debuffs CD Issue

### ISSUE THREAD

**Issue by Noob1e** [ElvUI-WotLK/ElvUI#666]
**Description**
CD text on the Enemy Nameplates debuffs get bugged sometimes. I polymorphed the first target then changed to the 2nd one and as you can see in the SS, second target's debuff CD texts turned to the default.

Also, even if you "Color" and "Text" override options in "Cooldown Text" menu, after you relog, CD text turns back to the default. It looks fine in the menu, but not on the nameplates. 

**Version Number**
6.04

**Additional Information**
https://ibb.co/ts9tV83
https://ibb.co/250y33M
https://ibb.co/hBmGK2k

**Comment by Noob1e** [comment]
Is there a way to remove "s" letter of the "second(s)" in nameplates CD?

**Comment by Zidras** [comment]
Just referencing an old ticket with the same request #624
Thought it would help since it highlights the commit in which the time unit was introduced

**Comment by Zidras** [comment]
@Noob1e It appears the time unit no longer shows on nameplates
