### ISSUE TITLE
[Nameplate branch] Nameplate glow bugged

### ISSUE THREAD

**Issue by Zidras** [ElvUI-WotLK/ElvUI#669]
**Description**

Nameplate glow is behaving abnormally. See prints for more details.
(This ticket applies ONLY to dev build "Nameplates")

**Version Number**

6.04 (Nameplates branch)

**Steps to Reproduce**

1. Targets; random chance... See below for each example.
https://clips.twitch.tv/EnticingFancyRhinocerosPoooound

**Expected Behavior**

Glow should be the same size as nameplate and also not glow on death (low health indicator means this? Couldn't understand what is output of low health indicator) nor absence of target/mousover.

**Actual Behavior**

Example 1: Targetting Pafins - shows out of bounds glow. Mousover Zuppal for expected background glow.
![image](https://user-images.githubusercontent.com/10605951/69486211-49ada000-0e41-11ea-9bcd-bf612a3adbe3.png)
1) Random targetting people until bug occured

Example 2: Targetting Walleina (bug  happens to random people but it sticks to them until /rl).
![image](https://user-images.githubusercontent.com/10605951/69486238-b9238f80-0e41-11ea-8e3d-7309571d0f27.png)
1) Random targetting people until bug occured

Example 3: Chose Border Glow, same happens:
![image](https://user-images.githubusercontent.com/10605951/69486488-da857b00-0e43-11ea-978c-3fafcd9de9cf.png)

Example 4: Different coloured out of bound glows:
![image](https://user-images.githubusercontent.com/10605951/69486326-36e79b00-0e42-11ea-8d76-acf0d86f20cc.png)
https://clips.twitch.tv/EnticingFancyRhinocerosPoooound
1) Don't know what triggered

Example 5: Permanent glow (both out of bounds glow and Psicotick correct glow but permanent without being mouseovered or targetted
![image](https://user-images.githubusercontent.com/10605951/69486340-77471900-0e42-11ea-9170-5eb7d80b57f6.png)
1) Mouseover one time.

Example 6: Red out of bounds glow on ghosts and remained after rez:
![image](https://user-images.githubusercontent.com/10605951/69486517-423bc600-0e44-11ea-8feb-2b920f711eae.png)

![image](https://user-images.githubusercontent.com/10605951/69486527-8cbd4280-0e44-11ea-93bb-2b29ac75dc38.png)
1) Death

**Only ElvUI Enabled**

Haven't tested with /luaerror on

**Blizzard Issue?**

No

**Additional Information**

No Lua errors.
I also noticed that if HP bar on friendly is disabled (so only name shows), the option of Target/Low Health indicator does not apply If targetted. Shouldn't it be like shown in player Psicotick if targetted?:
![image](https://user-images.githubusercontent.com/10605951/69486548-cee68400-0e44-11ea-8cb0-42cd16952d86.png)

**Comment by Zidras** [comment]
Problem still persists. This time I did /luaerror on to narrow it to elvui.
![image](https://user-images.githubusercontent.com/10605951/69493794-1b64aa80-0eab-11ea-8c3f-6088d812c12a.png)
![image](https://user-images.githubusercontent.com/10605951/69493803-4222e100-0eab-11ea-8271-88a3a5d697b4.png)

Width being affected by a disabled slider:
![image](https://user-images.githubusercontent.com/10605951/69493862-03415b00-0eac-11ea-9bf5-5c9c59ad2e78.png)
![image](https://user-images.githubusercontent.com/10605951/69493864-0dfbf000-0eac-11ea-817f-88e3cc705408.png)


Also found a way to force bug 100% of the time for debugging purposes:
- Enable and disable Friendly Player health. This way all the plates will show bugged glow.

**Comment by Zidras** [comment]
I'd like to add/clarify a bit more information on this: 

- Whenever I target someone, it doesn't always apply said Target/Low Health Indicator on my target nameplate
Expected: 
![image](https://user-images.githubusercontent.com/10605951/69584117-4f87ba80-0fd4-11ea-9c74-efc50b87b0a5.png)
Actual (sometimes):
![image](https://user-images.githubusercontent.com/10605951/69584166-6e864c80-0fd4-11ea-9e66-3e698052268a.png)
(additional notes: if I enable always show health bar on target, it works 100% of the time)

- Indicator selected (when applied) isn't always the chosen one. Example below taken on same session with no settings changed between picture:
![image](https://user-images.githubusercontent.com/10605951/69584310-c7ee7b80-0fd4-11ea-8c8a-8e4bd5fa8bd7.png)
![image](https://user-images.githubusercontent.com/10605951/69584326-cf158980-0fd4-11ea-9650-cb274a14e769.png)

- Indicator if changed in the same session required a /reload to get the right indicator to show.

- Indicator width not being applied to name width but rather a disabled Health width slider

**Comment by Bunny67** [comment]
Check now

**Comment by Zidras** [comment]
I've done a quick testing in dalaran as baseline and also 1 run PVP to test the low health indicator.
Haven't tested death status nor raid yet (will only be able to test on raid during weekend).

Here are my findings:
- If target selected, **with no health bar**, nameplate acquires **background glow** with color selected from general options > color. Type of glow is NOT affected by current selection of target/low health indicator.
![image](https://user-images.githubusercontent.com/10605951/69668394-b5814a00-1087-11ea-9784-4663414dcba9.png)

**_If using background glow by default without HP bar is indeed intended, it is working properly._**


 
- If target selected, **with health bar**, nameplate acquires glow with color selected from general options > color. Type of glow **is** affected by current selection of target/low health indicator.

![image](https://user-images.githubusercontent.com/10605951/69668259-6e935480-1087-11ea-8e46-ace04c0ef590.png)

**_Working as intended._**

Personal note: Should the raid/death glow portrayed in examples 5 and 6 be problems of the past, the ticket can be closed as everything appears to be working properly and perfectly implemented.

**Comment by Zidras** [comment]
Raid tested: no issues

**Comment by Zidras** [comment]
Found a bug. If I force namplate _Name Only_ with style filters Actions, glow width gets funky again.
Expected behaviour:
![image](https://user-images.githubusercontent.com/10605951/69900102-84df3000-1367-11ea-982e-b680d65e9fd2.png)

Actual behaviour (any nameplate: enemy and friendly. Created a test filter with just _Is targeted_ and action _Name Only_):
![image](https://user-images.githubusercontent.com/10605951/69900119-b1934780-1367-11ea-9f6f-b5f1bdd1e9af.png)
![image](https://user-images.githubusercontent.com/10605951/69900127-c5d74480-1367-11ea-903a-3ae2dc4db73c.png)
![image](https://user-images.githubusercontent.com/10605951/69900153-fa4b0080-1367-11ea-844d-cb9918e8dc16.png)

**Comment by Zidras** [comment]
So after https://github.com/ElvUI-WotLK/ElvUI/commit/e5cef8630f7b8757f49d3617d17eb75e0330655d pretty much everything that was described above has been fixed. However a new bug with target friendly NPC name color was introduced. It always shows white color.
- No target:
![image](https://user-images.githubusercontent.com/10605951/70368634-0cb3c580-18a5-11ea-9fa5-ee982501aa73.png)

- Targetted: 
![image](https://user-images.githubusercontent.com/10605951/70368635-150c0080-18a5-11ea-8091-2a63ebf5de96.png)

**Comment by Zidras** [comment]
Using latest nameplates build and it's fixed.
