### ISSUE TITLE
[Nameplate branch] Nameplate target alpha not working

### ISSUE THREAD

**Issue by Zidras** [ElvUI-WotLK/ElvUI#672]
**Description**

If I disable the new target and non-target default style filters (dev placeholder filters ??),  under Target doesn't work.

**Version Number**

https://github.com/ElvUI-WotLK/ElvUI/commit/e5cef8630f7b8757f49d3617d17eb75e0330655d

**Steps to Reproduce**

1. Use non-target alpha slider

**Expected Behavior**

![image](https://user-images.githubusercontent.com/10605951/70369058-67e8b680-18ab-11ea-971b-d5fc4701da47.png)

**Actual Behavior**

![image](https://user-images.githubusercontent.com/10605951/70369051-3839ae80-18ab-11ea-8190-8bac53f6e40e.png)

**Only ElvUI Enabled**

Yes

**Blizzard Issue?**

No

**Additional Information**

To mimic alpha, used Dev Elvui_nonTarget filter > Action alpha

**Comment by Bunny67** [comment]
delete ElvUI_Target and ElvUI_NonTarget filters, if any and check now

**Comment by Zidras** [comment]
Your latest commits to the nameplates fixed it. Those filters did not affect the glow (tried on and off :)) Good work
