### ISSUE TITLE
[Nameplates branch] Icon only glow set to icon width + length

### ISSUE THREAD

**Issue by Zidras** [ElvUI-WotLK/ElvUI#683]
**Description**

Nameplate glow when _icon only_ is presented assumes a "normal" nameplate instead of the icon frame. 

**Version Number**

6.06 nameplate branch

**Steps to Reproduce**

1. Mouseover icon

**Expected Behavior**

Shape glow around icon frame

**Actual Behavior**

![image](https://user-images.githubusercontent.com/10605951/71490778-9b708e00-2824-11ea-88f2-cddd8542410b.png)
Also width of glow is assuming length of the replaced name (eg.: tremor totem has shorter glow, while strength of earth totem has wider glow)

**Only ElvUI Enabled**

Yes

**Blizzard Issue?**

No

**Comment by Bunny67** [comment]
Check now in master

**Comment by Zidras** [comment]
1. Mouseover glow **not** working on icons;
2. Width icon glow fixed!
3. Icon with a light green border is intended? Kinda clashes with item border colors in my opinion. I suggest making it neutral color or adopt the color scheme of totem bars (earth, fire, water, air):
![image](https://user-images.githubusercontent.com/10605951/71636933-e842d300-2c2f-11ea-8af6-5dffce1bd5d8.png) 
![image](https://user-images.githubusercontent.com/10605951/71636934-f4c72b80-2c2f-11ea-8309-d9f87f1dd7d0.png) 
![image](https://user-images.githubusercontent.com/10605951/71636940-0a3c5580-2c30-11ea-8563-ac8d74007582.png)  ![image](https://user-images.githubusercontent.com/10605951/71636937-ff81c080-2c2f-11ea-9849-f30fbb2cee58.png)

**Comment by Zidras** [comment]
Fixed 👍

**Comment by Zidras** [comment]
So after your commit, I went through the code and I understood your intention (correct me if I'm wrong). The line `self:StyleFrameColor(frame.IconFrame, frame.oldHealthBar:GetStatusBarColor())` created an icon border with the color according to status bar color. I reckon this feature has potential for PvP: 
![image](https://user-images.githubusercontent.com/10605951/71637181-e596ac80-2c34-11ea-84fa-77987a8692f7.png)

Bunny, for the moment I don't have any ideas on how to improve this feature further. I'll think about this so we can discuss this topic and not toss your idea out the window

**Comment by Zidras** [comment]
Had to reopen issue. When being mouseover on icons from the opposing faction, there's no mouseover glow applied.

**Comment by Zidras** [comment]
Using totem style filter with icon only. If enemy HP bar is enabled, mouseover glow is white. If I disable enemy HP bar (either by going to enemy NPC > disable Health OR using a style filter with Name only), mouseover glow correctly shows Red.

**Comment by Zidras** [comment]
Fixed 🥇
