### ISSUE TITLE
[Bug] ElvUI disappearing bufficons on nameplates

### ISSUE THREAD

**Issue by MaelKoT** [ElvUI-WotLK/ElvUI#685]
**Description**
Весь бой смотрим за синей полоской шамана.
На него вешается Длань жертвенности, затем Длань свободы, и Длань защиты (заменяет Длань жертвенности). Эти бафы на мгновение после наложения появляются над неймплейтами и сразу же исчезают. Потом, когда я меняю таргет - на шамане возвращается отображение иконки Длани свободы, висит до конца этого бафа. Потом за мгновение до конца над неймплейтами появляется Длани защиты, хотя этот баф висел все время.

Фильтры и приоритет - по умолчанию.
Черный список - PlayerBuffs - TurtleBuffs

**Version Number**
ElvUI-master 26.12.2019

**Additional Information**
https://www.youtube.com/watch?v=dxNB8UhpL-k

**Comment by Bunny67** [comment]
Должно быть исправлено
