### ISSUE TITLE
Nameplate mouseover glow not showing for HP bar in new created plates

### ISSUE THREAD

**Issue by Zidras** [ElvUI-WotLK/ElvUI#688]
**Description**

If I mouseover a nameplate with HP bar enabled, it does not create the whitish glow inside HP bar. Forcing a refresh, like enable and disable clickthrough, glow starts working only for the plates that were already created.

**Version Number**

6.06 (01.01.2020 commits)

**Steps to Reproduce**

1. Enable HP bar
2. Mouseover plate

**Expected Behavior**

![image](https://user-images.githubusercontent.com/10605951/71637548-838e7500-2c3d-11ea-894c-13fd0eb086e3.png)
![image](https://user-images.githubusercontent.com/10605951/71637549-9739db80-2c3d-11ea-972f-839a978fed02.png)

**Actual Behavior**

![image](https://user-images.githubusercontent.com/10605951/71637546-796c7680-2c3d-11ea-8011-96feac6da76a.png)
![image](https://user-images.githubusercontent.com/10605951/71637553-ac166f00-2c3d-11ea-9491-831a20e265e7.png)

**Only ElvUI Enabled**

Yes

**Blizzard Issue?**

No

**Additional information**
Pictures taken in the same session with same build. Doesn't happen to 100% of the plates

**Comment by Bunny67** [comment]
Can not reproduce

**Comment by Zidras** [comment]
I can't figure out what's causing this... This is happening with pretty much all my profiles.
With fresh/default profiles I cannot reproduce this.

Did testing with /luaerror on. Let me know if there's dev commands or something that could help pinpoint the source of the bug.

I clipped to better illustrate the issue, maybe you can understand what's going on:
https://streamable.com/p28vf
Video starts with left two plates not glowing. I do a camera 360 to force new plates with no success, walked away and back in to again force new plates and now 1 bottom left and 1 top right dummy don't have glow. I force update on existing plates by enabling/disabling clickthrough and now all work. After /rl they still all work, i do 360º and problem reappear.

(PS: on the clip sometimes hp bar gets green for some reason, even with a default elvui profile. Does not happen with blizz plates as statusbarcolor is always yellow, no matter what I tried. I can make new issue, idk if it was related or not with current issue)

**Comment by Bunny67** [comment]
Check again, there were small changes

**Comment by Zidras** [comment]
Don't have problem anymore 👍
