### ISSUE TITLE
ElvUI_MinimapButtons missing?

### ISSUE THREAD

**Issue by MansourM** [ElvUI-WotLK/ElvUI#694]
hey,
great work!
I'm just a bit confused, I got the addon from a discord friend the first time,
it has a module called "ElvUI_MinimapButtons" and it works!
I cam here to update my addon and was wondering why u don't have it here.
I attached mine

thanks a lot and keep up the good work.
[ElvUI_MinimapButtons.zip](https://github.com/ElvUI-WotLK/ElvUI/files/4028591/ElvUI_MinimapButtons.zip)

**Comment by Zidras** [comment]
Minimap buttons are now integrated in the ElvUI Enhanced.

**Comment by MansourM** [comment]
Oh, I see
Thanks
