### ISSUE TITLE
ElvUI плагин

### ISSUE THREAD

**Issue by Frixen** [ElvUI-WotLK/ElvUI#695]
ElvUI Visual Aura Times, включаю модификацию, перезапускается интерфейс, а она все равно выключена, после последнего релиза. Или эта модификация больше не поддерживается?

**Comment by Bunny67** [comment]
Функции плагина теперь в самом ElvUI

**Comment by Frixen** [comment]
> Функции плагина теперь в самом ElvUI

тогда добавь функцию отключения показа времени, чтобы я мог оставить только статусбар

**Comment by Bunny67** [comment]
Да, скрытие времени не переехало, чуть позже добавлю

**Comment by Frixen** [comment]
> Да, скрытие времени не переехало, чуть позже добавлю

Нет эффекта от кнопки "No duration" жму, время не убирается

**Comment by Bunny67** [comment]
> Нет эффекта от кнопки "No duration" жму, время не убирается.
> Edit: время остается только на ядах у роги, статусбар на них не отображается
Эта опция отвечает, показывать ли статус бар при отсутствии времени у баффа.
Если ты не про это то скинь скрин.

**Comment by Frixen** [comment]
![image](https://user-images.githubusercontent.com/18544029/71978244-2c505c00-325e-11ea-856d-d360aa83e657.png)

**Comment by Frixen** [comment]
![image](https://user-images.githubusercontent.com/18544029/71978334-6b7ead00-325e-11ea-9f82-ff2874fe7e9a.png)

**Comment by Frixen** [comment]
Надоел тебе поди) можешь на ядах обводку убрать на статусбаре чтоб она не наследовала обводку от иконки 
![image](https://user-images.githubusercontent.com/18544029/71988897-0b930100-3274-11ea-8930-767e652c7dd5.png)

**Comment by MaelKoT** [comment]
Frixen, можешь отписать в дискорде Ma_aelKoT#7282 ? Просто стиль красивый у твоих юнитфреймов, поделись настройками, пожалуйста :)

Прошу прощения что влез не по теме, просто не знаю, можно ли тут как-то пользователю личное сообщение отправить.
