### ISSUE TITLE
Map quest objectives

### ISSUE THREAD

**Issue by Jinteki01** [ElvUI-WotLK/ElvUI#698]
**Description**
When I open the world map the first time it shows the zone with the quest objectives correctly, but every time after that it doesn't show any of the objectives till I reload or relog.

**Version Number**
v6.06

**Steps to Reproduce**
1. I log in and open the map in a zone with quests.
2. The objectives show correctly and I close the map.
3. I open the map again and now no objectives are showing and the error below pops up.
4. I /reloadui or relog and repeat the steps above with the same result.

**Only ElvUI Enabled**
Turned off all addons except the ElvUI ones and still got the same error.

**Additional Information**
When I click the arrow in the top right corner that makes the map bigger or smaller produces the same error below without closing the map.
I have Automatic Quest Tracking and Automatic Quest Progress Updates are enabled in the interface options. I tried turning these options off, but it didn't seem to make a difference.

**Error Log**
```
Message: Interface\FrameXML\QuestPOI.lua:200: attempt to index local 'poiButton' (a nil value)
Time: 01/22/20 11:02:50
Count: 6
Stack: [C]: ?
Interface\FrameXML\QuestPOI.lua:200: in function `QuestPOI_HideButtons'
Interface\FrameXML\WorldMapFrame.lua:1698: in function `WorldMapFrame_ClearQuestPOIs'
Interface\FrameXML\WorldMapFrame.lua:1539: in function `WorldMapFrame_UpdateQuests'
Interface\FrameXML\WorldMapFrame.lua:1444: in function `WorldMapFrame_DisplayQuests'
Interface\FrameXML\WorldMapFrame.lua:1521: in function `WorldMapFrame_UpdateMap'
Interface\FrameXML\WorldMapFrame.lua:175: in function <Interface\FrameXML\WorldMapFrame.lua:168>
[C]: in function `SetMapToCurrentZone'
Interface\FrameXML\WorldMapFrame.lua:142: in function <Interface\FrameXML\WorldMapFrame.lua:132>
[C]: in function `Show'
Interface\FrameXML\UIParent.lua:1580: in function `SetUIPanel'
Interface\FrameXML\UIParent.lua:1385: in function `ShowUIPanel'
Interface\FrameXML\UIParent.lua:1311: in function <Interface\FrameXML\UIParent.lua:1307>
[C]: in function `SetAttribute'
Interface\FrameXML\UIParent.lua:1974: in function `ShowUIPanel'
Interface\FrameXML\UIParent.lua:1958: in function `ToggleFrame'
[string "TOGGLEWORLDMAP"]:1: in function <[string "TOGGLEWORLDMAP"]:1>

```

**Comment by MyneLife** [comment]
I am using v6.08 and am just experiencing the very same issue. Is this issue fixed already? If so the fix probably did not work for me
