### ISSUE TITLE
Auto repair lua error

### ISSUE THREAD

**Issue by Zidras** [ElvUI-WotLK/ElvUI#701]
**Description**

Everytime I went to repair on the entrance of ICC, I received lua error.

**Version Number**

6.06

**Steps to Reproduce**

1. Get durability to less than 100%
2. Open Repair
(reproduced this in ICC with 2g in the bag, autoguild repair on)

**Expected Behavior**

No error

**Actual Behavior**

Clip: https://streamable.com/y7y7i

**Only ElvUI Enabled**

No.

**Blizzard Issue?**

No.

**Additional Information**

Received not enough gold warning. Being an error number it might be related

**Error Log**

```
Message: Interface\AddOns\ElvUI\Modules\Misc\Misc.lua:130: attempt to compare number with nil
Time: 02/01/20 00:23:56
Count: 1
Stack: (tail call): ?ace\AddOns\ElvUI\Modules\Misc\Misc.lua:130: in function <Interface\AddOns\ElvUI\Modules\Misc\Misc.lua:122>
Interface\AddOns\ElvUI\Modules\Misc\Misc.lua:189: in function AutoRepair'
Interface\AddOns\ElvUI\Modules\Misc\Misc.lua:248: in function ?'
...BLT\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:146: in function <...BLT\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:146>
[string "safecall Dispatcher[1]"]:4: in function <[string "safecall Dispatcher[1]"]:4>
[C]: ?
[string "safecall Dispatcher[1]"]:13: in function ?'
...BLT\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:91: in function Fire'
...erface\AddOns\BLT\libs\AceEvent-3.0\AceEvent-3.0.lua:120: in function <...erface\AddOns\BLT\libs\AceEvent-3.0\AceEvent-3.0.lua:119>

Locals: No locals to dump

```

**Comment by Loaal** [comment]
Fixed with 0a2164e55db9dcbb8556a58ddb9d226fbc823045
