### ISSUE TITLE
Custom font selection for chat Timestamps

### ISSUE THREAD

**Issue by Svannie** [ElvUI-WotLK/ElvUI#720]
Please let us choose a custom TImestamp font, different from the chat font.
So that we would be able to choose fixed width font for the time stamps and avoid what's shown in the screenshot, thank you very much.

https://i.imgur.com/vnUA9QA.png

I'm loving elvUI and want to thank every contributor very much for your work.

**Comment by Loaal** [comment]
Timestamps are part of message string, and changing the font only for certain characters is not possible.
Sepparation of timestamp from a message string require major rework of whole chat module, and it's unlikely to be done, especially for that small feature.

I may advise you to find a good monospace font as an alternative solution to your problem.
