### ISSUE TITLE
Datatexts not showing on reload/login

### ISSUE THREAD

**Issue by Triksterism** [ElvUI-WotLK/ElvUI#724]
**Description**
Datatext information (guild, system, friends, etc...) does not display when the UI is reloaded or on a login.

**Version Number**
6.07

**Steps to Reproduce**
N/A

**Expected Behavior**
Datatexts should display always

**Actual Behavior**
Datatexts do not show UNLESS you manually change one of them

**Only ElvUI Enabled**
Yes

**Blizzard Issue?**
No

**Additional Information**
Despite datatexts not displaying, they can be 'fixed' (until reload / relog) by changing any of them

**Error Log**
N/A

**Comment by Triksterism** [comment]
Here's a video of me 'fixing' it: https://dl.dropboxusercontent.com/s/kickrz3kt2qxnov/2020-04-14_16-56-57.mp4

**Comment by Zidras** [comment]
Have you tried on a fresh profile? I don't have that issue

**Comment by Triksterism** [comment]
I think it's an issue with https://github.com/ElvUI-WotLK/ElvUI_DTBars2 now that I look into it.

**Comment by Bunny67** [comment]
fixed in https://github.com/ElvUI-WotLK/ElvUI_DTBars2
