### ISSUE TITLE
How to move/hide that frame

### ISSUE THREAD

**Issue by MicheleLele** [ElvUI-WotLK/ElvUI#727]
Hi there,

how can I move/hide the circled frame on the screenshot?

Thank you.

![InkedWoWScrnShot_050120_140519_LI](https://user-images.githubusercontent.com/24496956/80804702-3eac2800-8bb6-11ea-808e-cc02a795dfc0.jpg)

**Comment by rokpusnik** [comment]
that's the tooltip frame. you can play around with it by using these settings 
![image](https://user-images.githubusercontent.com/49006425/80804938-f17c8600-8bb6-11ea-9f82-a7c78170e04a.png)
as well as moving its anchor by toggling anchors and moving it around to wherever you like
