### ISSUE TITLE
Minimap buff bar.

### ISSUE THREAD

**Issue by FilipiBrabo** [ElvUI-WotLK/ElvUI#728]
**Minimap buff bar**

There's no buffbar and 'C' button on my minimap and I can't find the option to turn it on.

**Version Number**
6.07

![image](https://user-images.githubusercontent.com/33284760/81628786-ea841d80-93d7-11ea-85be-da0d7f0816a4.png)

(This is from a year a go, i don't remember the version)
![image](https://user-images.githubusercontent.com/33284760/81628746-db9d6b00-93d7-11ea-94be-341f295a2412.png)

**Comment by FilipiBrabo** [comment]
Thank you!

**Comment by Vapor312904** [comment]
how i can find it in version 12.91 ?

**Comment by Fanquar** [comment]
> how i can find it in version 12.91 ?

this is for WotLK Private servers, you'll have to ask in https://github.com/tukui-org/ElvUI or on their discord server for WotLK Classic
