### ISSUE TITLE
chatbar

### ISSUE THREAD

**Issue by xdenial** [ElvUI-WotLK/ElvUI#73]
In older versions was chatbar.
It is possible to add a new version?

![chatbar](https://cloud.githubusercontent.com/assets/15176640/10561895/15e0f086-7559-11e5-8581-fb96d909d664.jpg)

**Comment by Bunny67** [comment]
In ElvUI I add I will not try to match the features of the original version. The plug-in can add

Ru: В ЕлвУИ добовлять не буду, стараюсь что бы функции соответствовали оригинальной версии. В плагин можно добавить

**Comment by crumdidlyumshis** [comment]
Close or make addon?

**Comment by Bunny67** [comment]
close
use addon on the chatbar
