### ISSUE TITLE
Realm time is incorrect. Only displays local time.

### ISSUE THREAD

**Issue by Triksterism** [ElvUI-WotLK/ElvUI#732]
**Description**
The time displayed on my datatexts for time only shows my local time. When I hover over the time with my cursor to show lockouts + realm time, the realm time is the same as my local time (I'm in the US and my local time is 4hrs behind realm time) -- This is very incorrect and has been an issue since 6.07

Toggling "realm time" in the datatexts options does not change this either.

**Version Number**
6.07

**Steps to Reproduce**
I have tested this with a fresh character + a fresh ElvUI profile with only ElvUI loaded (no plugins) and the result is the same.

**Expected Behavior**
The datatexts should display realm time in the tooltip when hovering over the time

**Actual Behavior**
Datatexts for time only shows local time no matter what options are selected.

**Only ElvUI Enabled**
This happens no matter what addons are enabled.

**Blizzard Issue?**
See above

**Additional Information**
N/A

**Error Log**
N/A

**Comment by jeyrella** [comment]
This still seems to be a problem, aggravated now that the daylight savings has changed.

**Comment by foxtoopia12** [comment]
yea I got this issue on one of my account but I don't on my two other accounts.

**Comment by jeyrella** [comment]
Any chance this might be looked at?  it still seems to be an issue

**Comment by Crumdidlyumshis** [comment]
Honestly, I am not sure exactly what could be causing this issue. I personally play on Warmane - Lordaeron and from what I can see, the server time and my local time is correct. 

![image](https://user-images.githubusercontent.com/7307335/107867251-f3aa8b00-6e3e-11eb-9435-f5a38feb1c50.png)
