### ISSUE TITLE
LFB Support [ButtonFacade]

### ISSUE THREAD

**Issue by 3majed** [ElvUI-WotLK/ElvUI#734]
**Description**
Unlike other addons, ElvUI resets ButtonFacade ActionBars & Aura settings every reload, relog, restart WoW, or editing ActionBars setting in Elvui options menu.
I also have WeakAuras It keeps the skin while Elvui doesn't

**Version Number**
6.07

**Comment by GodinRaider** [comment]
![image](https://user-images.githubusercontent.com/22397709/85155454-730c9e00-b261-11ea-8a32-6e2d28ace09b.png)

Have you activated this option in the panel menu?

**Comment by 3majed** [comment]
Yes otherwise it wont accept the skin, However after I select the skin from ButtonFacade (both global Settings and AddOns settings) for example Onyx and reload it goes back to Blizzard skin
