### ISSUE TITLE
Sunn - Viewport Art - Disabled by ElviUI

### ISSUE THREAD

**Issue by mati3464** [ElvUI-WotLK/ElvUI#744]
**Description**
After updated ElviUI my Sunn - Viewport Art is disabled. Even if i have addon "Sunn - Viewport Art" enabled and type /sa, i get error " type /help for listing of a few commands "

If i disable ElviUI sun art start working and everything is ok. Happened after update ElviUI

**Version Number**
<"11.44") -->

IMG>

https://i.imgur.com/8aChAHb.jpg

Found this from git but seems that lines are enabled, expect core looks different 

https://git.tukui.org/shadow-and-light/shadow-and-light/-/issues/134

**Comment by Bunny67** [comment]
This ElvUI not for retail client. Report this bug here: https://git.tukui.org/elvui/elvui/-/issues
