### ISSUE TITLE
LootRoll Fonts Issue

### ISSUE THREAD

**Issue by Noob1e** [ElvUI-WotLK/ElvUI#751]
**Description**
LootRoll frame fonts looks bad and I can't change that.

**Version Number**
6.08

**Expected Behavior**
It should has an option to change fonts.

**Actual Behavior**
I can't change the fonts.

**Blizzard Issue?**
No.

**Additional Information**
It was working and looking good before the last updates.

**Comment by Bunny67** [comment]
fix in https://github.com/ElvUI-WotLK/ElvUI/commit/63dc456a48d4ed228dd8199fe314842c51ac9c7b
