### ISSUE TITLE
Extended Chat Window

### ISSUE THREAD

**Issue by Noob1e** [ElvUI-WotLK/ElvUI#759]
https://imgur.com/a/UGY1XPw

The button in the SS (top right corner) can make a separate window but is there any way to extend that window? If not, can you add a button at the lower right corner for it?

**Comment by Apollyonn** [comment]
Right click at the top and drag it.
![e](https://user-images.githubusercontent.com/19589902/92938550-58f3ed80-f455-11ea-8ff4-d61c0fb61c7a.gif)
