### ISSUE TITLE
Add Skada revisited to addon skins

### ISSUE THREAD

**Issue by Jujkavn** [ElvUI-WotLK/ElvUI#785]
Please add https://github.com/bkader/Skada-Revisited to addon skins.

**Comment by bkader** [comment]
I have modified 2 files within for the addonskins, you can try it. It allows the module to Skin **Skada Revisited**. [Download it here](https://www.mediafire.com/file/d80fekzo5l0ylhy/ElvUI_AddOnSkins.zip/file)

**Comment by Jujkavn** [comment]
Thank you

**Comment by Zidras** [comment]
@bkader Why not fork it and pull request?

**Comment by bkader** [comment]
@Zidras because imo modifying the whole ElvUI for only a single addon isn't worth it because the majority uses the old default skada.

**Comment by bkader** [comment]
> 
> 
> Please add https://github.com/bkader/Skada-Revisited to addon skins.

The addon was updated and it comes now with optional **ElvUI_AddOnSkins** integration. [Check it here](https://github.com/bkader/Skada-Revisited)
