### ISSUE TITLE
\DataTexts\Guild.lua:288        ERROR

### ISSUE THREAD

**Issue by XIAOPPTIAN** [ElvUI-WotLK/ElvUI#800]
WHEN I LOG IN, ELVUI SEND A ERROR. 

Message: Interface\AddOns\ElvUI\Modules\DataTexts\Guild.lua:288: bad argument #2 to 'find' (string expected, got nil)
Time: 05/09/21 14:45:02
Count: 4
Stack: [C]: ?
[C]: ?
Interface\AddOns\ElvUI\Modules\DataTexts\Guild.lua:288: in function `?'
Interface\AddOns\ElvUI\Modules\DataTexts\Guild.lua:311: in function <Interface\AddOns\ElvUI\Modules\DataTexts\Guild.lua:307>

HOW COULD I RESOLVE THIS PROBLEM?
MERCI EN AVANCE
![WoWScrnShot_050921_144939](https://user-images.githubusercontent.com/83899366/117563050-d26fd880-b0d5-11eb-9ee2-c401aa0fcaaf.jpg)

**Comment by M5Fkevin** [comment]
Interface\AddOns\ElvUI\Modules\DataTexts\Guild.lua:288: bad argument #2 to 'find' (string expected, got nil)
Count: 8

Call Stack:
[C]: ?
[C]: ?
Interface\AddOns\ElvUI\Modules\DataTexts\Guild.lua:288: in function `?'
Interface\AddOns\ElvUI\Modules\DataTexts\Guild.lua:311: in function <Interface\AddOns\ElvUI\Modules\DataTexts\Guild.lua:307>

**Comment by M5Fkevin** [comment]
Sorry, can you ask another question? : 
AceLocale-3.0: Mapster: Missing entry for 'Profiles'Count: 1
Call Stack:...ddOns\AtlasLoot\Libs\AceLocale-3.0\AceLocale-3.0.lua:31: in function <...ddOns\AtlasLoot\Libs\AceLocale-3.0\AceLocale-3.0.lua:29>Interface\AddOns\Mapster\Config.lua:179: in function `SetupOptions'Interface\AddOns\Mapster\Mapster.lua:77: in function <Interface\AddOns\Mapster\Mapster.lua:67>(tail call): ?[C]: ?[string "safecall Dispatcher[1]"]:9: in function <[string "safecall Dispatcher[1]"]:5>(tail call): ?...s\ElvUI\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0.lua:529: in function `InitializeAddon'...s\ElvUI\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0.lua:644: in function <...s\ElvUI\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0.lua:636>[C]: in function `LoadAddOn'Interface\AddOns\Duowan\Duowan.lua:682: in function `dwLoadAddOn'Interface\AddOns\Duowan\Configs\SexyMap.lua:92: in function <Interface\AddOns\Duowan\Configs\SexyMap.lua:89>[C]: in function `pcall'Interface\AddOns\Duowan\ConfigFrame.lua:1089: in function `dwTriggerMod'Interface\AddOns\Duowan\ConfigFrame.lua:1133: in function `dwConfigFrame_OnEvent'[string "*:OnEvent"]:1: in function <[string "*:OnEvent"]:1>
 Which UI is wrong with this error?If it disturbs, please forgive meHave a beautiful day
   在 2021年5月16日 星期日 下午01:13:20 [GMT+8]， ***@***.***> 寫道：  
 
 


Closed #800 via 35e4291.

**Comment by Loaal** [comment]
This error not related to ElvUI.
This error appears if there is no translation for particular key, in your case for it's "Profiles".
ElvUI appears in error log only because it contain updated version of AceAddon library.
