### ISSUE TITLE
ItemSearch - CustomSearch

### ISSUE THREAD

**Issue by dinh1405** [ElvUI-WotLK/ElvUI#81]
Message: ...ItemSearch-1.2\CustomSearch-1.0\CustomSearch-1.0.lua:146: attempt to index local 'string' (a nil value)
Time: 10/29/15 09:37:03
Count: 1
Stack: ...ItemSearch-1.2\CustomSearch-1.0\CustomSearch-1.0.lua:146: in function `Clean'
...ItemSearch-1.2\CustomSearch-1.0\CustomSearch-1.0.lua:199: in main chunk

Locals: self = <table> {
 Find = <function> defined @Interface\AddOns\ElvUI\libs\LibItemSearch-1.2\CustomSearch-1.0\CustomSearch-1.0.lua:133
 Match = <function> defined @Interface\AddOns\ElvUI\libs\LibItemSearch-1.2\CustomSearch-1.0\CustomSearch-1.0.lua:56
 MatchAny = <function> defined @Interface\AddOns\ElvUI\libs\LibItemSearch-1.2\CustomSearch-1.0\CustomSearch-1.0.lua:48
 ACCENTS = <table> {
 }
 MatchAll = <function> defined @Interface\AddOns\ElvUI\libs\LibItemSearch-1.2\CustomSearch-1.0\CustomSearch-1.0.lua:38
 UseFilter = <function> defined @Interface\AddOns\ElvUI\libs\LibItemSearch-1.2\CustomSearch-1.0\CustomSearch-1.0.lua:123
 Compare = <function> defined @Interface\AddOns\ElvUI\libs\LibItemSearch-1.2\CustomSearch-1.0\CustomSearch-1.0.lua:155
 Matches = <function> defined @Interface\AddOns\ElvUI\libs\LibItemSearch-1.2\CustomSearch-1.0\CustomSearch-1.0.lua:29
 Filter = <function> defined @Interface\AddOns\ElvUI\libs\LibItemSearch-1.2\CustomSearch-1.0\CustomSearch-1.0.lua:101
 Clean = <function> defined @Interface\AddOns\ElvUI\libs\LibItemSearch-1.2\CustomSearch-1.0\CustomSearch-1.0.lua:145
}
string = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'string' (a nil value)"

--------------------------------------------------------------------------------

How can i fix it?

**Comment by crumdidlyumshis** [comment]
Have never had this issue. Close? Probably fixed already?
