### ISSUE TITLE
Absorbs and Shields

### ISSUE THREAD

**Issue by SapoQLxd** [ElvUI-WotLK/ElvUI#829]
# Feature request
Absorbs and Shields on unitframes, it's on retail but not here on this version, very useful for disc priest or even for small shields like sacred shield and such.
It should be in heal prediction section, under the Colors part on General Options.

**Comment by Zidras** [comment]
> # Feature request
> Absorbs and Shields on unitframes, it's on retail but not here on this version, very useful for disc priest or even for small shields like sacred shield and such. It should be in heal prediction section, under the Colors part on General Options.

https://github.com/Zidras/ElvUI_ProjectZidras

**Comment by SapoQLxd** [comment]
Thanks, I searched everywhere but couldnt find anything for elvUI, and for some reason your project wasnt recommended anywhere.
