### ISSUE TITLE
Clock is always 24 hour mode, even when unticked

### ISSUE THREAD

**Issue by Mrhgb** [ElvUI-WotLK/ElvUI#858]
**Description**

I have unticked 24 hour mode on the clock but it still shows as 24 hour instead of 12 hour.

**Version Number**

13.54

**Steps to Reproduce**

1. Right click on the clock module at the bottom
2. Untick 24 hour mode

**Expected Behavior**

The clock should read 5:31pm instead of 17:51

**Actual Behavior**

The clock remains in 24 hour mode

**Only ElvUI Enabled**

Yes, it happens with just Elvui enabled

**Blizzard Issue?**

With default UI, it shows up correctly as 5:31
![Screenshot 2023-12-21 174947](https://github.com/ElvUI-WotLK/ElvUI/assets/7623941/c1945029-2c80-4710-bdfb-0b8a8812e2f7)

**Additional Information**

**Error Log**

```

```

**Comment by Mrhgb** [comment]
I should note it changes correctly on the clock menu, but not on the bottom data text bar.

**Comment by Zidras** [comment]
Handled here
![image](https://github.com/ElvUI-WotLK/ElvUI/assets/10605951/a8232c85-a8fd-4091-ab28-489ac7819127)

**Comment by Crumdidlyumshis** [comment]
Should also note.... this is not the correct version of the addon as they are on a retail version of the addon.

@Mrhgb Please go here for support: https://github.com/tukui-org/ElvUI
