### ISSUE TITLE
Party Leader Crown

### ISSUE THREAD

**Issue by crumdidlyumshis** [ElvUI-WotLK/ElvUI#88]
Party leader crown displays on more than one person. Should only be one.

![wowscrnshot_111215_224035](https://cloud.githubusercontent.com/assets/7307335/11160942/4d15ac70-8a37-11e5-8669-47569591368b.jpg)

**Comment by Bunny67** [comment]
I know about the bug, but the fix is not yet able to :( Where is the error in the Raid/Group frames

**Comment by crumdidlyumshis** [comment]
Ah okay. I am not sure where the error would be. It doesn't seem to throw any errors while playing.

**Comment by Bunny67** [comment]
Somewhere* Google translete fail:(

**Comment by crumdidlyumshis** [comment]
I haven't noticed this again. Can anyone verify?

**Comment by Bunny67** [comment]
bug yet remained

**Comment by crumdidlyumshis** [comment]
Bug still remains.

**Comment by Bunny67** [comment]
I think it is a problem Server, as 2-3 years nebylo bug

**Comment by crumdidlyumshis** [comment]
Ah ok. Sounds like same bug as quest tracker bug. Maybe I'll close for now.

**Comment by Bunny67** [comment]
You can check other raid frames

**Comment by crumdidlyumshis** [comment]
I might do that when I get home later. Good suggestion!
